// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: admin_platform.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminOrdersByDay = `-- name: AdminOrdersByDay :many
SELECT
    date_trunc('day', created_at)::date AS day,
    COUNT(*)::bigint AS order_count,
    COALESCE(SUM(total), 0)::text AS revenue
FROM orders
WHERE created_at >= now() - interval '30 days'
GROUP BY 1
ORDER BY 1 ASC
`

type AdminOrdersByDayRow struct {
	Day        pgtype.Date `json:"day"`
	OrderCount int64       `json:"order_count"`
	Revenue    string      `json:"revenue"`
}

func (q *Queries) AdminOrdersByDay(ctx context.Context) ([]AdminOrdersByDayRow, error) {
	rows, err := q.db.Query(ctx, adminOrdersByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminOrdersByDayRow{}
	for rows.Next() {
		var i AdminOrdersByDayRow
		if err := rows.Scan(&i.Day, &i.OrderCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminTenantsByWeek = `-- name: AdminTenantsByWeek :many
SELECT
    date_trunc('week', created_at)::date AS week_start,
    COUNT(*)::bigint AS tenant_count
FROM tenants
WHERE created_at >= now() - interval '84 days'
GROUP BY 1
ORDER BY 1 ASC
`

type AdminTenantsByWeekRow struct {
	WeekStart   pgtype.Date `json:"week_start"`
	TenantCount int64       `json:"tenant_count"`
}

func (q *Queries) AdminTenantsByWeek(ctx context.Context) ([]AdminTenantsByWeekRow, error) {
	rows, err := q.db.Query(ctx, adminTenantsByWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminTenantsByWeekRow{}
	for rows.Next() {
		var i AdminTenantsByWeekRow
		if err := rows.Scan(&i.WeekStart, &i.TenantCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActivePlatformAdmins = `-- name: CountActivePlatformAdmins :one
SELECT COUNT(*)::bigint
FROM users
WHERE tenant_id IS NULL
  AND role IN ('SUPER_ADMIN', 'PLATFORM_ADMIN')
  AND status = 'ACTIVE'
`

func (q *Queries) CountActivePlatformAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePlatformAdmins)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createConsoleUser = `-- name: CreateConsoleUser :one
INSERT INTO users (tenant_id, name, email, phone, password_hash, role, status, must_set_password, invite_token_hash)
VALUES (NULL, $1, $2, $3, $4,
        $5, 'ACTIVE', TRUE, $6)
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type CreateConsoleUserParams struct {
	Name            string      `json:"name"`
	Email           string      `json:"email"`
	Phone           string      `json:"phone"`
	PasswordHash    string      `json:"password_hash"`
	Role            string      `json:"role"`
	InviteTokenHash pgtype.Text `json:"invite_token_hash"`
}

func (q *Queries) CreateConsoleUser(ctx context.Context, arg CreateConsoleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createConsoleUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.InviteTokenHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const listAuditLogsByResult = `-- name: ListAuditLogsByResult :many
SELECT
    a.id, a.action, a.entity_type, a.entity_id, a.result, a.metadata,
    a.created_at, a.tenant_id,
    u.name AS actor_name, u.email AS actor_email,
    t.name AS tenant_name, t.slug AS tenant_slug
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
LEFT JOIN tenants t ON t.id = a.tenant_id
WHERE a.result = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type ListAuditLogsByResultParams struct {
	Result   string `json:"result"`
	RowLimit int32  `json:"row_limit"`
}

type ListAuditLogsByResultRow struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Result     string             `json:"result"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorName  pgtype.Text        `json:"actor_name"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	TenantName pgtype.Text        `json:"tenant_name"`
	TenantSlug pgtype.Text        `json:"tenant_slug"`
}

func (q *Queries) ListAuditLogsByResult(ctx context.Context, arg ListAuditLogsByResultParams) ([]ListAuditLogsByResultRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByResult, arg.Result, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByResultRow{}
	for rows.Next() {
		var i ListAuditLogsByResultRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Result,
			&i.Metadata,
			&i.CreatedAt,
			&i.TenantID,
			&i.ActorName,
			&i.ActorEmail,
			&i.TenantName,
			&i.TenantSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTenantAndResult = `-- name: ListAuditLogsByTenantAndResult :many
SELECT
    a.id, a.action, a.entity_type, a.entity_id, a.result, a.metadata,
    a.created_at, a.tenant_id,
    u.name AS actor_name, u.email AS actor_email,
    t.name AS tenant_name, t.slug AS tenant_slug
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
LEFT JOIN tenants t ON t.id = a.tenant_id
WHERE a.tenant_id = $1 AND a.result = $2
ORDER BY a.created_at DESC
LIMIT $3
`

type ListAuditLogsByTenantAndResultParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Result   string      `json:"result"`
	RowLimit int32       `json:"row_limit"`
}

type ListAuditLogsByTenantAndResultRow struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Result     string             `json:"result"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorName  pgtype.Text        `json:"actor_name"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	TenantName pgtype.Text        `json:"tenant_name"`
	TenantSlug pgtype.Text        `json:"tenant_slug"`
}

func (q *Queries) ListAuditLogsByTenantAndResult(ctx context.Context, arg ListAuditLogsByTenantAndResultParams) ([]ListAuditLogsByTenantAndResultRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByTenantAndResult, arg.TenantID, arg.Result, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByTenantAndResultRow{}
	for rows.Next() {
		var i ListAuditLogsByTenantAndResultRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Result,
			&i.Metadata,
			&i.CreatedAt,
			&i.TenantID,
			&i.ActorName,
			&i.ActorEmail,
			&i.TenantName,
			&i.TenantSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsEnriched = `-- name: ListAuditLogsEnriched :many
SELECT
    a.id,
    a.action,
    a.entity_type,
    a.entity_id,
    a.result,
    a.metadata,
    a.created_at,
    a.tenant_id,
    u.name AS actor_name,
    u.email AS actor_email,
    t.name AS tenant_name,
    t.slug AS tenant_slug
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
LEFT JOIN tenants t ON t.id = a.tenant_id
ORDER BY a.created_at DESC
LIMIT $1
`

type ListAuditLogsEnrichedRow struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Result     string             `json:"result"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorName  pgtype.Text        `json:"actor_name"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	TenantName pgtype.Text        `json:"tenant_name"`
	TenantSlug pgtype.Text        `json:"tenant_slug"`
}

func (q *Queries) ListAuditLogsEnriched(ctx context.Context, rowLimit int32) ([]ListAuditLogsEnrichedRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsEnriched, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsEnrichedRow{}
	for rows.Next() {
		var i ListAuditLogsEnrichedRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Result,
			&i.Metadata,
			&i.CreatedAt,
			&i.TenantID,
			&i.ActorName,
			&i.ActorEmail,
			&i.TenantName,
			&i.TenantSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsEnrichedByTenant = `-- name: ListAuditLogsEnrichedByTenant :many
SELECT
    a.id,
    a.action,
    a.entity_type,
    a.entity_id,
    a.result,
    a.metadata,
    a.created_at,
    a.tenant_id,
    u.name AS actor_name,
    u.email AS actor_email,
    t.name AS tenant_name,
    t.slug AS tenant_slug
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
LEFT JOIN tenants t ON t.id = a.tenant_id
WHERE a.tenant_id = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type ListAuditLogsEnrichedByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RowLimit int32       `json:"row_limit"`
}

type ListAuditLogsEnrichedByTenantRow struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Result     string             `json:"result"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorName  pgtype.Text        `json:"actor_name"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	TenantName pgtype.Text        `json:"tenant_name"`
	TenantSlug pgtype.Text        `json:"tenant_slug"`
}

func (q *Queries) ListAuditLogsEnrichedByTenant(ctx context.Context, arg ListAuditLogsEnrichedByTenantParams) ([]ListAuditLogsEnrichedByTenantRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsEnrichedByTenant, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsEnrichedByTenantRow{}
	for rows.Next() {
		var i ListAuditLogsEnrichedByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Result,
			&i.Metadata,
			&i.CreatedAt,
			&i.TenantID,
			&i.ActorName,
			&i.ActorEmail,
			&i.TenantName,
			&i.TenantSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleUsers = `-- name: ListConsoleUsers :many
SELECT
    u.id,
    u.name,
    u.email,
    u.phone,
    u.role,
    u.status,
    u.must_set_password,
    u.created_at,
    (SELECT MAX(rt.created_at) FROM refresh_tokens rt WHERE rt.user_id = u.id) AS last_activity,
    (SELECT COUNT(*)::bigint FROM refresh_tokens rt
      WHERE rt.user_id = u.id AND rt.expires_at > now()) AS active_sessions
FROM users u
WHERE u.tenant_id IS NULL
ORDER BY
    CASE u.role WHEN 'SUPER_ADMIN' THEN 0 WHEN 'PLATFORM_ADMIN' THEN 1 ELSE 2 END,
    u.created_at ASC
`

type ListConsoleUsersRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	MustSetPassword bool               `json:"must_set_password"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastActivity    interface{}        `json:"last_activity"`
	ActiveSessions  int64              `json:"active_sessions"`
}

// Everyone who can reach the platform console. Business users are excluded by
// construction: a console identity has no tenant.
func (q *Queries) ListConsoleUsers(ctx context.Context) ([]ListConsoleUsersRow, error) {
	rows, err := q.db.Query(ctx, listConsoleUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConsoleUsersRow{}
	for rows.Next() {
		var i ListConsoleUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Status,
			&i.MustSetPassword,
			&i.CreatedAt,
			&i.LastActivity,
			&i.ActiveSessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringSubscriptions = `-- name: ListExpiringSubscriptions :many
SELECT
    s.id,
    s.tenant_id,
    t.name AS tenant_name,
    t.slug AS tenant_slug,
    p.name AS plan_name,
    s.status,
    s.end_at
FROM subscriptions s
JOIN tenants t ON t.id = s.tenant_id
JOIN plans p ON p.id = s.plan_id
WHERE s.end_at IS NOT NULL
  AND s.status IN ('TRIAL', 'ACTIVE')
  AND s.end_at <= now() + make_interval(days => $1::int)
ORDER BY s.end_at ASC
LIMIT 20
`

type ListExpiringSubscriptionsRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	TenantName string             `json:"tenant_name"`
	TenantSlug string             `json:"tenant_slug"`
	PlanName   string             `json:"plan_name"`
	Status     string             `json:"status"`
	EndAt      pgtype.Timestamptz `json:"end_at"`
}

// Subscriptions whose trial or term ends inside the window, newest deadline
// first. The dashboard's "needs attention" list is built from this rather than
// from a client-side scan of every subscription.
func (q *Queries) ListExpiringSubscriptions(ctx context.Context, withinDays int32) ([]ListExpiringSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringSubscriptions, withinDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringSubscriptionsRow{}
	for rows.Next() {
		var i ListExpiringSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TenantName,
			&i.TenantSlug,
			&i.PlanName,
			&i.Status,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformUsers = `-- name: ListPlatformUsers :many
SELECT
    u.id,
    u.name,
    u.email,
    u.phone,
    u.role,
    u.status,
    u.must_set_password,
    u.created_at,
    u.tenant_id,
    t.name AS tenant_name,
    t.slug AS tenant_slug,
    t.status AS tenant_status,
    (SELECT MAX(rt.created_at) FROM refresh_tokens rt WHERE rt.user_id = u.id) AS last_activity
FROM users u
LEFT JOIN tenants t ON t.id = u.tenant_id
ORDER BY (u.tenant_id IS NOT NULL), u.created_at DESC
`

type ListPlatformUsersRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	MustSetPassword bool               `json:"must_set_password"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	TenantName      pgtype.Text        `json:"tenant_name"`
	TenantSlug      pgtype.Text        `json:"tenant_slug"`
	TenantStatus    pgtype.Text        `json:"tenant_status"`
	LastActivity    interface{}        `json:"last_activity"`
}

// Every identity the platform knows about, tenant-scoped or not. The platform
// owner (SUPER_ADMIN, tenant_id NULL) is included on purpose: IAM has to show
// who can reach the console, and leaving the one account that can out of the
// list made the page lie. last_activity is the most recent session issued to
// the user, which is the closest thing to a sign-in time the schema records.
func (q *Queries) ListPlatformUsers(ctx context.Context) ([]ListPlatformUsersRow, error) {
	rows, err := q.db.Query(ctx, listPlatformUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformUsersRow{}
	for rows.Next() {
		var i ListPlatformUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Status,
			&i.MustSetPassword,
			&i.CreatedAt,
			&i.TenantID,
			&i.TenantName,
			&i.TenantSlug,
			&i.TenantStatus,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsAdmin = `-- name: ListSubscriptionsAdmin :many
SELECT
    s.id,
    s.tenant_id,
    s.plan_id,
    s.status,
    s.start_at,
    s.end_at,
    s.created_at,
    t.name AS tenant_name,
    p.name AS plan_name,
    p.price AS plan_price
FROM subscriptions s
JOIN tenants t ON t.id = s.tenant_id
JOIN plans p ON p.id = s.plan_id
ORDER BY s.created_at DESC
`

type ListSubscriptionsAdminRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	PlanID     pgtype.UUID        `json:"plan_id"`
	Status     string             `json:"status"`
	StartAt    pgtype.Timestamptz `json:"start_at"`
	EndAt      pgtype.Timestamptz `json:"end_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantName string             `json:"tenant_name"`
	PlanName   string             `json:"plan_name"`
	PlanPrice  pgtype.Numeric     `json:"plan_price"`
}

func (q *Queries) ListSubscriptionsAdmin(ctx context.Context) ([]ListSubscriptionsAdminRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsAdminRow{}
	for rows.Next() {
		var i ListSubscriptionsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PlanID,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.TenantName,
			&i.PlanName,
			&i.PlanPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsAwaitingSetup = `-- name: ListTenantsAwaitingSetup :many
SELECT
    t.id,
    t.name,
    t.slug,
    t.status,
    t.created_at
FROM tenants t
WHERE t.setup_status <> 'COMPLETED'
ORDER BY t.created_at DESC
LIMIT 20
`

type ListTenantsAwaitingSetupRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Businesses whose administrator has never set a password. They are onboarded
// but nobody can sign in, which is the single most common thing a Super Admin
// needs to chase.
func (q *Queries) ListTenantsAwaitingSetup(ctx context.Context) ([]ListTenantsAwaitingSetupRow, error) {
	rows, err := q.db.Query(ctx, listTenantsAwaitingSetup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsAwaitingSetupRow{}
	for rows.Next() {
		var i ListTenantsAwaitingSetupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantAdminMetrics = `-- name: TenantAdminMetrics :one
SELECT
    (SELECT COUNT(*)::bigint FROM orders o WHERE o.tenant_id = $1) AS total_orders,
    COALESCE((
        SELECT SUM(o.total) FROM orders o
        WHERE o.tenant_id = $1 AND o.status = 'COMPLETED'
    ), 0)::text AS total_revenue,
    (SELECT COUNT(*)::bigint FROM users u WHERE u.tenant_id = $1 AND u.status = 'ACTIVE') AS active_users,
    (SELECT COUNT(*)::bigint FROM orders o
     WHERE o.tenant_id = $1
       AND o.created_at >= date_trunc('day', now())) AS orders_today,
    COALESCE((
        SELECT SUM(o.total) FROM orders o
        WHERE o.tenant_id = $1
          AND o.status <> 'CANCELLED'
          AND o.created_at >= date_trunc('day', now())
    ), 0)::text AS revenue_today,
    (SELECT COUNT(*)::bigint FROM orders o
     WHERE o.tenant_id = $1 AND o.status = 'CANCELLED') AS cancelled_orders,
    COALESCE((
        SELECT AVG(o.total) FROM orders o
        WHERE o.tenant_id = $1 AND o.status = 'COMPLETED'
    ), 0)::text AS avg_order_value,
    (SELECT MIN(o.created_at) FROM orders o WHERE o.tenant_id = $1) AS first_order_at,
    (SELECT MAX(o.created_at) FROM orders o WHERE o.tenant_id = $1) AS last_order_at
`

type TenantAdminMetricsRow struct {
	TotalOrders     int64       `json:"total_orders"`
	TotalRevenue    string      `json:"total_revenue"`
	ActiveUsers     int64       `json:"active_users"`
	OrdersToday     int64       `json:"orders_today"`
	RevenueToday    string      `json:"revenue_today"`
	CancelledOrders int64       `json:"cancelled_orders"`
	AvgOrderValue   string      `json:"avg_order_value"`
	FirstOrderAt    interface{} `json:"first_order_at"`
	LastOrderAt     interface{} `json:"last_order_at"`
}

func (q *Queries) TenantAdminMetrics(ctx context.Context, tenantID pgtype.UUID) (TenantAdminMetricsRow, error) {
	row := q.db.QueryRow(ctx, tenantAdminMetrics, tenantID)
	var i TenantAdminMetricsRow
	err := row.Scan(
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.ActiveUsers,
		&i.OrdersToday,
		&i.RevenueToday,
		&i.CancelledOrders,
		&i.AvgOrderValue,
		&i.FirstOrderAt,
		&i.LastOrderAt,
	)
	return i, err
}

const tenantOrderStatusBreakdown = `-- name: TenantOrderStatusBreakdown :many
SELECT
    o.status AS status,
    COUNT(*)::bigint AS count
FROM orders o
WHERE o.tenant_id = $1
GROUP BY o.status
ORDER BY 2 DESC
`

type TenantOrderStatusBreakdownRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) TenantOrderStatusBreakdown(ctx context.Context, tenantID pgtype.UUID) ([]TenantOrderStatusBreakdownRow, error) {
	rows, err := q.db.Query(ctx, tenantOrderStatusBreakdown, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantOrderStatusBreakdownRow{}
	for rows.Next() {
		var i TenantOrderStatusBreakdownRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantOrdersByDay = `-- name: TenantOrdersByDay :many
SELECT
    date_trunc('day', created_at)::date AS day,
    COUNT(*)::bigint AS order_count,
    COALESCE(SUM(CASE WHEN status <> 'CANCELLED' THEN total ELSE 0 END), 0)::text AS revenue
FROM orders
WHERE tenant_id = $1
    AND created_at >= now() - interval '30 days'
GROUP BY 1
ORDER BY 1 ASC
`

type TenantOrdersByDayRow struct {
	Day        pgtype.Date `json:"day"`
	OrderCount int64       `json:"order_count"`
	Revenue    string      `json:"revenue"`
}

func (q *Queries) TenantOrdersByDay(ctx context.Context, tenantID pgtype.UUID) ([]TenantOrdersByDayRow, error) {
	rows, err := q.db.Query(ctx, tenantOrdersByDay, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantOrdersByDayRow{}
	for rows.Next() {
		var i TenantOrdersByDayRow
		if err := rows.Scan(&i.Day, &i.OrderCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantSecuritySummary = `-- name: TenantSecuritySummary :one
SELECT
    (SELECT COUNT(*)::bigint FROM users u WHERE u.tenant_id = $1) AS users_total,
    (SELECT COUNT(*)::bigint FROM users u
     WHERE u.tenant_id = $1 AND u.status = 'ACTIVE') AS users_active,
    (SELECT COUNT(*)::bigint FROM users u
     WHERE u.tenant_id = $1 AND u.must_set_password) AS users_pending_password,
    (SELECT COUNT(*)::bigint
     FROM refresh_tokens rt
     JOIN users u ON u.id = rt.user_id
     WHERE u.tenant_id = $1 AND rt.expires_at > now()) AS active_sessions,
    (SELECT COUNT(*)::bigint FROM audit_logs a WHERE a.tenant_id = $1) AS audit_events,
    (SELECT COUNT(*)::bigint FROM audit_logs a
     WHERE a.tenant_id = $1
       AND a.created_at >= now() - interval '7 days') AS audit_events_7d
`

type TenantSecuritySummaryRow struct {
	UsersTotal           int64 `json:"users_total"`
	UsersActive          int64 `json:"users_active"`
	UsersPendingPassword int64 `json:"users_pending_password"`
	ActiveSessions       int64 `json:"active_sessions"`
	AuditEvents          int64 `json:"audit_events"`
	AuditEvents7d        int64 `json:"audit_events_7d"`
}

func (q *Queries) TenantSecuritySummary(ctx context.Context, tenantID pgtype.UUID) (TenantSecuritySummaryRow, error) {
	row := q.db.QueryRow(ctx, tenantSecuritySummary, tenantID)
	var i TenantSecuritySummaryRow
	err := row.Scan(
		&i.UsersTotal,
		&i.UsersActive,
		&i.UsersPendingPassword,
		&i.ActiveSessions,
		&i.AuditEvents,
		&i.AuditEvents7d,
	)
	return i, err
}
