// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (tenant_id, customer_id, service_id, staff_id, scheduled_at, status)
VALUES ($1, $2, $3, $4, $5, 'REQUESTED')
RETURNING id, tenant_id, customer_id, service_id, staff_id, scheduled_at, status, created_at, updated_at
`

type CreateAppointmentParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	ServiceID   pgtype.UUID        `json:"service_id"`
	StaffID     pgtype.UUID        `json:"staff_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.TenantID,
		arg.CustomerID,
		arg.ServiceID,
		arg.StaffID,
		arg.ScheduledAt,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StaffID,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQueueEntry = `-- name: CreateQueueEntry :one
INSERT INTO queue_entries (tenant_id, appointment_id, customer_id, queue_date, queue_number, status)
VALUES ($1, $2, $3, CURRENT_DATE, $4, 'WAITING')
RETURNING id, tenant_id, appointment_id, customer_id, queue_date, queue_number, status, created_at
`

type CreateQueueEntryParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	AppointmentID pgtype.UUID `json:"appointment_id"`
	CustomerID    pgtype.UUID `json:"customer_id"`
	QueueNumber   int32       `json:"queue_number"`
}

func (q *Queries) CreateQueueEntry(ctx context.Context, arg CreateQueueEntryParams) (QueueEntry, error) {
	row := q.db.QueryRow(ctx, createQueueEntry,
		arg.TenantID,
		arg.AppointmentID,
		arg.CustomerID,
		arg.QueueNumber,
	)
	var i QueueEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AppointmentID,
		&i.CustomerID,
		&i.QueueDate,
		&i.QueueNumber,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one

INSERT INTO services (tenant_id, name, duration_minutes, price, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, duration_minutes, price, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	TenantID        pgtype.UUID    `json:"tenant_id"`
	Name            string         `json:"name"`
	DurationMinutes int32          `json:"duration_minutes"`
	Price           pgtype.Numeric `json:"price"`
	IsActive        bool           `json:"is_active"`
}

// Barber Shop capability group: services, staff availability, appointments,
// and the shared walk-in/checked-in queue. Every statement is tenant-scoped.
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.TenantID,
		arg.Name,
		arg.DurationMinutes,
		arg.Price,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DurationMinutes,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStaffAvailability = `-- name: CreateStaffAvailability :one
INSERT INTO staff_availability (tenant_id, staff_id, weekday, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, staff_id, weekday, start_time, end_time
`

type CreateStaffAvailabilityParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	StaffID   pgtype.UUID `json:"staff_id"`
	Weekday   int32       `json:"weekday"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateStaffAvailability(ctx context.Context, arg CreateStaffAvailabilityParams) (StaffAvailability, error) {
	row := q.db.QueryRow(ctx, createStaffAvailability,
		arg.TenantID,
		arg.StaffID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
	)
	var i StaffAvailability
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1 AND tenant_id = $2
`

type DeleteServiceParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) error {
	_, err := q.db.Exec(ctx, deleteService, arg.ID, arg.TenantID)
	return err
}

const deleteStaffAvailability = `-- name: DeleteStaffAvailability :exec
DELETE FROM staff_availability WHERE id = $1 AND tenant_id = $2
`

type DeleteStaffAvailabilityParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteStaffAvailability(ctx context.Context, arg DeleteStaffAvailabilityParams) error {
	_, err := q.db.Exec(ctx, deleteStaffAvailability, arg.ID, arg.TenantID)
	return err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, tenant_id, customer_id, service_id, staff_id, scheduled_at, status, created_at, updated_at FROM appointments WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetAppointmentByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetAppointmentByID(ctx context.Context, arg GetAppointmentByIDParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, arg.ID, arg.TenantID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StaffID,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, tenant_id, name, duration_minutes, price, is_active, created_at, updated_at FROM services WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetServiceByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, arg.ID, arg.TenantID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DurationMinutes,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointmentsByTenant = `-- name: ListAppointmentsByTenant :many
SELECT id, tenant_id, customer_id, service_id, staff_id, scheduled_at, status, created_at, updated_at FROM appointments WHERE tenant_id = $1 ORDER BY scheduled_at DESC LIMIT $2
`

type ListAppointmentsByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListAppointmentsByTenant(ctx context.Context, arg ListAppointmentsByTenantParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ServiceID,
			&i.StaffID,
			&i.ScheduledAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByTenant = `-- name: ListServicesByTenant :many
SELECT id, tenant_id, name, duration_minutes, price, is_active, created_at, updated_at FROM services WHERE tenant_id = $1 ORDER BY name ASC
`

func (q *Queries) ListServicesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DurationMinutes,
			&i.Price,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffAvailabilityByTenant = `-- name: ListStaffAvailabilityByTenant :many
SELECT id, tenant_id, staff_id, weekday, start_time, end_time FROM staff_availability WHERE tenant_id = $1 ORDER BY staff_id, weekday
`

func (q *Queries) ListStaffAvailabilityByTenant(ctx context.Context, tenantID pgtype.UUID) ([]StaffAvailability, error) {
	rows, err := q.db.Query(ctx, listStaffAvailabilityByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffAvailability{}
	for rows.Next() {
		var i StaffAvailability
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StaffID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayQueue = `-- name: ListTodayQueue :many
SELECT id, tenant_id, appointment_id, customer_id, queue_date, queue_number, status, created_at FROM queue_entries
WHERE tenant_id = $1 AND queue_date = CURRENT_DATE
ORDER BY queue_number ASC
`

func (q *Queries) ListTodayQueue(ctx context.Context, tenantID pgtype.UUID) ([]QueueEntry, error) {
	rows, err := q.db.Query(ctx, listTodayQueue, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueEntry{}
	for rows.Next() {
		var i QueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AppointmentID,
			&i.CustomerID,
			&i.QueueDate,
			&i.QueueNumber,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointments = `-- name: ListUpcomingAppointments :many
SELECT id, tenant_id, customer_id, service_id, staff_id, scheduled_at, status, created_at, updated_at FROM appointments
WHERE tenant_id = $1 AND status NOT IN ('COMPLETED', 'CANCELLED', 'NO_SHOW')
ORDER BY scheduled_at ASC
`

func (q *Queries) ListUpcomingAppointments(ctx context.Context, tenantID pgtype.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listUpcomingAppointments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ServiceID,
			&i.StaffID,
			&i.ScheduledAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextQueueNumberToday = `-- name: NextQueueNumberToday :one
SELECT COALESCE(MAX(queue_number), 0) + 1 AS next_number
FROM queue_entries
WHERE tenant_id = $1 AND queue_date = CURRENT_DATE
`

func (q *Queries) NextQueueNumberToday(ctx context.Context, tenantID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextQueueNumberToday, tenantID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments SET status = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, service_id, staff_id, scheduled_at, status, created_at, updated_at
`

type UpdateAppointmentStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentStatus, arg.ID, arg.TenantID, arg.Status)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StaffID,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQueueEntryStatus = `-- name: UpdateQueueEntryStatus :one
UPDATE queue_entries SET status = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, appointment_id, customer_id, queue_date, queue_number, status, created_at
`

type UpdateQueueEntryStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateQueueEntryStatus(ctx context.Context, arg UpdateQueueEntryStatusParams) (QueueEntry, error) {
	row := q.db.QueryRow(ctx, updateQueueEntryStatus, arg.ID, arg.TenantID, arg.Status)
	var i QueueEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AppointmentID,
		&i.CustomerID,
		&i.QueueDate,
		&i.QueueNumber,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services SET
    name = COALESCE($1, name),
    duration_minutes = COALESCE($2, duration_minutes),
    price = COALESCE($3, price),
    is_active = COALESCE($4, is_active),
    updated_at = now()
WHERE id = $5 AND tenant_id = $6
RETURNING id, tenant_id, name, duration_minutes, price, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	Name            pgtype.Text    `json:"name"`
	DurationMinutes pgtype.Int4    `json:"duration_minutes"`
	Price           pgtype.Numeric `json:"price"`
	IsActive        pgtype.Bool    `json:"is_active"`
	ID              pgtype.UUID    `json:"id"`
	TenantID        pgtype.UUID    `json:"tenant_id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.DurationMinutes,
		arg.Price,
		arg.IsActive,
		arg.ID,
		arg.TenantID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DurationMinutes,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
