// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsByResult = `-- name: CountAuditLogsByResult :many
SELECT result, COUNT(*)::bigint AS count
FROM audit_logs
WHERE tenant_id IS NULL OR tenant_id = $1
GROUP BY result
`

type CountAuditLogsByResultRow struct {
	Result string `json:"result"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountAuditLogsByResult(ctx context.Context, tenantID pgtype.UUID) ([]CountAuditLogsByResultRow, error) {
	rows, err := q.db.Query(ctx, countAuditLogsByResult, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditLogsByResultRow{}
	for rows.Next() {
		var i CountAuditLogsByResultRow
		if err := rows.Scan(&i.Result, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (tenant_id, user_id, action, entity_type, entity_id, metadata, result)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, user_id, action, entity_type, entity_id, metadata, created_at, result
`

type InsertAuditLogParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Metadata   []byte      `json:"metadata"`
	Result     string      `json:"result"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.TenantID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
		arg.Result,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
		&i.Result,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, user_id, action, entity_type, entity_id, metadata, created_at, result FROM audit_logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
