// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLicense = `-- name: CreateLicense :one
INSERT INTO licenses (tenant_id, template_id, status, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, template_id, status, issued_at, expires_at, revoked_reason, created_at, updated_at
`

type CreateLicenseParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	TemplateID pgtype.UUID        `json:"template_id"`
	Status     string             `json:"status"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLicense(ctx context.Context, arg CreateLicenseParams) (License, error) {
	row := q.db.QueryRow(ctx, createLicense,
		arg.TenantID,
		arg.TemplateID,
		arg.Status,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i License
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateID,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTermsAcceptance = `-- name: CreateTermsAcceptance :one
INSERT INTO terms_acceptances (tenant_id, user_id, document_id, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, document_id, accepted_at, metadata
`

type CreateTermsAcceptanceParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	UserID     pgtype.UUID `json:"user_id"`
	DocumentID pgtype.UUID `json:"document_id"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateTermsAcceptance(ctx context.Context, arg CreateTermsAcceptanceParams) (TermsAcceptance, error) {
	row := q.db.QueryRow(ctx, createTermsAcceptance,
		arg.TenantID,
		arg.UserID,
		arg.DocumentID,
		arg.Metadata,
	)
	var i TermsAcceptance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DocumentID,
		&i.AcceptedAt,
		&i.Metadata,
	)
	return i, err
}

const getBusinessTypeCapabilities = `-- name: GetBusinessTypeCapabilities :many
SELECT capability_code, default_enabled, configurable FROM business_type_capabilities
WHERE business_type_code = $1
`

type GetBusinessTypeCapabilitiesRow struct {
	CapabilityCode string `json:"capability_code"`
	DefaultEnabled bool   `json:"default_enabled"`
	Configurable   bool   `json:"configurable"`
}

func (q *Queries) GetBusinessTypeCapabilities(ctx context.Context, businessTypeCode string) ([]GetBusinessTypeCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, getBusinessTypeCapabilities, businessTypeCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBusinessTypeCapabilitiesRow{}
	for rows.Next() {
		var i GetBusinessTypeCapabilitiesRow
		if err := rows.Scan(&i.CapabilityCode, &i.DefaultEnabled, &i.Configurable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessTypeCapabilitiesWithLabels = `-- name: GetBusinessTypeCapabilitiesWithLabels :many
SELECT btc.capability_code, c.label, btc.default_enabled, btc.configurable
FROM business_type_capabilities btc
JOIN capabilities c ON c.code = btc.capability_code
WHERE btc.business_type_code = $1
ORDER BY btc.capability_code
`

type GetBusinessTypeCapabilitiesWithLabelsRow struct {
	CapabilityCode string `json:"capability_code"`
	Label          string `json:"label"`
	DefaultEnabled bool   `json:"default_enabled"`
	Configurable   bool   `json:"configurable"`
}

// Same as GetBusinessTypeCapabilities, with the human label joined in — for
// the onboarding wizard, which has no reason to carry its own copy of the
// capability catalogue's labels.
func (q *Queries) GetBusinessTypeCapabilitiesWithLabels(ctx context.Context, businessTypeCode string) ([]GetBusinessTypeCapabilitiesWithLabelsRow, error) {
	rows, err := q.db.Query(ctx, getBusinessTypeCapabilitiesWithLabels, businessTypeCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBusinessTypeCapabilitiesWithLabelsRow{}
	for rows.Next() {
		var i GetBusinessTypeCapabilitiesWithLabelsRow
		if err := rows.Scan(
			&i.CapabilityCode,
			&i.Label,
			&i.DefaultEnabled,
			&i.Configurable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessTypeDefaults = `-- name: GetBusinessTypeDefaults :many
SELECT capability_code, seed FROM business_type_defaults
WHERE business_type_code = $1
`

type GetBusinessTypeDefaultsRow struct {
	CapabilityCode string `json:"capability_code"`
	Seed           []byte `json:"seed"`
}

func (q *Queries) GetBusinessTypeDefaults(ctx context.Context, businessTypeCode string) ([]GetBusinessTypeDefaultsRow, error) {
	rows, err := q.db.Query(ctx, getBusinessTypeDefaults, businessTypeCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBusinessTypeDefaultsRow{}
	for rows.Next() {
		var i GetBusinessTypeDefaultsRow
		if err := rows.Scan(&i.CapabilityCode, &i.Seed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestTermsDocument = `-- name: GetLatestTermsDocument :one
SELECT id, version, content_url, content_hash, published_at FROM terms_documents
ORDER BY published_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTermsDocument(ctx context.Context) (TermsDocument, error) {
	row := q.db.QueryRow(ctx, getLatestTermsDocument)
	var i TermsDocument
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ContentUrl,
		&i.ContentHash,
		&i.PublishedAt,
	)
	return i, err
}

const getLicenseByTenant = `-- name: GetLicenseByTenant :one
SELECT id, tenant_id, template_id, status, issued_at, expires_at, revoked_reason, created_at, updated_at FROM licenses WHERE tenant_id = $1
`

func (q *Queries) GetLicenseByTenant(ctx context.Context, tenantID pgtype.UUID) (License, error) {
	row := q.db.QueryRow(ctx, getLicenseByTenant, tenantID)
	var i License
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateID,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLicenseTemplateByPlan = `-- name: GetLicenseTemplateByPlan :one
SELECT id, plan_id, name, validity_days, grace_period_days, created_at FROM license_templates WHERE plan_id = $1
`

func (q *Queries) GetLicenseTemplateByPlan(ctx context.Context, planID pgtype.UUID) (LicenseTemplate, error) {
	row := q.db.QueryRow(ctx, getLicenseTemplateByPlan, planID)
	var i LicenseTemplate
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.ValidityDays,
		&i.GracePeriodDays,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantLicenseStatus = `-- name: GetTenantLicenseStatus :one
SELECT status FROM licenses WHERE tenant_id = $1
`

func (q *Queries) GetTenantLicenseStatus(ctx context.Context, tenantID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTenantLicenseStatus, tenantID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listEnabledCapabilities = `-- name: ListEnabledCapabilities :many

SELECT capability_code FROM tenant_capabilities
WHERE tenant_id = $1 AND enabled = TRUE
`

// Capability, license and terms queries. These back the tenant-isolation
// middleware (tenantctx) and the onboarding transaction (platform.CreateTenant)
// — see planing/business_saas_lld.md and business_saas_db_map.md.
func (q *Queries) ListEnabledCapabilities(ctx context.Context, tenantID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnabledCapabilities, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var capability_code string
		if err := rows.Scan(&capability_code); err != nil {
			return nil, err
		}
		items = append(items, capability_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantCapabilities = `-- name: ListTenantCapabilities :many
SELECT capability_code, enabled, source, updated_at FROM tenant_capabilities
WHERE tenant_id = $1
ORDER BY capability_code
`

type ListTenantCapabilitiesRow struct {
	CapabilityCode string             `json:"capability_code"`
	Enabled        bool               `json:"enabled"`
	Source         string             `json:"source"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTenantCapabilities(ctx context.Context, tenantID pgtype.UUID) ([]ListTenantCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listTenantCapabilities, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantCapabilitiesRow{}
	for rows.Next() {
		var i ListTenantCapabilitiesRow
		if err := rows.Scan(
			&i.CapabilityCode,
			&i.Enabled,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLicenseStatus = `-- name: SetLicenseStatus :one
UPDATE licenses
SET status = $2, revoked_reason = $3, updated_at = now()
WHERE tenant_id = $1
RETURNING id, tenant_id, template_id, status, issued_at, expires_at, revoked_reason, created_at, updated_at
`

type SetLicenseStatusParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Status        string      `json:"status"`
	RevokedReason string      `json:"revoked_reason"`
}

func (q *Queries) SetLicenseStatus(ctx context.Context, arg SetLicenseStatusParams) (License, error) {
	row := q.db.QueryRow(ctx, setLicenseStatus, arg.TenantID, arg.Status, arg.RevokedReason)
	var i License
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateID,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTenantCapability = `-- name: SetTenantCapability :one
UPDATE tenant_capabilities
SET enabled = $3, source = 'OVERRIDE', updated_at = now()
WHERE tenant_id = $1 AND capability_code = $2
RETURNING tenant_id, capability_code, enabled, source, updated_at
`

type SetTenantCapabilityParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	CapabilityCode string      `json:"capability_code"`
	Enabled        bool        `json:"enabled"`
}

// Caller must have already checked business_type_capabilities.configurable —
// this statement does not, since it has no way to know the tenant's business
// type without a join the caller already has cheaper access to.
func (q *Queries) SetTenantCapability(ctx context.Context, arg SetTenantCapabilityParams) (TenantCapability, error) {
	row := q.db.QueryRow(ctx, setTenantCapability, arg.TenantID, arg.CapabilityCode, arg.Enabled)
	var i TenantCapability
	err := row.Scan(
		&i.TenantID,
		&i.CapabilityCode,
		&i.Enabled,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantCapability = `-- name: UpsertTenantCapability :exec
INSERT INTO tenant_capabilities (tenant_id, capability_code, enabled, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, capability_code) DO UPDATE
    SET enabled = EXCLUDED.enabled, source = EXCLUDED.source, updated_at = now()
`

type UpsertTenantCapabilityParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	CapabilityCode string      `json:"capability_code"`
	Enabled        bool        `json:"enabled"`
	Source         string      `json:"source"`
}

func (q *Queries) UpsertTenantCapability(ctx context.Context, arg UpsertTenantCapabilityParams) error {
	_, err := q.db.Exec(ctx, upsertTenantCapability,
		arg.TenantID,
		arg.CapabilityCode,
		arg.Enabled,
		arg.Source,
	)
	return err
}
