// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: customer_otp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOtpCode = `-- name: ConsumeOtpCode :one
UPDATE customer_otp_codes
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
RETURNING id, tenant_id, phone, code_hash, expires_at, attempts, consumed_at, created_at
`

func (q *Queries) ConsumeOtpCode(ctx context.Context, id pgtype.UUID) (CustomerOtpCode, error) {
	row := q.db.QueryRow(ctx, consumeOtpCode, id)
	var i CustomerOtpCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOtpCode = `-- name: CreateOtpCode :one
INSERT INTO customer_otp_codes (tenant_id, phone, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, phone, code_hash, expires_at, attempts, consumed_at, created_at
`

type CreateOtpCodeParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Phone     string             `json:"phone"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOtpCode(ctx context.Context, arg CreateOtpCodeParams) (CustomerOtpCode, error) {
	row := q.db.QueryRow(ctx, createOtpCode,
		arg.TenantID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i CustomerOtpCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveOtpCode = `-- name: GetActiveOtpCode :one
SELECT id, tenant_id, phone, code_hash, expires_at, attempts, consumed_at, created_at FROM customer_otp_codes
WHERE tenant_id = $1
  AND phone = $2
  AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOtpCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Phone    string      `json:"phone"`
}

// Latest unconsumed code for a phone number. One live code at a time: sending
// a new one supersedes the old.
func (q *Queries) GetActiveOtpCode(ctx context.Context, arg GetActiveOtpCodeParams) (CustomerOtpCode, error) {
	row := q.db.QueryRow(ctx, getActiveOtpCode, arg.TenantID, arg.Phone)
	var i CustomerOtpCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOtpAttempts = `-- name: IncrementOtpAttempts :one
UPDATE customer_otp_codes
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, tenant_id, phone, code_hash, expires_at, attempts, consumed_at, created_at
`

func (q *Queries) IncrementOtpAttempts(ctx context.Context, id pgtype.UUID) (CustomerOtpCode, error) {
	row := q.db.QueryRow(ctx, incrementOtpAttempts, id)
	var i CustomerOtpCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateOtpCodes = `-- name: InvalidateOtpCodes :exec
UPDATE customer_otp_codes
SET consumed_at = now()
WHERE tenant_id = $1 AND phone = $2 AND consumed_at IS NULL
`

type InvalidateOtpCodesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Phone    string      `json:"phone"`
}

func (q *Queries) InvalidateOtpCodes(ctx context.Context, arg InvalidateOtpCodesParams) error {
	_, err := q.db.Exec(ctx, invalidateOtpCodes, arg.TenantID, arg.Phone)
	return err
}
