// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked FROM customers
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetCustomerByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.TenantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked FROM customers
WHERE tenant_id = $1 AND phone = $2
LIMIT 1
`

type GetCustomerByPhoneParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, arg.TenantID, arg.Phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}

const listCustomerOrders = `-- name: ListCustomerOrders :many
SELECT id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee FROM orders
WHERE tenant_id = $1 AND customer_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListCustomerOrdersParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	CustomerID pgtype.UUID `json:"customer_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListCustomerOrders(ctx context.Context, arg ListCustomerOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listCustomerOrders, arg.TenantID, arg.CustomerID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Status,
			&i.OrderType,
			&i.Subtotal,
			&i.Tax,
			&i.Discount,
			&i.Total,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.Notes,
			&i.EstimatedReadyAt,
			&i.AcceptedAt,
			&i.PreparingAt,
			&i.ReadyAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelReason,
			&i.Source,
			&i.ClientToken,
			&i.PackagingFee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerProfile = `-- name: UpdateCustomerProfile :one
UPDATE customers
SET
    name = COALESCE($1, name),
    updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked
`

type UpdateCustomerProfileParams struct {
	Name     pgtype.Text `json:"name"`
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerProfile, arg.Name, arg.ID, arg.TenantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}

const upsertCustomerByPhone = `-- name: UpsertCustomerByPhone :one
INSERT INTO customers (tenant_id, name, phone, last_login_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (tenant_id, phone) WHERE phone IS NOT NULL
DO UPDATE SET
    name = CASE WHEN customers.name = '' THEN EXCLUDED.name ELSE customers.name END,
    last_login_at = now()
RETURNING id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked
`

type UpsertCustomerByPhoneParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Phone    pgtype.Text `json:"phone"`
}

// Phone identity for storefront customers. The (tenant_id, phone) unique index
// already exists in the schema, so this upsert cannot create a duplicate.
func (q *Queries) UpsertCustomerByPhone(ctx context.Context, arg UpsertCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, upsertCustomerByPhone, arg.TenantID, arg.Name, arg.Phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}
