// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomersByTenant = `-- name: CountCustomersByTenant :one
SELECT COUNT(*)::bigint FROM customers WHERE tenant_id = $1
`

func (q *Queries) CountCustomersByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByTenant, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked FROM customers
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetCustomerByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.TenantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked FROM customers
WHERE tenant_id = $1 AND phone = $2
LIMIT 1
`

type GetCustomerByPhoneParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, arg.TenantID, arg.Phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}

const listCustomerOrders = `-- name: ListCustomerOrders :many
SELECT id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id FROM orders
WHERE tenant_id = $1 AND customer_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListCustomerOrdersParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	CustomerID pgtype.UUID `json:"customer_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListCustomerOrders(ctx context.Context, arg ListCustomerOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listCustomerOrders, arg.TenantID, arg.CustomerID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Status,
			&i.OrderType,
			&i.Subtotal,
			&i.Tax,
			&i.Discount,
			&i.Total,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.Notes,
			&i.EstimatedReadyAt,
			&i.AcceptedAt,
			&i.PreparingAt,
			&i.ReadyAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelReason,
			&i.Source,
			&i.ClientToken,
			&i.PackagingFee,
			&i.TableID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByTenant = `-- name: ListCustomersByTenant :many
SELECT
    c.id,
    c.name,
    c.phone,
    c.is_blocked,
    c.last_login_at,
    c.created_at,
    c.updated_at,
    (
        SELECT COUNT(*)::bigint
        FROM orders o
        WHERE o.tenant_id = c.tenant_id
          AND (
              o.customer_id = c.id
              OR (c.phone IS NOT NULL AND o.customer_phone = c.phone)
          )
    ) AS order_count,
    (
        SELECT COALESCE(SUM(o.total), 0)::float8
        FROM orders o
        WHERE o.tenant_id = c.tenant_id
          AND (
              o.customer_id = c.id
              OR (c.phone IS NOT NULL AND o.customer_phone = c.phone)
          )
    ) AS total_spend,
    (
        SELECT MAX(o.created_at)
        FROM orders o
        WHERE o.tenant_id = c.tenant_id
          AND (
              o.customer_id = c.id
              OR (c.phone IS NOT NULL AND o.customer_phone = c.phone)
          )
    ) AS last_order_at
FROM customers c
WHERE c.tenant_id = $1
ORDER BY COALESCE(
    (
        SELECT MAX(o.created_at)
        FROM orders o
        WHERE o.tenant_id = c.tenant_id
          AND (
              o.customer_id = c.id
              OR (c.phone IS NOT NULL AND o.customer_phone = c.phone)
          )
    ),
    c.created_at
) DESC
LIMIT $3
OFFSET $2
`

type ListCustomersByTenantParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListCustomersByTenantRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Phone       pgtype.Text        `json:"phone"`
	IsBlocked   bool               `json:"is_blocked"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OrderCount  int64              `json:"order_count"`
	TotalSpend  float64            `json:"total_spend"`
	LastOrderAt interface{}        `json:"last_order_at"`
}

// Shop CRM: signed-in / known customers with order stats (matched by id or phone).
func (q *Queries) ListCustomersByTenant(ctx context.Context, arg ListCustomersByTenantParams) ([]ListCustomersByTenantRow, error) {
	rows, err := q.db.Query(ctx, listCustomersByTenant, arg.TenantID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersByTenantRow{}
	for rows.Next() {
		var i ListCustomersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.IsBlocked,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderCount,
			&i.TotalSpend,
			&i.LastOrderAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestCustomersFromOrders = `-- name: ListGuestCustomersFromOrders :many
SELECT
    MAX(o.customer_name) AS name,
    o.customer_phone AS phone,
    COUNT(*)::bigint AS order_count,
    COALESCE(SUM(o.total), 0)::float8 AS total_spend,
    MAX(o.created_at) AS last_order_at,
    MIN(o.created_at) AS first_seen_at
FROM orders o
WHERE o.tenant_id = $1
  AND NULLIF(TRIM(o.customer_phone), '') IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM customers c
      WHERE c.tenant_id = o.tenant_id AND c.phone = o.customer_phone
  )
GROUP BY o.customer_phone
ORDER BY MAX(o.created_at) DESC
LIMIT $2
`

type ListGuestCustomersFromOrdersParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	LimitCount int32       `json:"limit_count"`
}

type ListGuestCustomersFromOrdersRow struct {
	Name        interface{} `json:"name"`
	Phone       string      `json:"phone"`
	OrderCount  int64       `json:"order_count"`
	TotalSpend  float64     `json:"total_spend"`
	LastOrderAt interface{} `json:"last_order_at"`
	FirstSeenAt interface{} `json:"first_seen_at"`
}

// Guests who placed orders but never got a customers row (no phone login).
func (q *Queries) ListGuestCustomersFromOrders(ctx context.Context, arg ListGuestCustomersFromOrdersParams) ([]ListGuestCustomersFromOrdersRow, error) {
	rows, err := q.db.Query(ctx, listGuestCustomersFromOrders, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuestCustomersFromOrdersRow{}
	for rows.Next() {
		var i ListGuestCustomersFromOrdersRow
		if err := rows.Scan(
			&i.Name,
			&i.Phone,
			&i.OrderCount,
			&i.TotalSpend,
			&i.LastOrderAt,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerBlocked = `-- name: SetCustomerBlocked :one
UPDATE customers
SET is_blocked = $1, updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked
`

type SetCustomerBlockedParams struct {
	IsBlocked bool        `json:"is_blocked"`
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) SetCustomerBlocked(ctx context.Context, arg SetCustomerBlockedParams) (Customer, error) {
	row := q.db.QueryRow(ctx, setCustomerBlocked, arg.IsBlocked, arg.ID, arg.TenantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}

const updateCustomerProfile = `-- name: UpdateCustomerProfile :one
UPDATE customers
SET
    name = COALESCE($1, name),
    updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked
`

type UpdateCustomerProfileParams struct {
	Name     pgtype.Text `json:"name"`
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerProfile, arg.Name, arg.ID, arg.TenantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}

const upsertCustomerByPhone = `-- name: UpsertCustomerByPhone :one
INSERT INTO customers (tenant_id, name, phone, last_login_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (tenant_id, phone) WHERE phone IS NOT NULL
DO UPDATE SET
    name = CASE WHEN customers.name = '' THEN EXCLUDED.name ELSE customers.name END,
    last_login_at = now()
RETURNING id, tenant_id, name, phone, created_at, updated_at, last_login_at, is_blocked
`

type UpsertCustomerByPhoneParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Phone    pgtype.Text `json:"phone"`
}

// Phone identity for storefront customers. The (tenant_id, phone) unique index
// already exists in the schema, so this upsert cannot create a duplicate.
func (q *Queries) UpsertCustomerByPhone(ctx context.Context, arg UpsertCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, upsertCustomerByPhone, arg.TenantID, arg.Name, arg.Phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.IsBlocked,
	)
	return i, err
}
