// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: hotel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInReservation = `-- name: CheckInReservation :one
UPDATE reservations
SET status = 'CHECKED_IN', room_id = $3, checked_in_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, room_type_id, room_id, check_in_date, check_out_date, guests, status, checked_in_at, checked_out_at, created_at, updated_at
`

type CheckInReservationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	RoomID   pgtype.UUID `json:"room_id"`
}

func (q *Queries) CheckInReservation(ctx context.Context, arg CheckInReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, checkInReservation, arg.ID, arg.TenantID, arg.RoomID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.RoomTypeID,
		&i.RoomID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.Guests,
		&i.Status,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkOutReservation = `-- name: CheckOutReservation :one
UPDATE reservations
SET status = 'CHECKED_OUT', checked_out_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, room_type_id, room_id, check_in_date, check_out_date, guests, status, checked_in_at, checked_out_at, created_at, updated_at
`

type CheckOutReservationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CheckOutReservation(ctx context.Context, arg CheckOutReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, checkOutReservation, arg.ID, arg.TenantID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.RoomTypeID,
		&i.RoomID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.Guests,
		&i.Status,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCharge = `-- name: CreateCharge :one
INSERT INTO charges (tenant_id, folio_id, description, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, folio_id, description, amount, created_at
`

type CreateChargeParams struct {
	TenantID    pgtype.UUID    `json:"tenant_id"`
	FolioID     pgtype.UUID    `json:"folio_id"`
	Description string         `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateCharge(ctx context.Context, arg CreateChargeParams) (Charge, error) {
	row := q.db.QueryRow(ctx, createCharge,
		arg.TenantID,
		arg.FolioID,
		arg.Description,
		arg.Amount,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FolioID,
		&i.Description,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const createFolio = `-- name: CreateFolio :one
INSERT INTO folios (tenant_id, reservation_id, status)
VALUES ($1, $2, 'OPEN')
RETURNING id, tenant_id, reservation_id, status, created_at
`

type CreateFolioParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	ReservationID pgtype.UUID `json:"reservation_id"`
}

func (q *Queries) CreateFolio(ctx context.Context, arg CreateFolioParams) (Folio, error) {
	row := q.db.QueryRow(ctx, createFolio, arg.TenantID, arg.ReservationID)
	var i Folio
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReservationID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createHousekeepingTask = `-- name: CreateHousekeepingTask :one
INSERT INTO housekeeping_tasks (tenant_id, room_id, task_type, assigned_to)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, room_id, task_type, status, assigned_to, created_at, completed_at
`

type CreateHousekeepingTaskParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	RoomID     pgtype.UUID `json:"room_id"`
	TaskType   string      `json:"task_type"`
	AssignedTo pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) CreateHousekeepingTask(ctx context.Context, arg CreateHousekeepingTaskParams) (HousekeepingTask, error) {
	row := q.db.QueryRow(ctx, createHousekeepingTask,
		arg.TenantID,
		arg.RoomID,
		arg.TaskType,
		arg.AssignedTo,
	)
	var i HousekeepingTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoomID,
		&i.TaskType,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (tenant_id, customer_id, room_type_id, check_in_date, check_out_date, guests, status)
VALUES ($1, $2, $3, $4, $5, $6, 'REQUESTED')
RETURNING id, tenant_id, customer_id, room_type_id, room_id, check_in_date, check_out_date, guests, status, checked_in_at, checked_out_at, created_at, updated_at
`

type CreateReservationParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	CustomerID   pgtype.UUID `json:"customer_id"`
	RoomTypeID   pgtype.UUID `json:"room_type_id"`
	CheckInDate  pgtype.Date `json:"check_in_date"`
	CheckOutDate pgtype.Date `json:"check_out_date"`
	Guests       int32       `json:"guests"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.TenantID,
		arg.CustomerID,
		arg.RoomTypeID,
		arg.CheckInDate,
		arg.CheckOutDate,
		arg.Guests,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.RoomTypeID,
		&i.RoomID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.Guests,
		&i.Status,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (tenant_id, room_type_id, number, status)
VALUES ($1, $2, $3, 'AVAILABLE')
RETURNING id, tenant_id, room_type_id, number, status, created_at
`

type CreateRoomParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	RoomTypeID pgtype.UUID `json:"room_type_id"`
	Number     string      `json:"number"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.TenantID, arg.RoomTypeID, arg.Number)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoomTypeID,
		&i.Number,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createRoomType = `-- name: CreateRoomType :one

INSERT INTO room_types (tenant_id, name, base_price, max_guests)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, base_price, max_guests, created_at
`

type CreateRoomTypeParams struct {
	TenantID  pgtype.UUID    `json:"tenant_id"`
	Name      string         `json:"name"`
	BasePrice pgtype.Numeric `json:"base_price"`
	MaxGuests int32          `json:"max_guests"`
}

// Hotel capability group: room types, rooms, reservations, folios/charges and
// housekeeping. Reservation and room status are two separate state machines
// (POC requirement) — never write both from one statement.
func (q *Queries) CreateRoomType(ctx context.Context, arg CreateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, createRoomType,
		arg.TenantID,
		arg.Name,
		arg.BasePrice,
		arg.MaxGuests,
	)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.BasePrice,
		&i.MaxGuests,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoomType = `-- name: DeleteRoomType :exec
DELETE FROM room_types WHERE id = $1 AND tenant_id = $2
`

type DeleteRoomTypeParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRoomType(ctx context.Context, arg DeleteRoomTypeParams) error {
	_, err := q.db.Exec(ctx, deleteRoomType, arg.ID, arg.TenantID)
	return err
}

const folioTotal = `-- name: FolioTotal :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total FROM charges WHERE folio_id = $1 AND tenant_id = $2
`

type FolioTotalParams struct {
	FolioID  pgtype.UUID `json:"folio_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) FolioTotal(ctx context.Context, arg FolioTotalParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, folioTotal, arg.FolioID, arg.TenantID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getFolioByReservation = `-- name: GetFolioByReservation :one
SELECT id, tenant_id, reservation_id, status, created_at FROM folios WHERE reservation_id = $1 AND tenant_id = $2 LIMIT 1
`

type GetFolioByReservationParams struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetFolioByReservation(ctx context.Context, arg GetFolioByReservationParams) (Folio, error) {
	row := q.db.QueryRow(ctx, getFolioByReservation, arg.ReservationID, arg.TenantID)
	var i Folio
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReservationID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, tenant_id, customer_id, room_type_id, room_id, check_in_date, check_out_date, guests, status, checked_in_at, checked_out_at, created_at, updated_at FROM reservations WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetReservationByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetReservationByID(ctx context.Context, arg GetReservationByIDParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, arg.ID, arg.TenantID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.RoomTypeID,
		&i.RoomID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.Guests,
		&i.Status,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, tenant_id, room_type_id, number, status, created_at FROM rooms WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetRoomByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRoomByID(ctx context.Context, arg GetRoomByIDParams) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, arg.ID, arg.TenantID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoomTypeID,
		&i.Number,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listChargesByFolio = `-- name: ListChargesByFolio :many
SELECT id, tenant_id, folio_id, description, amount, created_at FROM charges WHERE folio_id = $1 AND tenant_id = $2 ORDER BY created_at ASC
`

type ListChargesByFolioParams struct {
	FolioID  pgtype.UUID `json:"folio_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListChargesByFolio(ctx context.Context, arg ListChargesByFolioParams) ([]Charge, error) {
	rows, err := q.db.Query(ctx, listChargesByFolio, arg.FolioID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Charge{}
	for rows.Next() {
		var i Charge
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FolioID,
			&i.Description,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousekeepingTasksByTenant = `-- name: ListHousekeepingTasksByTenant :many
SELECT id, tenant_id, room_id, task_type, status, assigned_to, created_at, completed_at FROM housekeeping_tasks WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListHousekeepingTasksByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListHousekeepingTasksByTenant(ctx context.Context, arg ListHousekeepingTasksByTenantParams) ([]HousekeepingTask, error) {
	rows, err := q.db.Query(ctx, listHousekeepingTasksByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HousekeepingTask{}
	for rows.Next() {
		var i HousekeepingTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoomID,
			&i.TaskType,
			&i.Status,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenHousekeepingTasks = `-- name: ListOpenHousekeepingTasks :many
SELECT id, tenant_id, room_id, task_type, status, assigned_to, created_at, completed_at FROM housekeeping_tasks
WHERE tenant_id = $1 AND status != 'DONE'
ORDER BY created_at ASC
`

func (q *Queries) ListOpenHousekeepingTasks(ctx context.Context, tenantID pgtype.UUID) ([]HousekeepingTask, error) {
	rows, err := q.db.Query(ctx, listOpenHousekeepingTasks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HousekeepingTask{}
	for rows.Next() {
		var i HousekeepingTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoomID,
			&i.TaskType,
			&i.Status,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByTenant = `-- name: ListReservationsByTenant :many
SELECT id, tenant_id, customer_id, room_type_id, room_id, check_in_date, check_out_date, guests, status, checked_in_at, checked_out_at, created_at, updated_at FROM reservations WHERE tenant_id = $1 ORDER BY check_in_date DESC LIMIT $2
`

type ListReservationsByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListReservationsByTenant(ctx context.Context, arg ListReservationsByTenantParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.RoomTypeID,
			&i.RoomID,
			&i.CheckInDate,
			&i.CheckOutDate,
			&i.Guests,
			&i.Status,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomTypesByTenant = `-- name: ListRoomTypesByTenant :many
SELECT id, tenant_id, name, base_price, max_guests, created_at FROM room_types WHERE tenant_id = $1 ORDER BY name ASC
`

func (q *Queries) ListRoomTypesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]RoomType, error) {
	rows, err := q.db.Query(ctx, listRoomTypesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomType{}
	for rows.Next() {
		var i RoomType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.BasePrice,
			&i.MaxGuests,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByTenant = `-- name: ListRoomsByTenant :many
SELECT id, tenant_id, room_type_id, number, status, created_at FROM rooms WHERE tenant_id = $1 ORDER BY number ASC
`

func (q *Queries) ListRoomsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoomTypeID,
			&i.Number,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFolioStatus = `-- name: SetFolioStatus :one
UPDATE folios SET status = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, reservation_id, status, created_at
`

type SetFolioStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) SetFolioStatus(ctx context.Context, arg SetFolioStatusParams) (Folio, error) {
	row := q.db.QueryRow(ctx, setFolioStatus, arg.ID, arg.TenantID, arg.Status)
	var i Folio
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReservationID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateHousekeepingTaskStatus = `-- name: UpdateHousekeepingTaskStatus :one
UPDATE housekeeping_tasks
SET status = $3, completed_at = CASE WHEN $3 = 'DONE' THEN now() ELSE completed_at END
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, room_id, task_type, status, assigned_to, created_at, completed_at
`

type UpdateHousekeepingTaskStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateHousekeepingTaskStatus(ctx context.Context, arg UpdateHousekeepingTaskStatusParams) (HousekeepingTask, error) {
	row := q.db.QueryRow(ctx, updateHousekeepingTaskStatus, arg.ID, arg.TenantID, arg.Status)
	var i HousekeepingTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoomID,
		&i.TaskType,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE reservations SET status = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, room_type_id, room_id, check_in_date, check_out_date, guests, status, checked_in_at, checked_out_at, created_at, updated_at
`

type UpdateReservationStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus, arg.ID, arg.TenantID, arg.Status)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.RoomTypeID,
		&i.RoomID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.Guests,
		&i.Status,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoomStatus = `-- name: UpdateRoomStatus :one
UPDATE rooms SET status = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, room_type_id, number, status, created_at
`

type UpdateRoomStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomStatus, arg.ID, arg.TenantID, arg.Status)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoomTypeID,
		&i.Number,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoomType = `-- name: UpdateRoomType :one
UPDATE room_types SET
    name = COALESCE($1, name),
    base_price = COALESCE($2, base_price),
    max_guests = COALESCE($3, max_guests)
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, name, base_price, max_guests, created_at
`

type UpdateRoomTypeParams struct {
	Name      pgtype.Text    `json:"name"`
	BasePrice pgtype.Numeric `json:"base_price"`
	MaxGuests pgtype.Int4    `json:"max_guests"`
	ID        pgtype.UUID    `json:"id"`
	TenantID  pgtype.UUID    `json:"tenant_id"`
}

func (q *Queries) UpdateRoomType(ctx context.Context, arg UpdateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, updateRoomType,
		arg.Name,
		arg.BasePrice,
		arg.MaxGuests,
		arg.ID,
		arg.TenantID,
	)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.BasePrice,
		&i.MaxGuests,
		&i.CreatedAt,
	)
	return i, err
}
