// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: menu.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductsInCategory = `-- name: CountProductsInCategory :one
SELECT COUNT(*)::bigint AS count
FROM products
WHERE tenant_id = $1 AND category_id = $2
`

type CountProductsInCategoryParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CountProductsInCategory(ctx context.Context, arg CountProductsInCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsInCategory, arg.TenantID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (tenant_id, name, description, sort_order, is_active, image_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, description, sort_order, is_active, created_at, updated_at, image_url
`

type CreateCategoryParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	IsActive    bool        `json:"is_active"`
	ImageUrl    pgtype.Text `json:"image_url"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.IsActive,
		arg.ImageUrl,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    tenant_id, category_id, name, description, price, image_url, sort_order, is_available,
    is_vegetarian, is_featured, is_popular, allow_special_instructions, addons
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, tenant_id, category_id, name, description, price, image_url, sort_order, is_available, created_at, updated_at, is_vegetarian, is_featured, is_popular, allow_special_instructions, addons
`

type CreateProductParams struct {
	TenantID                 pgtype.UUID    `json:"tenant_id"`
	CategoryID               pgtype.UUID    `json:"category_id"`
	Name                     string         `json:"name"`
	Description              string         `json:"description"`
	Price                    pgtype.Numeric `json:"price"`
	ImageUrl                 pgtype.Text    `json:"image_url"`
	SortOrder                int32          `json:"sort_order"`
	IsAvailable              bool           `json:"is_available"`
	IsVegetarian             bool           `json:"is_vegetarian"`
	IsFeatured               bool           `json:"is_featured"`
	IsPopular                bool           `json:"is_popular"`
	AllowSpecialInstructions bool           `json:"allow_special_instructions"`
	Addons                   []byte         `json:"addons"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImageUrl,
		arg.SortOrder,
		arg.IsAvailable,
		arg.IsVegetarian,
		arg.IsFeatured,
		arg.IsPopular,
		arg.AllowSpecialInstructions,
		arg.Addons,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVegetarian,
		&i.IsFeatured,
		&i.IsPopular,
		&i.AllowSpecialInstructions,
		&i.Addons,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1 AND tenant_id = $2
`

type DeleteCategoryParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.TenantID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1 AND tenant_id = $2
`

type DeleteProductParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.TenantID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, tenant_id, name, description, sort_order, is_active, created_at, updated_at, image_url FROM categories
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetCategoryByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.ID, arg.TenantID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, tenant_id, category_id, name, description, price, image_url, sort_order, is_available, created_at, updated_at, is_vegetarian, is_featured, is_popular, allow_special_instructions, addons FROM products
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetProductByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.TenantID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVegetarian,
		&i.IsFeatured,
		&i.IsPopular,
		&i.AllowSpecialInstructions,
		&i.Addons,
	)
	return i, err
}

const listActiveMenuCategories = `-- name: ListActiveMenuCategories :many
SELECT id, tenant_id, name, description, sort_order, is_active, created_at, updated_at, image_url FROM categories
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListActiveMenuCategories(ctx context.Context, tenantID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listActiveMenuCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableProductsByTenant = `-- name: ListAvailableProductsByTenant :many
SELECT id, tenant_id, category_id, name, description, price, image_url, sort_order, is_available, created_at, updated_at, is_vegetarian, is_featured, is_popular, allow_special_instructions, addons FROM products
WHERE tenant_id = $1 AND is_available = TRUE
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListAvailableProductsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listAvailableProductsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsVegetarian,
			&i.IsFeatured,
			&i.IsPopular,
			&i.AllowSpecialInstructions,
			&i.Addons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByTenant = `-- name: ListCategoriesByTenant :many
SELECT id, tenant_id, name, description, sort_order, is_active, created_at, updated_at, image_url FROM categories
WHERE tenant_id = $1
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListCategoriesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedProducts = `-- name: ListFeaturedProducts :many
SELECT id, tenant_id, category_id, name, description, price, image_url, sort_order, is_available, created_at, updated_at, is_vegetarian, is_featured, is_popular, allow_special_instructions, addons FROM products
WHERE tenant_id = $1
  AND is_available = TRUE
  AND is_featured = TRUE
ORDER BY sort_order ASC, name ASC
LIMIT $2
`

type ListFeaturedProductsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	LimitCount int32       `json:"limit_count"`
}

// Home page merchandising queries. Both are scoped to the tenant, so a
// storefront can only ever see its own products.
func (q *Queries) ListFeaturedProducts(ctx context.Context, arg ListFeaturedProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listFeaturedProducts, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsVegetarian,
			&i.IsFeatured,
			&i.IsPopular,
			&i.AllowSpecialInstructions,
			&i.Addons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularProducts = `-- name: ListPopularProducts :many
SELECT id, tenant_id, category_id, name, description, price, image_url, sort_order, is_available, created_at, updated_at, is_vegetarian, is_featured, is_popular, allow_special_instructions, addons FROM products
WHERE tenant_id = $1
  AND is_available = TRUE
  AND is_popular = TRUE
ORDER BY sort_order ASC, name ASC
LIMIT $2
`

type ListPopularProductsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListPopularProducts(ctx context.Context, arg ListPopularProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listPopularProducts, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsVegetarian,
			&i.IsFeatured,
			&i.IsPopular,
			&i.AllowSpecialInstructions,
			&i.Addons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByTenant = `-- name: ListProductsByTenant :many
SELECT id, tenant_id, category_id, name, description, price, image_url, sort_order, is_available, created_at, updated_at, is_vegetarian, is_featured, is_popular, allow_special_instructions, addons FROM products
WHERE tenant_id = $1
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListProductsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsVegetarian,
			&i.IsFeatured,
			&i.IsPopular,
			&i.AllowSpecialInstructions,
			&i.Addons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveProductsToCategory = `-- name: MoveProductsToCategory :exec
UPDATE products
SET category_id = $3, updated_at = now()
WHERE tenant_id = $1 AND category_id = $2
`

type MoveProductsToCategoryParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	CategoryID   pgtype.UUID `json:"category_id"`
	CategoryID_2 pgtype.UUID `json:"category_id_2"`
}

func (q *Queries) MoveProductsToCategory(ctx context.Context, arg MoveProductsToCategoryParams) error {
	_, err := q.db.Exec(ctx, moveProductsToCategory, arg.TenantID, arg.CategoryID, arg.CategoryID_2)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    sort_order = COALESCE($3, sort_order),
    is_active = COALESCE($4, is_active),
    image_url = COALESCE($5, image_url),
    updated_at = now()
WHERE id = $6 AND tenant_id = $7
RETURNING id, tenant_id, name, description, sort_order, is_active, created_at, updated_at, image_url
`

type UpdateCategoryParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   pgtype.Int4 `json:"sort_order"`
	IsActive    pgtype.Bool `json:"is_active"`
	ImageUrl    pgtype.Text `json:"image_url"`
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.IsActive,
		arg.ImageUrl,
		arg.ID,
		arg.TenantID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const updateCategorySortOrder = `-- name: UpdateCategorySortOrder :exec
UPDATE categories
SET sort_order = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateCategorySortOrderParams struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error {
	_, err := q.db.Exec(ctx, updateCategorySortOrder, arg.ID, arg.TenantID, arg.SortOrder)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    category_id = COALESCE($1, category_id),
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    price = COALESCE($4, price),
    image_url = COALESCE($5, image_url),
    sort_order = COALESCE($6, sort_order),
    is_available = COALESCE($7, is_available),
    is_vegetarian = COALESCE($8, is_vegetarian),
    is_featured = COALESCE($9, is_featured),
    is_popular = COALESCE($10, is_popular),
    allow_special_instructions = COALESCE($11, allow_special_instructions),
    addons = COALESCE($12::jsonb, addons),
    updated_at = now()
WHERE id = $13 AND tenant_id = $14
RETURNING id, tenant_id, category_id, name, description, price, image_url, sort_order, is_available, created_at, updated_at, is_vegetarian, is_featured, is_popular, allow_special_instructions, addons
`

type UpdateProductParams struct {
	CategoryID               pgtype.UUID    `json:"category_id"`
	Name                     pgtype.Text    `json:"name"`
	Description              pgtype.Text    `json:"description"`
	Price                    pgtype.Numeric `json:"price"`
	ImageUrl                 pgtype.Text    `json:"image_url"`
	SortOrder                pgtype.Int4    `json:"sort_order"`
	IsAvailable              pgtype.Bool    `json:"is_available"`
	IsVegetarian             pgtype.Bool    `json:"is_vegetarian"`
	IsFeatured               pgtype.Bool    `json:"is_featured"`
	IsPopular                pgtype.Bool    `json:"is_popular"`
	AllowSpecialInstructions pgtype.Bool    `json:"allow_special_instructions"`
	Addons                   []byte         `json:"addons"`
	ID                       pgtype.UUID    `json:"id"`
	TenantID                 pgtype.UUID    `json:"tenant_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImageUrl,
		arg.SortOrder,
		arg.IsAvailable,
		arg.IsVegetarian,
		arg.IsFeatured,
		arg.IsPopular,
		arg.AllowSpecialInstructions,
		arg.Addons,
		arg.ID,
		arg.TenantID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.SortOrder,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVegetarian,
		&i.IsFeatured,
		&i.IsPopular,
		&i.AllowSpecialInstructions,
		&i.Addons,
	)
	return i, err
}

const updateProductSortOrder = `-- name: UpdateProductSortOrder :exec
UPDATE products
SET sort_order = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateProductSortOrderParams struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateProductSortOrder(ctx context.Context, arg UpdateProductSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateProductSortOrder, arg.ID, arg.TenantID, arg.SortOrder)
	return err
}
