// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu_products_by_ids.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductsByIDs = `-- name: GetProductsByIDs :many
SELECT id, tenant_id, category_id, name, description, price, image_url, sort_order, is_available, created_at, updated_at, is_vegetarian, is_featured, is_popular, allow_special_instructions, addons FROM products
WHERE tenant_id = $1
  AND id = ANY($2::uuid[])
  AND is_available = TRUE
`

type GetProductsByIDsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	Ids      []pgtype.UUID `json:"ids"`
}

// Availability and price are both re-read here at order time. The client's
// figures are never trusted and `is_available = TRUE` is part of the filter, so
// a product taken off sale cannot sneak in through a stale cart.
func (q *Queries) GetProductsByIDs(ctx context.Context, arg GetProductsByIDsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.SortOrder,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsVegetarian,
			&i.IsFeatured,
			&i.IsPopular,
			&i.AllowSpecialInstructions,
			&i.Addons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
