// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: mfa.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserMfaMethods = `-- name: CountUserMfaMethods :one
SELECT count(*) FROM user_mfa_methods WHERE user_id = $1 AND enabled
`

func (q *Queries) CountUserMfaMethods(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMfaMethods, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO mfa_recovery_codes (user_id, code_hash)
VALUES ($1, $2)
`

type CreateRecoveryCodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash string      `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const deleteAllUserMfaMethods = `-- name: DeleteAllUserMfaMethods :exec
DELETE FROM user_mfa_methods WHERE user_id = $1
`

func (q *Queries) DeleteAllUserMfaMethods(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserMfaMethods, userID)
	return err
}

const deleteRecoveryCodesForUser = `-- name: DeleteRecoveryCodesForUser :exec
DELETE FROM mfa_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodesForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesForUser, userID)
	return err
}

const deleteUserMfaMethod = `-- name: DeleteUserMfaMethod :exec
DELETE FROM user_mfa_methods WHERE user_id = $1 AND method = $2
`

type DeleteUserMfaMethodParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Method string      `json:"method"`
}

func (q *Queries) DeleteUserMfaMethod(ctx context.Context, arg DeleteUserMfaMethodParams) error {
	_, err := q.db.Exec(ctx, deleteUserMfaMethod, arg.UserID, arg.Method)
	return err
}

const getUserMfaMethod = `-- name: GetUserMfaMethod :one
SELECT id, user_id, method, secret_enc, enabled, last_used_at, created_at FROM user_mfa_methods WHERE user_id = $1 AND method = $2 AND enabled
`

type GetUserMfaMethodParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Method string      `json:"method"`
}

func (q *Queries) GetUserMfaMethod(ctx context.Context, arg GetUserMfaMethodParams) (UserMfaMethod, error) {
	row := q.db.QueryRow(ctx, getUserMfaMethod, arg.UserID, arg.Method)
	var i UserMfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.SecretEnc,
		&i.Enabled,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, user_id, code_hash, used_at, created_at FROM mfa_recovery_codes
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, userID pgtype.UUID) ([]MfaRecoveryCode, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfaRecoveryCode{}
	for rows.Next() {
		var i MfaRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMfaMethods = `-- name: ListUserMfaMethods :many
SELECT id, user_id, method, secret_enc, enabled, last_used_at, created_at FROM user_mfa_methods WHERE user_id = $1 AND enabled ORDER BY created_at
`

func (q *Queries) ListUserMfaMethods(ctx context.Context, userID pgtype.UUID) ([]UserMfaMethod, error) {
	rows, err := q.db.Query(ctx, listUserMfaMethods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserMfaMethod{}
	for rows.Next() {
		var i UserMfaMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Method,
			&i.SecretEnc,
			&i.Enabled,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE mfa_recovery_codes
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRecoveryCodeUsed, id)
	return err
}

const syncUserMfaEnabledCache = `-- name: SyncUserMfaEnabledCache :exec
UPDATE users
SET mfa_enabled = EXISTS (SELECT 1 FROM user_mfa_methods WHERE user_id = $1 AND enabled)
WHERE id = $1
`

// Cosmetic status flag only (HandleMFAStatus display) — login/refresh logic
// must never read this as authority, see user_mfa_methods queries below.
func (q *Queries) SyncUserMfaEnabledCache(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, syncUserMfaEnabledCache, userID)
	return err
}

const touchUserMfaMethod = `-- name: TouchUserMfaMethod :exec
UPDATE user_mfa_methods SET last_used_at = now() WHERE user_id = $1 AND method = $2
`

type TouchUserMfaMethodParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Method string      `json:"method"`
}

func (q *Queries) TouchUserMfaMethod(ctx context.Context, arg TouchUserMfaMethodParams) error {
	_, err := q.db.Exec(ctx, touchUserMfaMethod, arg.UserID, arg.Method)
	return err
}

const upsertUserMfaMethod = `-- name: UpsertUserMfaMethod :one
INSERT INTO user_mfa_methods (user_id, method, secret_enc, enabled)
VALUES ($1, $2, $3, TRUE)
ON CONFLICT (user_id, method) DO UPDATE SET secret_enc = EXCLUDED.secret_enc, enabled = TRUE
RETURNING id, user_id, method, secret_enc, enabled, last_used_at, created_at
`

type UpsertUserMfaMethodParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Method    string      `json:"method"`
	SecretEnc pgtype.Text `json:"secret_enc"`
}

func (q *Queries) UpsertUserMfaMethod(ctx context.Context, arg UpsertUserMfaMethodParams) (UserMfaMethod, error) {
	row := q.db.QueryRow(ctx, upsertUserMfaMethod, arg.UserID, arg.Method, arg.SecretEnc)
	var i UserMfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.SecretEnc,
		&i.Enabled,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}
