// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: mfa_email_otp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeMfaEmailOtpCode = `-- name: ConsumeMfaEmailOtpCode :one
UPDATE mfa_email_otp_codes
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
RETURNING id, user_id, code_hash, expires_at, attempts, max_attempts, used_at, created_at
`

func (q *Queries) ConsumeMfaEmailOtpCode(ctx context.Context, id pgtype.UUID) (MfaEmailOtpCode, error) {
	row := q.db.QueryRow(ctx, consumeMfaEmailOtpCode, id)
	var i MfaEmailOtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMfaEmailOtpCode = `-- name: CreateMfaEmailOtpCode :one
INSERT INTO mfa_email_otp_codes (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code_hash, expires_at, attempts, max_attempts, used_at, created_at
`

type CreateMfaEmailOtpCodeParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMfaEmailOtpCode(ctx context.Context, arg CreateMfaEmailOtpCodeParams) (MfaEmailOtpCode, error) {
	row := q.db.QueryRow(ctx, createMfaEmailOtpCode, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	var i MfaEmailOtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveMfaEmailOtpCode = `-- name: GetActiveMfaEmailOtpCode :one
SELECT id, user_id, code_hash, expires_at, attempts, max_attempts, used_at, created_at FROM mfa_email_otp_codes
WHERE user_id = $1 AND used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

// Latest unconsumed code for a user. One live code at a time: sending a new
// one supersedes the old.
func (q *Queries) GetActiveMfaEmailOtpCode(ctx context.Context, userID pgtype.UUID) (MfaEmailOtpCode, error) {
	row := q.db.QueryRow(ctx, getActiveMfaEmailOtpCode, userID)
	var i MfaEmailOtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementMfaEmailOtpAttempts = `-- name: IncrementMfaEmailOtpAttempts :one
UPDATE mfa_email_otp_codes
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, user_id, code_hash, expires_at, attempts, max_attempts, used_at, created_at
`

func (q *Queries) IncrementMfaEmailOtpAttempts(ctx context.Context, id pgtype.UUID) (MfaEmailOtpCode, error) {
	row := q.db.QueryRow(ctx, incrementMfaEmailOtpAttempts, id)
	var i MfaEmailOtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateMfaEmailOtpCodes = `-- name: InvalidateMfaEmailOtpCodes :exec
UPDATE mfa_email_otp_codes
SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateMfaEmailOtpCodes(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateMfaEmailOtpCodes, userID)
	return err
}
