// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: mfa_policy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantMfaPolicy = `-- name: GetTenantMfaPolicy :one
SELECT tenant_id, mode, allowed_methods, enforce_scope, enforce_roles, grace_period_days, updated_at FROM tenant_mfa_policies WHERE tenant_id = $1
`

func (q *Queries) GetTenantMfaPolicy(ctx context.Context, tenantID pgtype.UUID) (TenantMfaPolicy, error) {
	row := q.db.QueryRow(ctx, getTenantMfaPolicy, tenantID)
	var i TenantMfaPolicy
	err := row.Scan(
		&i.TenantID,
		&i.Mode,
		&i.AllowedMethods,
		&i.EnforceScope,
		&i.EnforceRoles,
		&i.GracePeriodDays,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantMfaPolicy = `-- name: UpsertTenantMfaPolicy :one
INSERT INTO tenant_mfa_policies (tenant_id, mode, allowed_methods, enforce_scope, enforce_roles, grace_period_days)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id) DO UPDATE SET
    mode = EXCLUDED.mode,
    allowed_methods = EXCLUDED.allowed_methods,
    enforce_scope = EXCLUDED.enforce_scope,
    enforce_roles = EXCLUDED.enforce_roles,
    grace_period_days = EXCLUDED.grace_period_days,
    updated_at = now()
RETURNING tenant_id, mode, allowed_methods, enforce_scope, enforce_roles, grace_period_days, updated_at
`

type UpsertTenantMfaPolicyParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	Mode            string      `json:"mode"`
	AllowedMethods  []string    `json:"allowed_methods"`
	EnforceScope    string      `json:"enforce_scope"`
	EnforceRoles    []string    `json:"enforce_roles"`
	GracePeriodDays int32       `json:"grace_period_days"`
}

func (q *Queries) UpsertTenantMfaPolicy(ctx context.Context, arg UpsertTenantMfaPolicyParams) (TenantMfaPolicy, error) {
	row := q.db.QueryRow(ctx, upsertTenantMfaPolicy,
		arg.TenantID,
		arg.Mode,
		arg.AllowedMethods,
		arg.EnforceScope,
		arg.EnforceRoles,
		arg.GracePeriodDays,
	)
	var i TenantMfaPolicy
	err := row.Scan(
		&i.TenantID,
		&i.Mode,
		&i.AllowedMethods,
		&i.EnforceScope,
		&i.EnforceRoles,
		&i.GracePeriodDays,
		&i.UpdatedAt,
	)
	return i, err
}
