// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	ServiceID   pgtype.UUID        `json:"service_id"`
	StaffID     pgtype.UUID        `json:"staff_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Result     string             `json:"result"`
}

type BusinessTypeCapability struct {
	BusinessTypeCode string `json:"business_type_code"`
	CapabilityCode   string `json:"capability_code"`
	DefaultEnabled   bool   `json:"default_enabled"`
	Configurable     bool   `json:"configurable"`
}

type BusinessTypeDefault struct {
	BusinessTypeCode string `json:"business_type_code"`
	CapabilityCode   string `json:"capability_code"`
	Seed             []byte `json:"seed"`
}

type Capability struct {
	Code      string             `json:"code"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ImageUrl    pgtype.Text        `json:"image_url"`
}

type Charge struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	FolioID     pgtype.UUID        `json:"folio_id"`
	Description string             `json:"description"`
	Amount      pgtype.Numeric     `json:"amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Phone       pgtype.Text        `json:"phone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	IsBlocked   bool               `json:"is_blocked"`
}

type CustomerOtpCode struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Phone      string             `json:"phone"`
	CodeHash   string             `json:"code_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Folio struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ReservationID pgtype.UUID        `json:"reservation_id"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HousekeepingTask struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	TaskType    string             `json:"task_type"`
	Status      string             `json:"status"`
	AssignedTo  pgtype.UUID        `json:"assigned_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type License struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	TemplateID    pgtype.UUID        `json:"template_id"`
	Status        string             `json:"status"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedReason string             `json:"revoked_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type LicenseTemplate struct {
	ID              pgtype.UUID        `json:"id"`
	PlanID          pgtype.UUID        `json:"plan_id"`
	Name            string             `json:"name"`
	ValidityDays    pgtype.Int4        `json:"validity_days"`
	GracePeriodDays int32              `json:"grace_period_days"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	OrderNumber      int32              `json:"order_number"`
	Status           string             `json:"status"`
	OrderType        string             `json:"order_type"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	Tax              pgtype.Numeric     `json:"tax"`
	Discount         pgtype.Numeric     `json:"discount"`
	Total            pgtype.Numeric     `json:"total"`
	CustomerName     string             `json:"customer_name"`
	CustomerPhone    string             `json:"customer_phone"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomerEmail    string             `json:"customer_email"`
	Notes            string             `json:"notes"`
	EstimatedReadyAt pgtype.Timestamptz `json:"estimated_ready_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	PreparingAt      pgtype.Timestamptz `json:"preparing_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CancelledAt      pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason     string             `json:"cancel_reason"`
	Source           string             `json:"source"`
	ClientToken      string             `json:"client_token"`
	PackagingFee     pgtype.Numeric     `json:"packaging_fee"`
	TableID          pgtype.UUID        `json:"table_id"`
}

type OrderCounter struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	LastNumber int64       `json:"last_number"`
}

type OrderItem struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	OrderID             pgtype.UUID        `json:"order_id"`
	ProductID           pgtype.UUID        `json:"product_id"`
	ProductNameSnapshot string             `json:"product_name_snapshot"`
	UnitPrice           pgtype.Numeric     `json:"unit_price"`
	Quantity            int32              `json:"quantity"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Addons              []byte             `json:"addons"`
	Notes               string             `json:"notes"`
}

type OrderStatusHistory struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	OrderID    pgtype.UUID        `json:"order_id"`
	FromStatus string             `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Actor      string             `json:"actor"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	Provider          string             `json:"provider"`
	ProviderReference string             `json:"provider_reference"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FailureReason     string             `json:"failure_reason"`
	AttemptCount      int32              `json:"attempt_count"`
	PayableType       string             `json:"payable_type"`
	PayableID         pgtype.UUID        `json:"payable_id"`
	Purpose           string             `json:"purpose"`
}

type Plan struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	MaxStaff    int32              `json:"max_staff"`
	MaxProducts int32              `json:"max_products"`
	Features    []byte             `json:"features"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PlatformConfiguration struct {
	ID           pgtype.UUID        `json:"id"`
	ServiceType  string             `json:"service_type"`
	Provider     string             `json:"provider"`
	Config       []byte             `json:"config"`
	SecretConfig []byte             `json:"secret_config"`
	Status       string             `json:"status"`
	Enabled      bool               `json:"enabled"`
	AllowTenants bool               `json:"allow_tenants"`
	LastError    string             `json:"last_error"`
	LastTestedAt pgtype.Timestamptz `json:"last_tested_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PlatformSetting struct {
	ID        int16              `json:"id"`
	Config    []byte             `json:"config"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	CategoryID               pgtype.UUID        `json:"category_id"`
	Name                     string             `json:"name"`
	Description              string             `json:"description"`
	Price                    pgtype.Numeric     `json:"price"`
	ImageUrl                 pgtype.Text        `json:"image_url"`
	SortOrder                int32              `json:"sort_order"`
	IsAvailable              bool               `json:"is_available"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	IsVegetarian             bool               `json:"is_vegetarian"`
	IsFeatured               bool               `json:"is_featured"`
	IsPopular                bool               `json:"is_popular"`
	AllowSpecialInstructions bool               `json:"allow_special_instructions"`
	Addons                   []byte             `json:"addons"`
}

type QueueEntry struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	AppointmentID pgtype.UUID        `json:"appointment_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	QueueDate     pgtype.Date        `json:"queue_date"`
	QueueNumber   int32              `json:"queue_number"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reservation struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	RoomTypeID   pgtype.UUID        `json:"room_type_id"`
	RoomID       pgtype.UUID        `json:"room_id"`
	CheckInDate  pgtype.Date        `json:"check_in_date"`
	CheckOutDate pgtype.Date        `json:"check_out_date"`
	Guests       int32              `json:"guests"`
	Status       string             `json:"status"`
	CheckedInAt  pgtype.Timestamptz `json:"checked_in_at"`
	CheckedOutAt pgtype.Timestamptz `json:"checked_out_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	RoomTypeID pgtype.UUID        `json:"room_type_id"`
	Number     string             `json:"number"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RoomType struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	BasePrice pgtype.Numeric     `json:"base_price"`
	MaxGuests int32              `json:"max_guests"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	DurationMinutes int32              `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type StaffAvailability struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	StaffID   pgtype.UUID `json:"staff_id"`
	Weekday   int32       `json:"weekday"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

type Subscription struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	Status    string             `json:"status"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Table struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Label     string             `json:"label"`
	Seats     int32              `json:"seats"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	BusinessType     string             `json:"business_type"`
	OwnerName        string             `json:"owner_name"`
	Phone            string             `json:"phone"`
	Email            string             `json:"email"`
	Address          string             `json:"address"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	IsPublished      bool               `json:"is_published"`
	PlanID           pgtype.UUID        `json:"plan_id"`
	SetupStatus      string             `json:"setup_status"`
	ThemePresetID    string             `json:"theme_preset_id"`
	ThemeColorMode   string             `json:"theme_color_mode"`
	ThemeOverrides   []byte             `json:"theme_overrides"`
	LogoUrl          string             `json:"logo_url"`
	FaviconUrl       string             `json:"favicon_url"`
	ShortDescription string             `json:"short_description"`
	Currency         string             `json:"currency"`
	Timezone         string             `json:"timezone"`
	Language         string             `json:"language"`
	StoreStatus      string             `json:"store_status"`
	StatusMessage    string             `json:"status_message"`
}

type TenantCapability struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CapabilityCode string             `json:"capability_code"`
	Enabled        bool               `json:"enabled"`
	Source         string             `json:"source"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TenantConfiguration struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ServiceType  string             `json:"service_type"`
	Provider     string             `json:"provider"`
	Config       []byte             `json:"config"`
	SecretConfig []byte             `json:"secret_config"`
	Status       string             `json:"status"`
	Enabled      bool               `json:"enabled"`
	LastError    string             `json:"last_error"`
	LastTestedAt pgtype.Timestamptz `json:"last_tested_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TenantOnboardingDraft struct {
	ID                  pgtype.UUID        `json:"id"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	Step                string             `json:"step"`
	Payload             []byte             `json:"payload"`
	Status              string             `json:"status"`
	ProvisionedTenantID pgtype.UUID        `json:"provisioned_tenant_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type TenantServiceAccess struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ServiceType   string             `json:"service_type"`
	AllowPlatform bool               `json:"allow_platform"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TenantServicePreference struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ServiceType string             `json:"service_type"`
	Source      string             `json:"source"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantStorefrontDraft struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Document    []byte             `json:"document"`
	BaseVersion pgtype.Timestamptz `json:"base_version"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantStorefrontSetting struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	LogoUrl              string             `json:"logo_url"`
	FaviconUrl           string             `json:"favicon_url"`
	BusinessName         string             `json:"business_name"`
	Tagline              string             `json:"tagline"`
	Description          string             `json:"description"`
	Phone                string             `json:"phone"`
	Address              string             `json:"address"`
	ThemePreset          string             `json:"theme_preset"`
	PrimaryColor         string             `json:"primary_color"`
	SecondaryColor       string             `json:"secondary_color"`
	AccentColor          string             `json:"accent_color"`
	ThemeMode            string             `json:"theme_mode"`
	FontFamily           string             `json:"font_family"`
	Radius               string             `json:"radius"`
	ButtonStyle          string             `json:"button_style"`
	CardStyle            string             `json:"card_style"`
	HeaderStyle          string             `json:"header_style"`
	HeroStyle            string             `json:"hero_style"`
	HeroImageUrl         string             `json:"hero_image_url"`
	OrderingEnabled      bool               `json:"ordering_enabled"`
	ClosedMessage        string             `json:"closed_message"`
	CustomerLoginEnabled bool               `json:"customer_login_enabled"`
	PrepTimeMinutes      int32              `json:"prep_time_minutes"`
	TaxPercent           pgtype.Numeric     `json:"tax_percent"`
	PackagingFee         pgtype.Numeric     `json:"packaging_fee"`
	OpeningHours         []byte             `json:"opening_hours"`
	Homepage             []byte             `json:"homepage"`
	Payments             []byte             `json:"payments"`
	Workflow             []byte             `json:"workflow"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ProductLayout        string             `json:"product_layout"`
	FilterStyle          string             `json:"filter_style"`
	CustomerLoginMode    string             `json:"customer_login_mode"`
}

type TenantType struct {
	Code      string             `json:"code"`
	Label     string             `json:"label"`
	Active    bool               `json:"active"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TermsAcceptance struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	DocumentID pgtype.UUID        `json:"document_id"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	Metadata   []byte             `json:"metadata"`
}

type TermsDocument struct {
	ID          pgtype.UUID        `json:"id"`
	Version     string             `json:"version"`
	ContentUrl  string             `json:"content_url"`
	ContentHash string             `json:"content_hash"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type ThemePreset struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Tokens    []byte             `json:"tokens"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MustSetPassword bool               `json:"must_set_password"`
	InviteTokenHash pgtype.Text        `json:"invite_token_hash"`
	// Per-user console appearance override. NULL = follow the business default.
	ConsoleTheme []byte `json:"console_theme"`
}
