// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Result     string             `json:"result"`
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ImageUrl    pgtype.Text        `json:"image_url"`
}

type Customer struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Phone       pgtype.Text        `json:"phone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	IsBlocked   bool               `json:"is_blocked"`
}

type CustomerOtpCode struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Phone      string             `json:"phone"`
	CodeHash   string             `json:"code_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	OrderNumber      int32              `json:"order_number"`
	Status           string             `json:"status"`
	OrderType        string             `json:"order_type"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	Tax              pgtype.Numeric     `json:"tax"`
	Discount         pgtype.Numeric     `json:"discount"`
	Total            pgtype.Numeric     `json:"total"`
	CustomerName     string             `json:"customer_name"`
	CustomerPhone    string             `json:"customer_phone"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomerEmail    string             `json:"customer_email"`
	Notes            string             `json:"notes"`
	EstimatedReadyAt pgtype.Timestamptz `json:"estimated_ready_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	PreparingAt      pgtype.Timestamptz `json:"preparing_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CancelledAt      pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason     string             `json:"cancel_reason"`
	Source           string             `json:"source"`
	ClientToken      string             `json:"client_token"`
	PackagingFee     pgtype.Numeric     `json:"packaging_fee"`
}

type OrderCounter struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	LastNumber int64       `json:"last_number"`
}

type OrderItem struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	OrderID             pgtype.UUID        `json:"order_id"`
	ProductID           pgtype.UUID        `json:"product_id"`
	ProductNameSnapshot string             `json:"product_name_snapshot"`
	UnitPrice           pgtype.Numeric     `json:"unit_price"`
	Quantity            int32              `json:"quantity"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Addons              []byte             `json:"addons"`
	Notes               string             `json:"notes"`
}

type OrderStatusHistory struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	OrderID    pgtype.UUID        `json:"order_id"`
	FromStatus string             `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Actor      string             `json:"actor"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	Provider          string             `json:"provider"`
	ProviderReference string             `json:"provider_reference"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FailureReason     string             `json:"failure_reason"`
	AttemptCount      int32              `json:"attempt_count"`
}

type Plan struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	MaxStaff    int32              `json:"max_staff"`
	MaxProducts int32              `json:"max_products"`
	Features    []byte             `json:"features"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PlatformConfiguration struct {
	ID           pgtype.UUID        `json:"id"`
	ServiceType  string             `json:"service_type"`
	Provider     string             `json:"provider"`
	Config       []byte             `json:"config"`
	SecretConfig []byte             `json:"secret_config"`
	Status       string             `json:"status"`
	Enabled      bool               `json:"enabled"`
	AllowTenants bool               `json:"allow_tenants"`
	LastError    string             `json:"last_error"`
	LastTestedAt pgtype.Timestamptz `json:"last_tested_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PlatformSetting struct {
	ID        int16              `json:"id"`
	Config    []byte             `json:"config"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID                       pgtype.UUID        `json:"id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	CategoryID               pgtype.UUID        `json:"category_id"`
	Name                     string             `json:"name"`
	Description              string             `json:"description"`
	Price                    pgtype.Numeric     `json:"price"`
	ImageUrl                 pgtype.Text        `json:"image_url"`
	SortOrder                int32              `json:"sort_order"`
	IsAvailable              bool               `json:"is_available"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	IsVegetarian             bool               `json:"is_vegetarian"`
	IsFeatured               bool               `json:"is_featured"`
	IsPopular                bool               `json:"is_popular"`
	AllowSpecialInstructions bool               `json:"allow_special_instructions"`
	Addons                   []byte             `json:"addons"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	Status    string             `json:"status"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	BusinessType     string             `json:"business_type"`
	OwnerName        string             `json:"owner_name"`
	Phone            string             `json:"phone"`
	Email            string             `json:"email"`
	Address          string             `json:"address"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	IsPublished      bool               `json:"is_published"`
	PlanID           pgtype.UUID        `json:"plan_id"`
	SetupStatus      string             `json:"setup_status"`
	ThemePresetID    string             `json:"theme_preset_id"`
	ThemeColorMode   string             `json:"theme_color_mode"`
	ThemeOverrides   []byte             `json:"theme_overrides"`
	LogoUrl          string             `json:"logo_url"`
	FaviconUrl       string             `json:"favicon_url"`
	ShortDescription string             `json:"short_description"`
	Currency         string             `json:"currency"`
	Timezone         string             `json:"timezone"`
	Language         string             `json:"language"`
	StoreStatus      string             `json:"store_status"`
	ShopType         string             `json:"shop_type"`
	StatusMessage    string             `json:"status_message"`
}

type TenantConfiguration struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ServiceType  string             `json:"service_type"`
	Provider     string             `json:"provider"`
	Config       []byte             `json:"config"`
	SecretConfig []byte             `json:"secret_config"`
	Status       string             `json:"status"`
	Enabled      bool               `json:"enabled"`
	LastError    string             `json:"last_error"`
	LastTestedAt pgtype.Timestamptz `json:"last_tested_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TenantServiceAccess struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ServiceType   string             `json:"service_type"`
	AllowPlatform bool               `json:"allow_platform"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TenantServicePreference struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ServiceType string             `json:"service_type"`
	Source      string             `json:"source"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantStorefrontSetting struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	LogoUrl              string             `json:"logo_url"`
	FaviconUrl           string             `json:"favicon_url"`
	BusinessName         string             `json:"business_name"`
	Tagline              string             `json:"tagline"`
	Description          string             `json:"description"`
	Phone                string             `json:"phone"`
	Address              string             `json:"address"`
	ThemePreset          string             `json:"theme_preset"`
	PrimaryColor         string             `json:"primary_color"`
	SecondaryColor       string             `json:"secondary_color"`
	AccentColor          string             `json:"accent_color"`
	ThemeMode            string             `json:"theme_mode"`
	FontFamily           string             `json:"font_family"`
	Radius               string             `json:"radius"`
	ButtonStyle          string             `json:"button_style"`
	CardStyle            string             `json:"card_style"`
	HeaderStyle          string             `json:"header_style"`
	HeroStyle            string             `json:"hero_style"`
	HeroImageUrl         string             `json:"hero_image_url"`
	OrderingEnabled      bool               `json:"ordering_enabled"`
	ClosedMessage        string             `json:"closed_message"`
	CustomerLoginEnabled bool               `json:"customer_login_enabled"`
	PrepTimeMinutes      int32              `json:"prep_time_minutes"`
	TaxPercent           pgtype.Numeric     `json:"tax_percent"`
	PackagingFee         pgtype.Numeric     `json:"packaging_fee"`
	OpeningHours         []byte             `json:"opening_hours"`
	Homepage             []byte             `json:"homepage"`
	Payments             []byte             `json:"payments"`
	Workflow             []byte             `json:"workflow"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ProductLayout        string             `json:"product_layout"`
	FilterStyle          string             `json:"filter_style"`
	CustomerLoginMode    string             `json:"customer_login_mode"`
}

type TenantType struct {
	Code      string             `json:"code"`
	Label     string             `json:"label"`
	Active    bool               `json:"active"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ThemePreset struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Tokens    []byte             `json:"tokens"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MustSetPassword bool               `json:"must_set_password"`
	InviteTokenHash pgtype.Text        `json:"invite_token_hash"`
}
