// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplateVersion = `-- name: CreateTemplateVersion :one
INSERT INTO notification_templates (tenant_id, event_code, channel, subject, body, is_active, version)
VALUES (
    $5, $1, $2, $3, $4, TRUE,
    COALESCE((
        SELECT MAX(version) + 1 FROM notification_templates
        WHERE event_code = $1 AND channel = $2
          AND tenant_id IS NOT DISTINCT FROM $5::uuid
    ), 1)
)
RETURNING id, tenant_id, event_code, channel, subject, body, is_active, version, created_at, updated_at
`

type CreateTemplateVersionParams struct {
	EventCode string      `json:"event_code"`
	Channel   string      `json:"channel"`
	Subject   string      `json:"subject"`
	Body      string      `json:"body"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateTemplateVersion(ctx context.Context, arg CreateTemplateVersionParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplateVersion,
		arg.EventCode,
		arg.Channel,
		arg.Subject,
		arg.Body,
		arg.TenantID,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventCode,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateTemplate = `-- name: DeactivateTemplate :exec
UPDATE notification_templates
SET is_active = FALSE, updated_at = now()
WHERE event_code = $1 AND channel = $2 AND is_active
  AND tenant_id IS NOT DISTINCT FROM $3::uuid
`

type DeactivateTemplateParams struct {
	EventCode string      `json:"event_code"`
	Channel   string      `json:"channel"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

// Deactivates whatever is currently active for this key before a new
// version is inserted, so "the active template" stays a single row per the
// partial unique indexes rather than a status flag maintained by hand.
func (q *Queries) DeactivateTemplate(ctx context.Context, arg DeactivateTemplateParams) error {
	_, err := q.db.Exec(ctx, deactivateTemplate, arg.EventCode, arg.Channel, arg.TenantID)
	return err
}

const getEffectiveTemplate = `-- name: GetEffectiveTemplate :one
SELECT id, tenant_id, event_code, channel, subject, body, is_active, version, created_at, updated_at FROM notification_templates
WHERE event_code = $1 AND channel = $2 AND is_active
  AND (tenant_id = $3 OR tenant_id IS NULL)
ORDER BY tenant_id NULLS LAST
LIMIT 1
`

type GetEffectiveTemplateParams struct {
	EventCode string      `json:"event_code"`
	Channel   string      `json:"channel"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetEffectiveTemplate(ctx context.Context, arg GetEffectiveTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getEffectiveTemplate, arg.EventCode, arg.Channel, arg.TenantID)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventCode,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEffectiveTemplatesForTenant = `-- name: ListEffectiveTemplatesForTenant :many
SELECT DISTINCT ON (event_code, channel) id, tenant_id, event_code, channel, subject, body, is_active, version, created_at, updated_at
FROM notification_templates
WHERE is_active AND (tenant_id = $1 OR tenant_id IS NULL)
ORDER BY event_code, channel, tenant_id NULLS LAST
`

func (q *Queries) ListEffectiveTemplatesForTenant(ctx context.Context, tenantID pgtype.UUID) ([]NotificationTemplate, error) {
	rows, err := q.db.Query(ctx, listEffectiveTemplatesForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTemplate{}
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventCode,
			&i.Channel,
			&i.Subject,
			&i.Body,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTemplates = `-- name: ListPlatformTemplates :many
SELECT id, tenant_id, event_code, channel, subject, body, is_active, version, created_at, updated_at FROM notification_templates
WHERE is_active AND tenant_id IS NULL
ORDER BY event_code, channel
`

func (q *Queries) ListPlatformTemplates(ctx context.Context) ([]NotificationTemplate, error) {
	rows, err := q.db.Query(ctx, listPlatformTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTemplate{}
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventCode,
			&i.Channel,
			&i.Subject,
			&i.Body,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
