// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_deliveries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminRetryDelivery = `-- name: AdminRetryDelivery :exec
UPDATE notification_deliveries
SET status = 'PENDING', next_attempt_at = now()
WHERE id = $1 AND status IN ('FAILED', 'DEAD')
`

// A Super Admin may retry any delivery, tenant-owned or platform-scoped.
func (q *Queries) AdminRetryDelivery(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminRetryDelivery, id)
	return err
}

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many
UPDATE notification_deliveries
SET next_attempt_at = now() + interval '2 minutes'
WHERE id IN (
    SELECT id FROM notification_deliveries
    WHERE status IN ('PENDING', 'RETRYING') AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, notification_id, tenant_id, event_code, channel, recipient, status, attempt_count, max_attempts, last_error, provider_message_id, idempotency_key, next_attempt_at, delivered_at, created_at
`

// The worker's claim: due rows get their lease (next_attempt_at) pushed
// forward immediately, inside this single statement, so the lock is held
// only for the UPDATE itself rather than for the lifetime of a provider
// call. A worker that crashes mid-send leaves the row reclaimable once the
// lease expires.
func (q *Queries) ClaimDueDeliveries(ctx context.Context, limit int32) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, claimDueDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.TenantID,
			&i.EventCode,
			&i.Channel,
			&i.Recipient,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LastError,
			&i.ProviderMessageID,
			&i.IdempotencyKey,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueNotificationDelivery = `-- name: EnqueueNotificationDelivery :one
INSERT INTO notification_deliveries (
    notification_id, tenant_id, event_code, channel, recipient, idempotency_key
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, notification_id, tenant_id, event_code, channel, recipient, status, attempt_count, max_attempts, last_error, provider_message_id, idempotency_key, next_attempt_at, delivered_at, created_at
`

type EnqueueNotificationDeliveryParams struct {
	NotificationID pgtype.UUID `json:"notification_id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	EventCode      string      `json:"event_code"`
	Channel        string      `json:"channel"`
	Recipient      string      `json:"recipient"`
	IdempotencyKey string      `json:"idempotency_key"`
}

// Fire-and-forget enqueue. A duplicate idempotency_key (a retried or
// re-published event) is silently skipped — the caller sees zero rows
// rather than an error, since "already enqueued" is success, not failure.
func (q *Queries) EnqueueNotificationDelivery(ctx context.Context, arg EnqueueNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, enqueueNotificationDelivery,
		arg.NotificationID,
		arg.TenantID,
		arg.EventCode,
		arg.Channel,
		arg.Recipient,
		arg.IdempotencyKey,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.TenantID,
		&i.EventCode,
		&i.Channel,
		&i.Recipient,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllDeliveries = `-- name: ListAllDeliveries :many
SELECT id, notification_id, tenant_id, event_code, channel, recipient, status, attempt_count, max_attempts, last_error, provider_message_id, idempotency_key, next_attempt_at, delivered_at, created_at FROM notification_deliveries
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllDeliveriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllDeliveries(ctx context.Context, arg ListAllDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listAllDeliveries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.TenantID,
			&i.EventCode,
			&i.Channel,
			&i.Recipient,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LastError,
			&i.ProviderMessageID,
			&i.IdempotencyKey,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesForTenant = `-- name: ListDeliveriesForTenant :many
SELECT id, notification_id, tenant_id, event_code, channel, recipient, status, attempt_count, max_attempts, last_error, provider_message_id, idempotency_key, next_attempt_at, delivered_at, created_at FROM notification_deliveries
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeliveriesForTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListDeliveriesForTenant(ctx context.Context, arg ListDeliveriesForTenantParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesForTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.TenantID,
			&i.EventCode,
			&i.Channel,
			&i.Recipient,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LastError,
			&i.ProviderMessageID,
			&i.IdempotencyKey,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
UPDATE notification_deliveries
SET status = 'SENT', provider_message_id = $2, delivered_at = now()
WHERE id = $1
`

type MarkDeliverySentParams struct {
	ID                pgtype.UUID `json:"id"`
	ProviderMessageID string      `json:"provider_message_id"`
}

func (q *Queries) MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) error {
	_, err := q.db.Exec(ctx, markDeliverySent, arg.ID, arg.ProviderMessageID)
	return err
}

const retryDelivery = `-- name: RetryDelivery :exec
UPDATE notification_deliveries
SET status = 'PENDING', next_attempt_at = now()
WHERE id = $1 AND tenant_id IS NOT DISTINCT FROM $2::uuid
  AND status IN ('FAILED', 'DEAD')
`

type RetryDeliveryParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Re-queues a failed/dead delivery for the next worker tick. Scoped by
// tenant_id so a tenant can only retry its own deliveries; a platform-scoped
// row (tenant_id NULL) is retried with tenant_id passed as NULL.
func (q *Queries) RetryDelivery(ctx context.Context, arg RetryDeliveryParams) error {
	_, err := q.db.Exec(ctx, retryDelivery, arg.ID, arg.TenantID)
	return err
}

const updateDeliveryAttempt = `-- name: UpdateDeliveryAttempt :exec
UPDATE notification_deliveries
SET status = $2, attempt_count = $3, last_error = $4, next_attempt_at = $5
WHERE id = $1
`

type UpdateDeliveryAttemptParams struct {
	ID            pgtype.UUID        `json:"id"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     string             `json:"last_error"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) UpdateDeliveryAttempt(ctx context.Context, arg UpdateDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryAttempt,
		arg.ID,
		arg.Status,
		arg.AttemptCount,
		arg.LastError,
		arg.NextAttemptAt,
	)
	return err
}
