// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_events.sql

package sqlc

import (
	"context"
)

const getNotificationEvent = `-- name: GetNotificationEvent :one
SELECT code, category, label, description, default_channels, required_capability, variables, created_at FROM notification_events WHERE code = $1
`

func (q *Queries) GetNotificationEvent(ctx context.Context, code string) (NotificationEvent, error) {
	row := q.db.QueryRow(ctx, getNotificationEvent, code)
	var i NotificationEvent
	err := row.Scan(
		&i.Code,
		&i.Category,
		&i.Label,
		&i.Description,
		&i.DefaultChannels,
		&i.RequiredCapability,
		&i.Variables,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationEvents = `-- name: ListNotificationEvents :many
SELECT code, category, label, description, default_channels, required_capability, variables, created_at FROM notification_events
ORDER BY category, label
`

func (q *Queries) ListNotificationEvents(ctx context.Context) ([]NotificationEvent, error) {
	rows, err := q.db.Query(ctx, listNotificationEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.Code,
			&i.Category,
			&i.Label,
			&i.Description,
			&i.DefaultChannels,
			&i.RequiredCapability,
			&i.Variables,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationEventsForCapabilities = `-- name: ListNotificationEventsForCapabilities :many
SELECT code, category, label, description, default_channels, required_capability, variables, created_at FROM notification_events
WHERE required_capability IS NULL OR required_capability = ANY($1::text[])
ORDER BY category, label
`

// Events available to a tenant: either not capability-gated, or gated by a
// capability the tenant actually has enabled. Keeps the settings UI from
// showing "Reservation confirmed" to a food shop that has no RESERVATIONS
// capability.
func (q *Queries) ListNotificationEventsForCapabilities(ctx context.Context, capabilityCodes []string) ([]NotificationEvent, error) {
	rows, err := q.db.Query(ctx, listNotificationEventsForCapabilities, capabilityCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.Code,
			&i.Category,
			&i.Label,
			&i.Description,
			&i.DefaultChannels,
			&i.RequiredCapability,
			&i.Variables,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
