// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_preferences.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, overrides, sound_enabled, quiet_hours_start, quiet_hours_end, quiet_hours_tz, updated_at FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.Overrides,
		&i.SoundEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTz,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (user_id, overrides, sound_enabled, quiet_hours_start, quiet_hours_end, quiet_hours_tz)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    overrides = EXCLUDED.overrides,
    sound_enabled = EXCLUDED.sound_enabled,
    quiet_hours_start = EXCLUDED.quiet_hours_start,
    quiet_hours_end = EXCLUDED.quiet_hours_end,
    quiet_hours_tz = EXCLUDED.quiet_hours_tz,
    updated_at = now()
RETURNING user_id, overrides, sound_enabled, quiet_hours_start, quiet_hours_end, quiet_hours_tz, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Overrides       []byte      `json:"overrides"`
	SoundEnabled    bool        `json:"sound_enabled"`
	QuietHoursStart pgtype.Time `json:"quiet_hours_start"`
	QuietHoursEnd   pgtype.Time `json:"quiet_hours_end"`
	QuietHoursTz    pgtype.Text `json:"quiet_hours_tz"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.Overrides,
		arg.SoundEnabled,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.QuietHoursTz,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.Overrides,
		&i.SoundEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTz,
		&i.UpdatedAt,
	)
	return i, err
}
