// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_rules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTenantNotificationRuleOverride = `-- name: DeleteTenantNotificationRuleOverride :exec
DELETE FROM notification_rules
WHERE tenant_id = $1 AND event_code = $2 AND channel = $3 AND recipient_policy = $4
`

type DeleteTenantNotificationRuleOverrideParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	EventCode       string      `json:"event_code"`
	Channel         string      `json:"channel"`
	RecipientPolicy string      `json:"recipient_policy"`
}

// Reverts a tenant to inheriting the platform default for this key.
func (q *Queries) DeleteTenantNotificationRuleOverride(ctx context.Context, arg DeleteTenantNotificationRuleOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteTenantNotificationRuleOverride,
		arg.TenantID,
		arg.EventCode,
		arg.Channel,
		arg.RecipientPolicy,
	)
	return err
}

const isRuleLockedForTenant = `-- name: IsRuleLockedForTenant :one
SELECT COALESCE(
    (SELECT locked FROM notification_rules
     WHERE event_code = $2 AND channel = $3 AND recipient_policy = $4
       AND (tenant_id = $1 OR tenant_id IS NULL)
     ORDER BY tenant_id NULLS LAST LIMIT 1),
    FALSE
)::boolean AS locked
`

type IsRuleLockedForTenantParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	EventCode       string      `json:"event_code"`
	Channel         string      `json:"channel"`
	RecipientPolicy string      `json:"recipient_policy"`
}

// Whether the effective (tenant-or-platform) rule for this exact key is
// locked, checked before accepting a tenant write.
func (q *Queries) IsRuleLockedForTenant(ctx context.Context, arg IsRuleLockedForTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRuleLockedForTenant,
		arg.TenantID,
		arg.EventCode,
		arg.Channel,
		arg.RecipientPolicy,
	)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const listEffectiveRulesForEvent = `-- name: ListEffectiveRulesForEvent :many
SELECT DISTINCT ON (channel, recipient_policy) id, tenant_id, event_code, channel, enabled, recipient_policy, priority, locked, created_at, updated_at
FROM notification_rules
WHERE event_code = $1 AND (tenant_id = $2 OR tenant_id IS NULL)
ORDER BY channel, recipient_policy, tenant_id NULLS LAST
`

type ListEffectiveRulesForEventParams struct {
	EventCode string      `json:"event_code"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

// The merge that implements Platform Defaults -> Business Configuration
// precedence: one row per (channel, recipient_policy), the tenant's own row
// winning over the platform default when both exist. `tenant_id NULLS LAST`
// sorts the non-null (tenant) row first within each DISTINCT ON group.
func (q *Queries) ListEffectiveRulesForEvent(ctx context.Context, arg ListEffectiveRulesForEventParams) ([]NotificationRule, error) {
	rows, err := q.db.Query(ctx, listEffectiveRulesForEvent, arg.EventCode, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRule{}
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventCode,
			&i.Channel,
			&i.Enabled,
			&i.RecipientPolicy,
			&i.Priority,
			&i.Locked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveRulesForTenant = `-- name: ListEffectiveRulesForTenant :many
SELECT DISTINCT ON (event_code, channel, recipient_policy) id, tenant_id, event_code, channel, enabled, recipient_policy, priority, locked, created_at, updated_at
FROM notification_rules
WHERE tenant_id = $1 OR tenant_id IS NULL
ORDER BY event_code, channel, recipient_policy, tenant_id NULLS LAST
`

func (q *Queries) ListEffectiveRulesForTenant(ctx context.Context, tenantID pgtype.UUID) ([]NotificationRule, error) {
	rows, err := q.db.Query(ctx, listEffectiveRulesForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRule{}
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventCode,
			&i.Channel,
			&i.Enabled,
			&i.RecipientPolicy,
			&i.Priority,
			&i.Locked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformRules = `-- name: ListPlatformRules :many
SELECT id, tenant_id, event_code, channel, enabled, recipient_policy, priority, locked, created_at, updated_at FROM notification_rules
WHERE tenant_id IS NULL
ORDER BY event_code, channel, recipient_policy
`

func (q *Queries) ListPlatformRules(ctx context.Context) ([]NotificationRule, error) {
	rows, err := q.db.Query(ctx, listPlatformRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRule{}
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventCode,
			&i.Channel,
			&i.Enabled,
			&i.RecipientPolicy,
			&i.Priority,
			&i.Locked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlatformNotificationRule = `-- name: UpsertPlatformNotificationRule :one
INSERT INTO notification_rules (tenant_id, event_code, channel, enabled, recipient_policy, priority, locked)
VALUES (NULL, $1, $2, $3, $4, $5, $6)
ON CONFLICT (event_code, channel, recipient_policy) WHERE tenant_id IS NULL
DO UPDATE SET enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, locked = EXCLUDED.locked, updated_at = now()
RETURNING id, tenant_id, event_code, channel, enabled, recipient_policy, priority, locked, created_at, updated_at
`

type UpsertPlatformNotificationRuleParams struct {
	EventCode       string `json:"event_code"`
	Channel         string `json:"channel"`
	Enabled         bool   `json:"enabled"`
	RecipientPolicy string `json:"recipient_policy"`
	Priority        string `json:"priority"`
	Locked          bool   `json:"locked"`
}

// The platform default. Only ever called with tenant_id NULL, matching the
// partial unique index rather than the full constraint (which does not
// de-duplicate NULL tenant_id rows).
func (q *Queries) UpsertPlatformNotificationRule(ctx context.Context, arg UpsertPlatformNotificationRuleParams) (NotificationRule, error) {
	row := q.db.QueryRow(ctx, upsertPlatformNotificationRule,
		arg.EventCode,
		arg.Channel,
		arg.Enabled,
		arg.RecipientPolicy,
		arg.Priority,
		arg.Locked,
	)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventCode,
		&i.Channel,
		&i.Enabled,
		&i.RecipientPolicy,
		&i.Priority,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantNotificationRule = `-- name: UpsertTenantNotificationRule :one
INSERT INTO notification_rules (tenant_id, event_code, channel, enabled, recipient_policy, priority, locked)
VALUES ($1, $2, $3, $4, $5, $6, FALSE)
ON CONFLICT (tenant_id, event_code, channel, recipient_policy)
DO UPDATE SET enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, updated_at = now()
RETURNING id, tenant_id, event_code, channel, enabled, recipient_policy, priority, locked, created_at, updated_at
`

type UpsertTenantNotificationRuleParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	EventCode       string      `json:"event_code"`
	Channel         string      `json:"channel"`
	Enabled         bool        `json:"enabled"`
	RecipientPolicy string      `json:"recipient_policy"`
	Priority        string      `json:"priority"`
}

// A tenant override. Only ever called with a concrete tenant_id, so it
// matches the full (tenant_id, event_code, channel, recipient_policy)
// unique constraint. The caller is responsible for rejecting this when the
// effective platform rule for the same key is locked.
func (q *Queries) UpsertTenantNotificationRule(ctx context.Context, arg UpsertTenantNotificationRuleParams) (NotificationRule, error) {
	row := q.db.QueryRow(ctx, upsertTenantNotificationRule,
		arg.TenantID,
		arg.EventCode,
		arg.Channel,
		arg.Enabled,
		arg.RecipientPolicy,
		arg.Priority,
	)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventCode,
		&i.Channel,
		&i.Enabled,
		&i.RecipientPolicy,
		&i.Priority,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
