// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadForUser = `-- name: CountUnreadForUser :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    tenant_id, user_id, type, title, body, data, priority, event_code
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, user_id, type, title, body, data, read_at, created_at, priority, event_code
`

type CreateNotificationParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Type      string      `json:"type"`
	Title     string      `json:"title"`
	Body      string      `json:"body"`
	Data      []byte      `json:"data"`
	Priority  string      `json:"priority"`
	EventCode pgtype.Text `json:"event_code"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TenantID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.Priority,
		arg.EventCode,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Priority,
		&i.EventCode,
	)
	return i, err
}

const listActivePlatformUsers = `-- name: ListActivePlatformUsers :many
SELECT id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme, mfa_enabled FROM users
WHERE tenant_id IS NULL AND status = 'ACTIVE'
`

// Recipient resolution for a platform-wide event. Tenant-wide recipient
// resolution reuses the existing ListTenantUsers query (users.sql) instead of
// a second copy — it already returns every column this needs.
func (q *Queries) ListActivePlatformUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActivePlatformUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MustSetPassword,
			&i.InviteTokenHash,
			&i.ConsoleTheme,
			&i.MfaEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, tenant_id, user_id, type, title, body, data, read_at, created_at, priority, event_code FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

// user_id alone is a sufficient, safe scope: a user has exactly one fixed
// tenant_id (or NULL for a platform account), enforced by
// users_tenant_role_check, so one query serves both the shop and the console.
func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Priority,
			&i.EventCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUserBefore = `-- name: ListNotificationsForUserBefore :many
SELECT id, tenant_id, user_id, type, title, body, data, read_at, created_at, priority, event_code FROM notifications
WHERE user_id = $1
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsForUserBeforeParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	Limit           int32              `json:"limit"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
}

// Cursor pagination for the "view all" page: everything strictly older than
// a given row, by (created_at, id) so same-timestamp rows never repeat or
// get skipped across pages.
func (q *Queries) ListNotificationsForUserBefore(ctx context.Context, arg ListNotificationsForUserBeforeParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUserBefore,
		arg.UserID,
		arg.Limit,
		arg.BeforeCreatedAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Priority,
			&i.EventCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// The user_id guard keeps a user from marking someone else's notification read.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const markNotificationUnread = `-- name: MarkNotificationUnread :exec
UPDATE notifications
SET read_at = NULL
WHERE id = $1 AND user_id = $2
`

type MarkNotificationUnreadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationUnread(ctx context.Context, arg MarkNotificationUnreadParams) error {
	_, err := q.db.Exec(ctx, markNotificationUnread, arg.ID, arg.UserID)
	return err
}
