// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendOrderStatusHistory = `-- name: AppendOrderStatusHistory :one
INSERT INTO order_status_history (tenant_id, order_id, from_status, to_status, actor)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, order_id, from_status, to_status, actor, created_at
`

type AppendOrderStatusHistoryParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	OrderID    pgtype.UUID `json:"order_id"`
	FromStatus string      `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	Actor      string      `json:"actor"`
}

func (q *Queries) AppendOrderStatusHistory(ctx context.Context, arg AppendOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRow(ctx, appendOrderStatusHistory,
		arg.TenantID,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Actor,
	)
	var i OrderStatusHistory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const confirmPayment = `-- name: ConfirmPayment :one
UPDATE payments
SET status = 'PAID', paid_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, order_id, amount, method, status, provider, provider_reference, paid_at, created_at, updated_at, failure_reason, attempt_count, payable_type, payable_id, purpose
`

type ConfirmPaymentParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, confirmPayment, arg.ID, arg.TenantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.Provider,
		&i.ProviderReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.AttemptCount,
		&i.PayableType,
		&i.PayableID,
		&i.Purpose,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    tenant_id, customer_id, order_number, status, order_type,
    subtotal, tax, discount, packaging_fee, total, customer_name, customer_phone,
    customer_email, notes, estimated_ready_at, client_token, source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id
`

type CreateOrderParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	OrderNumber      int32              `json:"order_number"`
	Status           string             `json:"status"`
	OrderType        string             `json:"order_type"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	Tax              pgtype.Numeric     `json:"tax"`
	Discount         pgtype.Numeric     `json:"discount"`
	PackagingFee     pgtype.Numeric     `json:"packaging_fee"`
	Total            pgtype.Numeric     `json:"total"`
	CustomerName     string             `json:"customer_name"`
	CustomerPhone    string             `json:"customer_phone"`
	CustomerEmail    string             `json:"customer_email"`
	Notes            string             `json:"notes"`
	EstimatedReadyAt pgtype.Timestamptz `json:"estimated_ready_at"`
	ClientToken      string             `json:"client_token"`
	Source           string             `json:"source"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.TenantID,
		arg.CustomerID,
		arg.OrderNumber,
		arg.Status,
		arg.OrderType,
		arg.Subtotal,
		arg.Tax,
		arg.Discount,
		arg.PackagingFee,
		arg.Total,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CustomerEmail,
		arg.Notes,
		arg.EstimatedReadyAt,
		arg.ClientToken,
		arg.Source,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    tenant_id, order_id, product_id, product_name_snapshot,
    unit_price, quantity, subtotal, addons, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, order_id, product_id, product_name_snapshot, unit_price, quantity, subtotal, created_at, addons, notes
`

type CreateOrderItemParams struct {
	TenantID            pgtype.UUID    `json:"tenant_id"`
	OrderID             pgtype.UUID    `json:"order_id"`
	ProductID           pgtype.UUID    `json:"product_id"`
	ProductNameSnapshot string         `json:"product_name_snapshot"`
	UnitPrice           pgtype.Numeric `json:"unit_price"`
	Quantity            int32          `json:"quantity"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	Addons              []byte         `json:"addons"`
	Notes               string         `json:"notes"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.TenantID,
		arg.OrderID,
		arg.ProductID,
		arg.ProductNameSnapshot,
		arg.UnitPrice,
		arg.Quantity,
		arg.Subtotal,
		arg.Addons,
		arg.Notes,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductNameSnapshot,
		&i.UnitPrice,
		&i.Quantity,
		&i.Subtotal,
		&i.CreatedAt,
		&i.Addons,
		&i.Notes,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    tenant_id, order_id, amount, method, status, provider, provider_reference
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, order_id, amount, method, status, provider, provider_reference, paid_at, created_at, updated_at, failure_reason, attempt_count, payable_type, payable_id, purpose
`

type CreatePaymentParams struct {
	TenantID          pgtype.UUID    `json:"tenant_id"`
	OrderID           pgtype.UUID    `json:"order_id"`
	Amount            pgtype.Numeric `json:"amount"`
	Method            string         `json:"method"`
	Status            string         `json:"status"`
	Provider          string         `json:"provider"`
	ProviderReference string         `json:"provider_reference"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.TenantID,
		arg.OrderID,
		arg.Amount,
		arg.Method,
		arg.Status,
		arg.Provider,
		arg.ProviderReference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.Provider,
		&i.ProviderReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.AttemptCount,
		&i.PayableType,
		&i.PayableID,
		&i.Purpose,
	)
	return i, err
}

const ensureOrderCounter = `-- name: EnsureOrderCounter :exec
INSERT INTO order_counters (tenant_id, last_number)
VALUES ($1, 0)
ON CONFLICT (tenant_id) DO NOTHING
`

// Allocating an order number must work for a brand new tenant, which has no
// counter row yet. The insert/ignore seeds it at zero so the first order a shop
// ever takes is numbered 1 rather than failing.
func (q *Queries) EnsureOrderCounter(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureOrderCounter, tenantID)
	return err
}

const getOrderByClientToken = `-- name: GetOrderByClientToken :one
SELECT id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id FROM orders
WHERE tenant_id = $1 AND client_token = $2
LIMIT 1
`

type GetOrderByClientTokenParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ClientToken string      `json:"client_token"`
}

// Idempotent lookup for a retried checkout submit. A double tap, a refresh or
// a flaky network must never produce a second order.
func (q *Queries) GetOrderByClientToken(ctx context.Context, arg GetOrderByClientTokenParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByClientToken, arg.TenantID, arg.ClientToken)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id FROM orders
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetOrderByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, arg.ID, arg.TenantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const getOrderByTenantAndNumber = `-- name: GetOrderByTenantAndNumber :one
SELECT id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id FROM orders
WHERE tenant_id = $1 AND order_number = $2
LIMIT 1
`

type GetOrderByTenantAndNumberParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	OrderNumber int32       `json:"order_number"`
}

func (q *Queries) GetOrderByTenantAndNumber(ctx context.Context, arg GetOrderByTenantAndNumberParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByTenantAndNumber, arg.TenantID, arg.OrderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const getOrderByTenantNumberAndPhone = `-- name: GetOrderByTenantNumberAndPhone :one
SELECT id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id FROM orders
WHERE tenant_id = $1 AND order_number = $2 AND customer_phone = $3
LIMIT 1
`

type GetOrderByTenantNumberAndPhoneParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	OrderNumber   int32       `json:"order_number"`
	CustomerPhone string      `json:"customer_phone"`
}

// Guest tracking: an order number alone must not be enough, so the phone used
// at checkout is part of the lookup.
func (q *Queries) GetOrderByTenantNumberAndPhone(ctx context.Context, arg GetOrderByTenantNumberAndPhoneParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByTenantNumberAndPhone, arg.TenantID, arg.OrderNumber, arg.CustomerPhone)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, tenant_id, order_id, amount, method, status, provider, provider_reference, paid_at, created_at, updated_at, failure_reason, attempt_count, payable_type, payable_id, purpose FROM payments
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetPaymentByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, arg.ID, arg.TenantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.Provider,
		&i.ProviderReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.AttemptCount,
		&i.PayableType,
		&i.PayableID,
		&i.Purpose,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, tenant_id, order_id, amount, method, status, provider, provider_reference, paid_at, created_at, updated_at, failure_reason, attempt_count, payable_type, payable_id, purpose FROM payments
WHERE order_id = $1 AND tenant_id = $2
LIMIT 1
`

type GetPaymentByOrderIDParams struct {
	OrderID  pgtype.UUID `json:"order_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPaymentByOrderID(ctx context.Context, arg GetPaymentByOrderIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, arg.OrderID, arg.TenantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.Provider,
		&i.ProviderReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.AttemptCount,
		&i.PayableType,
		&i.PayableID,
		&i.Purpose,
	)
	return i, err
}

const listOrderHistory = `-- name: ListOrderHistory :many
SELECT
    o.id, o.tenant_id, o.customer_id, o.order_number, o.status, o.order_type, o.subtotal, o.tax, o.discount, o.total, o.customer_name, o.customer_phone, o.created_at, o.updated_at, o.customer_email, o.notes, o.estimated_ready_at, o.accepted_at, o.preparing_at, o.ready_at, o.completed_at, o.cancelled_at, o.cancel_reason, o.source, o.client_token, o.packaging_fee, o.table_id,
    (SELECT COUNT(*)::bigint FROM order_items oi WHERE oi.order_id = o.id) AS item_count,
    -- Coalesced because the join is optional: an order with no payment row
    -- yields NULL, which the generated scanner would refuse for a column the
    -- payments table declares NOT NULL.
    COALESCE(p.status, '')::text AS payment_status,
    COALESCE(p.method, '')::text AS payment_method
FROM orders o
LEFT JOIN LATERAL (
    SELECT status, method FROM payments
    WHERE payments.order_id = o.id
    ORDER BY created_at DESC LIMIT 1
) p ON TRUE
WHERE o.tenant_id = $1
  AND ($2::text IS NULL OR o.status = $2::text)
  AND ($3::text IS NULL OR o.source = $3::text)
  AND ($4::timestamptz IS NULL OR o.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR o.created_at < $5::timestamptz)
  AND (
        $6::text IS NULL
        OR o.customer_name ILIKE '%' || $6::text || '%'
        OR o.customer_phone ILIKE '%' || $6::text || '%'
        OR o.order_number::text = $6::text
      )
ORDER BY o.created_at DESC
LIMIT $8 OFFSET $7
`

type ListOrderHistoryParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Status    pgtype.Text        `json:"status"`
	Source    pgtype.Text        `json:"source"`
	FromDate  pgtype.Timestamptz `json:"from_date"`
	ToDate    pgtype.Timestamptz `json:"to_date"`
	Search    pgtype.Text        `json:"search"`
	RowOffset int32              `json:"row_offset"`
	RowLimit  int32              `json:"row_limit"`
}

type ListOrderHistoryRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	OrderNumber      int32              `json:"order_number"`
	Status           string             `json:"status"`
	OrderType        string             `json:"order_type"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	Tax              pgtype.Numeric     `json:"tax"`
	Discount         pgtype.Numeric     `json:"discount"`
	Total            pgtype.Numeric     `json:"total"`
	CustomerName     string             `json:"customer_name"`
	CustomerPhone    string             `json:"customer_phone"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomerEmail    string             `json:"customer_email"`
	Notes            string             `json:"notes"`
	EstimatedReadyAt pgtype.Timestamptz `json:"estimated_ready_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	PreparingAt      pgtype.Timestamptz `json:"preparing_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CancelledAt      pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason     string             `json:"cancel_reason"`
	Source           string             `json:"source"`
	ClientToken      string             `json:"client_token"`
	PackagingFee     pgtype.Numeric     `json:"packaging_fee"`
	TableID          pgtype.UUID        `json:"table_id"`
	ItemCount        int64              `json:"item_count"`
	PaymentStatus    string             `json:"payment_status"`
	PaymentMethod    string             `json:"payment_method"`
}

// Order history for the tenant console. Unlike the Selling board — which shows
// the live queue — this searches the whole record, so every filter is optional
// and applied in SQL rather than by shipping the table to the browser.
//
// sqlc.narg values are NULL when the console did not filter on them, and the
// COALESCE pairs below turn that into "match everything".
func (q *Queries) ListOrderHistory(ctx context.Context, arg ListOrderHistoryParams) ([]ListOrderHistoryRow, error) {
	rows, err := q.db.Query(ctx, listOrderHistory,
		arg.TenantID,
		arg.Status,
		arg.Source,
		arg.FromDate,
		arg.ToDate,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderHistoryRow{}
	for rows.Next() {
		var i ListOrderHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Status,
			&i.OrderType,
			&i.Subtotal,
			&i.Tax,
			&i.Discount,
			&i.Total,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.Notes,
			&i.EstimatedReadyAt,
			&i.AcceptedAt,
			&i.PreparingAt,
			&i.ReadyAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelReason,
			&i.Source,
			&i.ClientToken,
			&i.PackagingFee,
			&i.TableID,
			&i.ItemCount,
			&i.PaymentStatus,
			&i.PaymentMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderIDsByTenant = `-- name: ListOrderIDsByTenant :many
SELECT id FROM orders
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOrderIDsByTenantParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListOrderIDsByTenant(ctx context.Context, arg ListOrderIDsByTenantParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOrderIDsByTenant, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, tenant_id, order_id, product_id, product_name_snapshot, unit_price, quantity, subtotal, created_at, addons, notes FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductNameSnapshot,
			&i.UnitPrice,
			&i.Quantity,
			&i.Subtotal,
			&i.CreatedAt,
			&i.Addons,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderStatusHistory = `-- name: ListOrderStatusHistory :many
SELECT id, tenant_id, order_id, from_status, to_status, actor, created_at FROM order_status_history
WHERE order_id = $1 AND tenant_id = $2
ORDER BY created_at ASC
`

type ListOrderStatusHistoryParams struct {
	OrderID  pgtype.UUID `json:"order_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListOrderStatusHistory(ctx context.Context, arg ListOrderStatusHistoryParams) ([]OrderStatusHistory, error) {
	rows, err := q.db.Query(ctx, listOrderStatusHistory, arg.OrderID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderStatusHistory{}
	for rows.Next() {
		var i OrderStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByTenant = `-- name: ListOrdersByTenant :many
SELECT id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id FROM orders
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOrdersByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListOrdersByTenant(ctx context.Context, arg ListOrdersByTenantParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Status,
			&i.OrderType,
			&i.Subtotal,
			&i.Tax,
			&i.Discount,
			&i.Total,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.Notes,
			&i.EstimatedReadyAt,
			&i.AcceptedAt,
			&i.PreparingAt,
			&i.ReadyAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelReason,
			&i.Source,
			&i.ClientToken,
			&i.PackagingFee,
			&i.TableID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByTenantAndPhone = `-- name: ListOrdersByTenantAndPhone :many
SELECT id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id FROM orders
WHERE tenant_id = $1 AND customer_phone = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListOrdersByTenantAndPhoneParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	CustomerPhone string      `json:"customer_phone"`
	LimitCount    int32       `json:"limit_count"`
}

// Guest order lookup from the orders page: a phone number returns every order
// placed with it, newest first.
func (q *Queries) ListOrdersByTenantAndPhone(ctx context.Context, arg ListOrdersByTenantAndPhoneParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByTenantAndPhone, arg.TenantID, arg.CustomerPhone, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Status,
			&i.OrderType,
			&i.Subtotal,
			&i.Tax,
			&i.Discount,
			&i.Total,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.Notes,
			&i.EstimatedReadyAt,
			&i.AcceptedAt,
			&i.PreparingAt,
			&i.ReadyAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelReason,
			&i.Source,
			&i.ClientToken,
			&i.PackagingFee,
			&i.TableID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantActivity = `-- name: ListTenantActivity :many
SELECT
    h.id,
    h.order_id,
    h.from_status,
    h.to_status,
    h.actor,
    h.created_at,
    o.order_number,
    o.customer_name,
    o.customer_phone,
    o.total,
    o.source
FROM order_status_history h
JOIN orders o ON o.id = h.order_id
WHERE h.tenant_id = $1
  AND ($2::text IS NULL OR h.to_status = $2::text)
ORDER BY h.created_at DESC
LIMIT $3
`

type ListTenantActivityParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ToStatus pgtype.Text `json:"to_status"`
	RowLimit int32       `json:"row_limit"`
}

type ListTenantActivityRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	FromStatus    string             `json:"from_status"`
	ToStatus      string             `json:"to_status"`
	Actor         string             `json:"actor"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	OrderNumber   int32              `json:"order_number"`
	CustomerName  string             `json:"customer_name"`
	CustomerPhone string             `json:"customer_phone"`
	Total         pgtype.Numeric     `json:"total"`
	Source        string             `json:"source"`
}

// The business activity feed: what happened in the shop, as opposed to who
// changed its configuration (that is the audit log).
//
// Every row is an order moving through the workflow, joined back to the order
// so the feed can name it without a second query per row.
func (q *Queries) ListTenantActivity(ctx context.Context, arg ListTenantActivityParams) ([]ListTenantActivityRow, error) {
	rows, err := q.db.Query(ctx, listTenantActivity, arg.TenantID, arg.ToStatus, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantActivityRow{}
	for rows.Next() {
		var i ListTenantActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Actor,
			&i.CreatedAt,
			&i.OrderNumber,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Total,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET status = 'FAILED',
    failure_reason = $3,
    attempt_count = attempt_count + 1,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND status <> 'PAID'
RETURNING id, tenant_id, order_id, amount, method, status, provider, provider_reference, paid_at, created_at, updated_at, failure_reason, attempt_count, payable_type, payable_id, purpose
`

type MarkPaymentFailedParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	FailureReason string      `json:"failure_reason"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, arg.ID, arg.TenantID, arg.FailureReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.Provider,
		&i.ProviderReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.AttemptCount,
		&i.PayableType,
		&i.PayableID,
		&i.Purpose,
	)
	return i, err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :one
UPDATE payments
SET status = 'PAID',
    failure_reason = '',
    paid_at = now(),
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND status <> 'PAID'
RETURNING id, tenant_id, order_id, amount, method, status, provider, provider_reference, paid_at, created_at, updated_at, failure_reason, attempt_count, payable_type, payable_id, purpose
`

type MarkPaymentPaidParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Guarded so a late gateway callback can never mark a captured payment unpaid.
func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaid, arg.ID, arg.TenantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.Provider,
		&i.ProviderReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.AttemptCount,
		&i.PayableType,
		&i.PayableID,
		&i.Purpose,
	)
	return i, err
}

const nextOrderNumber = `-- name: NextOrderNumber :one
INSERT INTO order_counters (tenant_id, last_number)
VALUES ($1, 1)
ON CONFLICT (tenant_id) DO UPDATE
SET last_number = order_counters.last_number + 1
RETURNING last_number
`

func (q *Queries) NextOrderNumber(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderNumber, tenantID)
	var last_number int64
	err := row.Scan(&last_number)
	return last_number, err
}

const setPaymentPending = `-- name: SetPaymentPending :one
UPDATE payments
SET status = 'PENDING',
    method = $3,
    provider = $4,
    provider_reference = $5,
    failure_reason = '',
    attempt_count = attempt_count + 1,
    paid_at = NULL,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND status <> 'PAID'
RETURNING id, tenant_id, order_id, amount, method, status, provider, provider_reference, paid_at, created_at, updated_at, failure_reason, attempt_count, payable_type, payable_id, purpose
`

type SetPaymentPendingParams struct {
	ID                pgtype.UUID `json:"id"`
	TenantID          pgtype.UUID `json:"tenant_id"`
	Method            string      `json:"method"`
	Provider          string      `json:"provider"`
	ProviderReference string      `json:"provider_reference"`
}

func (q *Queries) SetPaymentPending(ctx context.Context, arg SetPaymentPendingParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentPending,
		arg.ID,
		arg.TenantID,
		arg.Method,
		arg.Provider,
		arg.ProviderReference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.Provider,
		&i.ProviderReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.AttemptCount,
		&i.PayableType,
		&i.PayableID,
		&i.Purpose,
	)
	return i, err
}

const stampOrderAccepted = `-- name: StampOrderAccepted :one
UPDATE orders
SET status = 'ACCEPTED', accepted_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id
`

type StampOrderAcceptedParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Lifecycle timestamps. Each transition stamps only the column it owns, so the
// tracking timeline can show when the order actually reached each stage.
func (q *Queries) StampOrderAccepted(ctx context.Context, arg StampOrderAcceptedParams) (Order, error) {
	row := q.db.QueryRow(ctx, stampOrderAccepted, arg.ID, arg.TenantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const stampOrderCancelled = `-- name: StampOrderCancelled :one
UPDATE orders
SET status = 'CANCELLED', cancelled_at = now(), cancel_reason = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id
`

type StampOrderCancelledParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	CancelReason string      `json:"cancel_reason"`
}

func (q *Queries) StampOrderCancelled(ctx context.Context, arg StampOrderCancelledParams) (Order, error) {
	row := q.db.QueryRow(ctx, stampOrderCancelled, arg.ID, arg.TenantID, arg.CancelReason)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const stampOrderCompleted = `-- name: StampOrderCompleted :one
UPDATE orders
SET status = 'COMPLETED', completed_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id
`

type StampOrderCompletedParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) StampOrderCompleted(ctx context.Context, arg StampOrderCompletedParams) (Order, error) {
	row := q.db.QueryRow(ctx, stampOrderCompleted, arg.ID, arg.TenantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const stampOrderPreparing = `-- name: StampOrderPreparing :one
UPDATE orders
SET status = 'PREPARING', preparing_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id
`

type StampOrderPreparingParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) StampOrderPreparing(ctx context.Context, arg StampOrderPreparingParams) (Order, error) {
	row := q.db.QueryRow(ctx, stampOrderPreparing, arg.ID, arg.TenantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const stampOrderReady = `-- name: StampOrderReady :one
UPDATE orders
SET status = 'READY', ready_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id
`

type StampOrderReadyParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) StampOrderReady(ctx context.Context, arg StampOrderReadyParams) (Order, error) {
	row := q.db.QueryRow(ctx, stampOrderReady, arg.ID, arg.TenantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}

const summarizeOrderHistory = `-- name: SummarizeOrderHistory :one
SELECT
    COUNT(*)::bigint AS total_orders,
    COALESCE(SUM(CASE WHEN o.status <> 'CANCELLED' THEN o.total ELSE 0 END), 0)::text AS total_revenue,
    COUNT(*) FILTER (WHERE o.status = 'COMPLETED')::bigint AS completed,
    COUNT(*) FILTER (WHERE o.status = 'CANCELLED')::bigint AS cancelled
FROM orders o
WHERE o.tenant_id = $1
  AND ($2::text IS NULL OR o.status = $2::text)
  AND ($3::text IS NULL OR o.source = $3::text)
  AND ($4::timestamptz IS NULL OR o.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR o.created_at < $5::timestamptz)
  AND (
        $6::text IS NULL
        OR o.customer_name ILIKE '%' || $6::text || '%'
        OR o.customer_phone ILIKE '%' || $6::text || '%'
        OR o.order_number::text = $6::text
      )
`

type SummarizeOrderHistoryParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Status   pgtype.Text        `json:"status"`
	Source   pgtype.Text        `json:"source"`
	FromDate pgtype.Timestamptz `json:"from_date"`
	ToDate   pgtype.Timestamptz `json:"to_date"`
	Search   pgtype.Text        `json:"search"`
}

type SummarizeOrderHistoryRow struct {
	TotalOrders  int64  `json:"total_orders"`
	TotalRevenue string `json:"total_revenue"`
	Completed    int64  `json:"completed"`
	Cancelled    int64  `json:"cancelled"`
}

// The totals that go with a filtered history page: how many rows match, and
// what they are worth. Counting in SQL keeps the pager honest when the page
// itself is only twenty rows.
func (q *Queries) SummarizeOrderHistory(ctx context.Context, arg SummarizeOrderHistoryParams) (SummarizeOrderHistoryRow, error) {
	row := q.db.QueryRow(ctx, summarizeOrderHistory,
		arg.TenantID,
		arg.Status,
		arg.Source,
		arg.FromDate,
		arg.ToDate,
		arg.Search,
	)
	var i SummarizeOrderHistoryRow
	err := row.Scan(
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.Completed,
		&i.Cancelled,
	)
	return i, err
}

const tenantDashboardStats = `-- name: TenantDashboardStats :one
SELECT
    (SELECT COUNT(*)::bigint FROM orders o WHERE o.tenant_id = $1 AND o.created_at >= date_trunc('day', now())) AS orders_today,
    COALESCE((SELECT SUM(o.total) FROM orders o WHERE o.tenant_id = $1 AND o.created_at >= date_trunc('day', now()) AND o.status = 'COMPLETED'), 0)::text AS revenue_today,
    (SELECT COUNT(*)::bigint FROM orders o WHERE o.tenant_id = $1 AND o.status = 'PENDING') AS pending_orders,
    (SELECT COUNT(*)::bigint FROM orders o WHERE o.tenant_id = $1 AND o.status = 'PREPARING') AS preparing_orders,
    (SELECT COUNT(*)::bigint FROM orders o WHERE o.tenant_id = $1 AND o.status = 'READY') AS ready_orders,
    (SELECT COUNT(*)::bigint FROM orders o WHERE o.tenant_id = $1 AND o.status = 'COMPLETED' AND o.created_at >= date_trunc('day', now())) AS completed_today
`

type TenantDashboardStatsRow struct {
	OrdersToday     int64  `json:"orders_today"`
	RevenueToday    string `json:"revenue_today"`
	PendingOrders   int64  `json:"pending_orders"`
	PreparingOrders int64  `json:"preparing_orders"`
	ReadyOrders     int64  `json:"ready_orders"`
	CompletedToday  int64  `json:"completed_today"`
}

func (q *Queries) TenantDashboardStats(ctx context.Context, tenantID pgtype.UUID) (TenantDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, tenantDashboardStats, tenantID)
	var i TenantDashboardStatsRow
	err := row.Scan(
		&i.OrdersToday,
		&i.RevenueToday,
		&i.PendingOrders,
		&i.PreparingOrders,
		&i.ReadyOrders,
		&i.CompletedToday,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, order_number, status, order_type, subtotal, tax, discount, total, customer_name, customer_phone, created_at, updated_at, customer_email, notes, estimated_ready_at, accepted_at, preparing_at, ready_at, completed_at, cancelled_at, cancel_reason, source, client_token, packaging_fee, table_id
`

type UpdateOrderStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.TenantID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.OrderType,
		&i.Subtotal,
		&i.Tax,
		&i.Discount,
		&i.Total,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.Notes,
		&i.EstimatedReadyAt,
		&i.AcceptedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.ClientToken,
		&i.PackagingFee,
		&i.TableID,
	)
	return i, err
}
