// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenantsOnPlan = `-- name: CountTenantsOnPlan :one
SELECT COUNT(*)::bigint
FROM tenants
WHERE plan_id = $1
`

func (q *Queries) CountTenantsOnPlan(ctx context.Context, planID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantsOnPlan, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (name, description, price, max_staff, max_products, features, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, price, max_staff, max_products, features, is_active, created_at, updated_at
`

type CreatePlanParams struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	MaxStaff    int32          `json:"max_staff"`
	MaxProducts int32          `json:"max_products"`
	Features    []byte         `json:"features"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.MaxStaff,
		arg.MaxProducts,
		arg.Features,
		arg.IsActive,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.MaxStaff,
		&i.MaxProducts,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (tenant_id, plan_id, status, start_at, end_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, plan_id, status, start_at, end_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	PlanID   pgtype.UUID        `json:"plan_id"`
	Status   string             `json:"status"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.TenantID,
		arg.PlanID,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, description, price, max_staff, max_products, features, is_active, created_at, updated_at FROM plans
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.MaxStaff,
		&i.MaxProducts,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, description, price, max_staff, max_products, features, is_active, created_at, updated_at FROM plans
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.MaxStaff,
		&i.MaxProducts,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByNameAny = `-- name: GetPlanByNameAny :one
SELECT id, name, description, price, max_staff, max_products, features, is_active, created_at, updated_at FROM plans
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetPlanByNameAny(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByNameAny, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.MaxStaff,
		&i.MaxProducts,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByTenant = `-- name: GetSubscriptionByTenant :one
SELECT id, tenant_id, plan_id, status, start_at, end_at, created_at, updated_at FROM subscriptions
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSubscriptionByTenant(ctx context.Context, tenantID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByTenant, tenantID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT id, name, description, price, max_staff, max_products, features, is_active, created_at, updated_at FROM plans
ORDER BY price ASC, name ASC
`

func (q *Queries) ListAllPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.MaxStaff,
			&i.MaxProducts,
			&i.Features,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, description, price, max_staff, max_products, features, is_active, created_at, updated_at FROM plans
WHERE is_active = TRUE
ORDER BY price ASC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.MaxStaff,
			&i.MaxProducts,
			&i.Features,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansWithUsage = `-- name: ListPlansWithUsage :many
SELECT
    p.id, p.name, p.description, p.price, p.max_staff, p.max_products, p.features, p.is_active, p.created_at, p.updated_at,
    (SELECT COUNT(*) FROM tenants t WHERE t.plan_id = p.id)::bigint AS tenant_count,
    (SELECT COUNT(*) FROM subscriptions s WHERE s.plan_id = p.id AND s.status IN ('TRIAL', 'ACTIVE'))::bigint AS active_subscriptions
FROM plans p
ORDER BY p.price ASC, p.name ASC
`

type ListPlansWithUsageRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	Price               pgtype.Numeric     `json:"price"`
	MaxStaff            int32              `json:"max_staff"`
	MaxProducts         int32              `json:"max_products"`
	Features            []byte             `json:"features"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TenantCount         int64              `json:"tenant_count"`
	ActiveSubscriptions int64              `json:"active_subscriptions"`
}

// Every plan with the number of tenants provisioned on it, so the console can
// warn before deactivating one that businesses are still using.
func (q *Queries) ListPlansWithUsage(ctx context.Context) ([]ListPlansWithUsageRow, error) {
	rows, err := q.db.Query(ctx, listPlansWithUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlansWithUsageRow{}
	for rows.Next() {
		var i ListPlansWithUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.MaxStaff,
			&i.MaxProducts,
			&i.Features,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantCount,
			&i.ActiveSubscriptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    price = COALESCE($3, price),
    max_staff = COALESCE($4, max_staff),
    max_products = COALESCE($5, max_products),
    -- features carries the commercial terms the plans table has no column for:
    -- billing period, trial length, the feature list and which business types
    -- the plan is offered to. NULL leaves the stored document untouched.
    features = COALESCE($6::jsonb, features),
    is_active = COALESCE($7, is_active),
    updated_at = now()
WHERE id = $8
RETURNING id, name, description, price, max_staff, max_products, features, is_active, created_at, updated_at
`

type UpdatePlanParams struct {
	Name        pgtype.Text    `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	MaxStaff    pgtype.Int4    `json:"max_staff"`
	MaxProducts pgtype.Int4    `json:"max_products"`
	Features    []byte         `json:"features"`
	IsActive    pgtype.Bool    `json:"is_active"`
	ID          pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.MaxStaff,
		arg.MaxProducts,
		arg.Features,
		arg.IsActive,
		arg.ID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.MaxStaff,
		&i.MaxProducts,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :one
UPDATE subscriptions
SET plan_id = $2, status = $3, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, plan_id, status, start_at, end_at, created_at, updated_at
`

type UpdateSubscriptionPlanParams struct {
	ID     pgtype.UUID `json:"id"`
	PlanID pgtype.UUID `json:"plan_id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPlan, arg.ID, arg.PlanID, arg.Status)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
