// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: platform_settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformSettings = `-- name: GetPlatformSettings :one
SELECT config, updated_at FROM platform_settings WHERE id = 1
`

type GetPlatformSettingsRow struct {
	Config    []byte             `json:"config"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPlatformSettings(ctx context.Context) (GetPlatformSettingsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformSettings)
	var i GetPlatformSettingsRow
	err := row.Scan(&i.Config, &i.UpdatedAt)
	return i, err
}

const upsertPlatformSettings = `-- name: UpsertPlatformSettings :one
INSERT INTO platform_settings (id, config)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE
SET config = EXCLUDED.config, updated_at = now()
RETURNING config, updated_at
`

type UpsertPlatformSettingsRow struct {
	Config    []byte             `json:"config"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPlatformSettings(ctx context.Context, config []byte) (UpsertPlatformSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertPlatformSettings, config)
	var i UpsertPlatformSettingsRow
	err := row.Scan(&i.Config, &i.UpdatedAt)
	return i, err
}
