// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: service_configs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlatformTenantsUsingService = `-- name: CountPlatformTenantsUsingService :one
SELECT COUNT(*)::bigint
FROM tenant_service_preferences
WHERE service_type = $1
  AND source = 'PLATFORM'
`

func (q *Queries) CountPlatformTenantsUsingService(ctx context.Context, serviceType string) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformTenantsUsingService, serviceType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePlatformConfiguration = `-- name: DeletePlatformConfiguration :exec
DELETE FROM platform_configurations
WHERE service_type = $1
`

func (q *Queries) DeletePlatformConfiguration(ctx context.Context, serviceType string) error {
	_, err := q.db.Exec(ctx, deletePlatformConfiguration, serviceType)
	return err
}

const deleteTenantConfiguration = `-- name: DeleteTenantConfiguration :exec
DELETE FROM tenant_configurations
WHERE tenant_id = $1
  AND service_type = $2
`

type DeleteTenantConfigurationParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ServiceType string      `json:"service_type"`
}

func (q *Queries) DeleteTenantConfiguration(ctx context.Context, arg DeleteTenantConfigurationParams) error {
	_, err := q.db.Exec(ctx, deleteTenantConfiguration, arg.TenantID, arg.ServiceType)
	return err
}

const getPlatformConfiguration = `-- name: GetPlatformConfiguration :one

SELECT id, service_type, provider, config, secret_config, status, enabled, allow_tenants, last_error, last_tested_at, created_at, updated_at FROM platform_configurations
WHERE service_type = $1
LIMIT 1
`

// Platform-wide provider configuration, one row per service.
func (q *Queries) GetPlatformConfiguration(ctx context.Context, serviceType string) (PlatformConfiguration, error) {
	row := q.db.QueryRow(ctx, getPlatformConfiguration, serviceType)
	var i PlatformConfiguration
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.Provider,
		&i.Config,
		&i.SecretConfig,
		&i.Status,
		&i.Enabled,
		&i.AllowTenants,
		&i.LastError,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantConfiguration = `-- name: GetTenantConfiguration :one

SELECT id, tenant_id, service_type, provider, config, secret_config, status, enabled, last_error, last_tested_at, created_at, updated_at FROM tenant_configurations
WHERE tenant_id = $1
  AND service_type = $2
LIMIT 1
`

type GetTenantConfigurationParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ServiceType string      `json:"service_type"`
}

// Per-tenant configuration.
func (q *Queries) GetTenantConfiguration(ctx context.Context, arg GetTenantConfigurationParams) (TenantConfiguration, error) {
	row := q.db.QueryRow(ctx, getTenantConfiguration, arg.TenantID, arg.ServiceType)
	var i TenantConfiguration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ServiceType,
		&i.Provider,
		&i.Config,
		&i.SecretConfig,
		&i.Status,
		&i.Enabled,
		&i.LastError,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantServiceAccess = `-- name: GetTenantServiceAccess :one

SELECT tenant_id, service_type, allow_platform, updated_at FROM tenant_service_access
WHERE tenant_id = $1
  AND service_type = $2
LIMIT 1
`

type GetTenantServiceAccessParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ServiceType string      `json:"service_type"`
}

// Per-tenant permission to borrow the platform configuration.
func (q *Queries) GetTenantServiceAccess(ctx context.Context, arg GetTenantServiceAccessParams) (TenantServiceAccess, error) {
	row := q.db.QueryRow(ctx, getTenantServiceAccess, arg.TenantID, arg.ServiceType)
	var i TenantServiceAccess
	err := row.Scan(
		&i.TenantID,
		&i.ServiceType,
		&i.AllowPlatform,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantServicePreference = `-- name: GetTenantServicePreference :one

SELECT tenant_id, service_type, source, updated_at FROM tenant_service_preferences
WHERE tenant_id = $1
  AND service_type = $2
LIMIT 1
`

type GetTenantServicePreferenceParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ServiceType string      `json:"service_type"`
}

// Source preference.
func (q *Queries) GetTenantServicePreference(ctx context.Context, arg GetTenantServicePreferenceParams) (TenantServicePreference, error) {
	row := q.db.QueryRow(ctx, getTenantServicePreference, arg.TenantID, arg.ServiceType)
	var i TenantServicePreference
	err := row.Scan(
		&i.TenantID,
		&i.ServiceType,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlatformConfigurations = `-- name: ListPlatformConfigurations :many
SELECT id, service_type, provider, config, secret_config, status, enabled, allow_tenants, last_error, last_tested_at, created_at, updated_at FROM platform_configurations
ORDER BY service_type ASC
`

func (q *Queries) ListPlatformConfigurations(ctx context.Context) ([]PlatformConfiguration, error) {
	rows, err := q.db.Query(ctx, listPlatformConfigurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformConfiguration{}
	for rows.Next() {
		var i PlatformConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.ServiceType,
			&i.Provider,
			&i.Config,
			&i.SecretConfig,
			&i.Status,
			&i.Enabled,
			&i.AllowTenants,
			&i.LastError,
			&i.LastTestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceAccessForAllTenants = `-- name: ListServiceAccessForAllTenants :many
SELECT
    t.id AS tenant_id,
    t.name AS tenant_name,
    t.slug AS tenant_slug,
    sv.service_type::text AS service_type,
    COALESCE(a.allow_platform, FALSE) AS allow_platform,
    p.source,
    tc.status  AS own_status,
    tc.enabled AS own_enabled,
    pc.status  AS platform_status,
    pc.enabled AS platform_enabled,
    pc.allow_tenants AS platform_allow_tenants
FROM tenants t
CROSS JOIN (VALUES ('SMTP'), ('STORAGE'), ('AI')) AS sv(service_type)
LEFT JOIN tenant_service_access a
       ON a.tenant_id = t.id AND a.service_type = sv.service_type
LEFT JOIN tenant_service_preferences p
       ON p.tenant_id = t.id AND p.service_type = sv.service_type
LEFT JOIN tenant_configurations tc
       ON tc.tenant_id = t.id AND tc.service_type = sv.service_type
LEFT JOIN platform_configurations pc
       ON pc.service_type = sv.service_type
ORDER BY t.name ASC
`

type ListServiceAccessForAllTenantsRow struct {
	TenantID             pgtype.UUID `json:"tenant_id"`
	TenantName           string      `json:"tenant_name"`
	TenantSlug           string      `json:"tenant_slug"`
	ServiceType          string      `json:"service_type"`
	AllowPlatform        bool        `json:"allow_platform"`
	Source               pgtype.Text `json:"source"`
	OwnStatus            pgtype.Text `json:"own_status"`
	OwnEnabled           pgtype.Bool `json:"own_enabled"`
	PlatformStatus       pgtype.Text `json:"platform_status"`
	PlatformEnabled      pgtype.Bool `json:"platform_enabled"`
	PlatformAllowTenants pgtype.Bool `json:"platform_allow_tenants"`
}

// Ensures every (tenant, service) pair appears, even when unset, so the Super
// Admin table can render a complete grid.
// Service ordering is applied in Go: sqlc cannot resolve a VALUES alias in ORDER BY.
func (q *Queries) ListServiceAccessForAllTenants(ctx context.Context) ([]ListServiceAccessForAllTenantsRow, error) {
	rows, err := q.db.Query(ctx, listServiceAccessForAllTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceAccessForAllTenantsRow{}
	for rows.Next() {
		var i ListServiceAccessForAllTenantsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.TenantSlug,
			&i.ServiceType,
			&i.AllowPlatform,
			&i.Source,
			&i.OwnStatus,
			&i.OwnEnabled,
			&i.PlatformStatus,
			&i.PlatformEnabled,
			&i.PlatformAllowTenants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantConfigurations = `-- name: ListTenantConfigurations :many
SELECT id, tenant_id, service_type, provider, config, secret_config, status, enabled, last_error, last_tested_at, created_at, updated_at FROM tenant_configurations
WHERE tenant_id = $1
ORDER BY service_type ASC
`

func (q *Queries) ListTenantConfigurations(ctx context.Context, tenantID pgtype.UUID) ([]TenantConfiguration, error) {
	rows, err := q.db.Query(ctx, listTenantConfigurations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantConfiguration{}
	for rows.Next() {
		var i TenantConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ServiceType,
			&i.Provider,
			&i.Config,
			&i.SecretConfig,
			&i.Status,
			&i.Enabled,
			&i.LastError,
			&i.LastTestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantServiceAccess = `-- name: ListTenantServiceAccess :many
SELECT tenant_id, service_type, allow_platform, updated_at FROM tenant_service_access
WHERE tenant_id = $1
ORDER BY service_type ASC
`

func (q *Queries) ListTenantServiceAccess(ctx context.Context, tenantID pgtype.UUID) ([]TenantServiceAccess, error) {
	rows, err := q.db.Query(ctx, listTenantServiceAccess, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantServiceAccess{}
	for rows.Next() {
		var i TenantServiceAccess
		if err := rows.Scan(
			&i.TenantID,
			&i.ServiceType,
			&i.AllowPlatform,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantServicePreferences = `-- name: ListTenantServicePreferences :many
SELECT tenant_id, service_type, source, updated_at FROM tenant_service_preferences
WHERE tenant_id = $1
ORDER BY service_type ASC
`

func (q *Queries) ListTenantServicePreferences(ctx context.Context, tenantID pgtype.UUID) ([]TenantServicePreference, error) {
	rows, err := q.db.Query(ctx, listTenantServicePreferences, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantServicePreference{}
	for rows.Next() {
		var i TenantServicePreference
		if err := rows.Scan(
			&i.TenantID,
			&i.ServiceType,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlatformConfigurationAllowTenants = `-- name: SetPlatformConfigurationAllowTenants :one
UPDATE platform_configurations
SET allow_tenants = $1, updated_at = now()
WHERE service_type = $2
RETURNING id, service_type, provider, config, secret_config, status, enabled, allow_tenants, last_error, last_tested_at, created_at, updated_at
`

type SetPlatformConfigurationAllowTenantsParams struct {
	AllowTenants bool   `json:"allow_tenants"`
	ServiceType  string `json:"service_type"`
}

func (q *Queries) SetPlatformConfigurationAllowTenants(ctx context.Context, arg SetPlatformConfigurationAllowTenantsParams) (PlatformConfiguration, error) {
	row := q.db.QueryRow(ctx, setPlatformConfigurationAllowTenants, arg.AllowTenants, arg.ServiceType)
	var i PlatformConfiguration
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.Provider,
		&i.Config,
		&i.SecretConfig,
		&i.Status,
		&i.Enabled,
		&i.AllowTenants,
		&i.LastError,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPlatformConfigurationStatus = `-- name: SetPlatformConfigurationStatus :one
UPDATE platform_configurations
SET
    status        = $1,
    last_error    = $2,
    last_tested_at = now(),
    updated_at    = now()
WHERE service_type = $3
RETURNING id, service_type, provider, config, secret_config, status, enabled, allow_tenants, last_error, last_tested_at, created_at, updated_at
`

type SetPlatformConfigurationStatusParams struct {
	Status      string `json:"status"`
	LastError   string `json:"last_error"`
	ServiceType string `json:"service_type"`
}

// Records the outcome of a connection test without touching credentials.
func (q *Queries) SetPlatformConfigurationStatus(ctx context.Context, arg SetPlatformConfigurationStatusParams) (PlatformConfiguration, error) {
	row := q.db.QueryRow(ctx, setPlatformConfigurationStatus, arg.Status, arg.LastError, arg.ServiceType)
	var i PlatformConfiguration
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.Provider,
		&i.Config,
		&i.SecretConfig,
		&i.Status,
		&i.Enabled,
		&i.AllowTenants,
		&i.LastError,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTenantConfigurationStatus = `-- name: SetTenantConfigurationStatus :one
UPDATE tenant_configurations
SET
    status        = $1,
    last_error    = $2,
    last_tested_at = now(),
    updated_at    = now()
WHERE tenant_id = $3
  AND service_type = $4
RETURNING id, tenant_id, service_type, provider, config, secret_config, status, enabled, last_error, last_tested_at, created_at, updated_at
`

type SetTenantConfigurationStatusParams struct {
	Status      string      `json:"status"`
	LastError   string      `json:"last_error"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	ServiceType string      `json:"service_type"`
}

func (q *Queries) SetTenantConfigurationStatus(ctx context.Context, arg SetTenantConfigurationStatusParams) (TenantConfiguration, error) {
	row := q.db.QueryRow(ctx, setTenantConfigurationStatus,
		arg.Status,
		arg.LastError,
		arg.TenantID,
		arg.ServiceType,
	)
	var i TenantConfiguration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ServiceType,
		&i.Provider,
		&i.Config,
		&i.SecretConfig,
		&i.Status,
		&i.Enabled,
		&i.LastError,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlatformConfiguration = `-- name: UpsertPlatformConfiguration :one
INSERT INTO platform_configurations (
    service_type, provider, config, secret_config, status,
    enabled, allow_tenants, last_error, last_tested_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9
)
ON CONFLICT (service_type) DO UPDATE SET
    provider      = EXCLUDED.provider,
    config        = EXCLUDED.config,
    secret_config = EXCLUDED.secret_config,
    status        = EXCLUDED.status,
    enabled       = EXCLUDED.enabled,
    allow_tenants = EXCLUDED.allow_tenants,
    last_error    = EXCLUDED.last_error,
    last_tested_at = EXCLUDED.last_tested_at,
    updated_at    = now()
RETURNING id, service_type, provider, config, secret_config, status, enabled, allow_tenants, last_error, last_tested_at, created_at, updated_at
`

type UpsertPlatformConfigurationParams struct {
	ServiceType  string             `json:"service_type"`
	Provider     string             `json:"provider"`
	Config       []byte             `json:"config"`
	SecretConfig []byte             `json:"secret_config"`
	Status       string             `json:"status"`
	Enabled      bool               `json:"enabled"`
	AllowTenants bool               `json:"allow_tenants"`
	LastError    string             `json:"last_error"`
	LastTestedAt pgtype.Timestamptz `json:"last_tested_at"`
}

func (q *Queries) UpsertPlatformConfiguration(ctx context.Context, arg UpsertPlatformConfigurationParams) (PlatformConfiguration, error) {
	row := q.db.QueryRow(ctx, upsertPlatformConfiguration,
		arg.ServiceType,
		arg.Provider,
		arg.Config,
		arg.SecretConfig,
		arg.Status,
		arg.Enabled,
		arg.AllowTenants,
		arg.LastError,
		arg.LastTestedAt,
	)
	var i PlatformConfiguration
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.Provider,
		&i.Config,
		&i.SecretConfig,
		&i.Status,
		&i.Enabled,
		&i.AllowTenants,
		&i.LastError,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantConfiguration = `-- name: UpsertTenantConfiguration :one
INSERT INTO tenant_configurations (
    tenant_id, service_type, provider, config, secret_config,
    status, enabled, last_error, last_tested_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9
)
ON CONFLICT (tenant_id, service_type) DO UPDATE SET
    provider      = EXCLUDED.provider,
    config        = EXCLUDED.config,
    secret_config = EXCLUDED.secret_config,
    status        = EXCLUDED.status,
    enabled       = EXCLUDED.enabled,
    last_error    = EXCLUDED.last_error,
    last_tested_at = EXCLUDED.last_tested_at,
    updated_at    = now()
RETURNING id, tenant_id, service_type, provider, config, secret_config, status, enabled, last_error, last_tested_at, created_at, updated_at
`

type UpsertTenantConfigurationParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ServiceType  string             `json:"service_type"`
	Provider     string             `json:"provider"`
	Config       []byte             `json:"config"`
	SecretConfig []byte             `json:"secret_config"`
	Status       string             `json:"status"`
	Enabled      bool               `json:"enabled"`
	LastError    string             `json:"last_error"`
	LastTestedAt pgtype.Timestamptz `json:"last_tested_at"`
}

func (q *Queries) UpsertTenantConfiguration(ctx context.Context, arg UpsertTenantConfigurationParams) (TenantConfiguration, error) {
	row := q.db.QueryRow(ctx, upsertTenantConfiguration,
		arg.TenantID,
		arg.ServiceType,
		arg.Provider,
		arg.Config,
		arg.SecretConfig,
		arg.Status,
		arg.Enabled,
		arg.LastError,
		arg.LastTestedAt,
	)
	var i TenantConfiguration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ServiceType,
		&i.Provider,
		&i.Config,
		&i.SecretConfig,
		&i.Status,
		&i.Enabled,
		&i.LastError,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantServiceAccess = `-- name: UpsertTenantServiceAccess :one
INSERT INTO tenant_service_access (tenant_id, service_type, allow_platform)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, service_type) DO UPDATE SET
    allow_platform = EXCLUDED.allow_platform,
    updated_at    = now()
RETURNING tenant_id, service_type, allow_platform, updated_at
`

type UpsertTenantServiceAccessParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	ServiceType   string      `json:"service_type"`
	AllowPlatform bool        `json:"allow_platform"`
}

func (q *Queries) UpsertTenantServiceAccess(ctx context.Context, arg UpsertTenantServiceAccessParams) (TenantServiceAccess, error) {
	row := q.db.QueryRow(ctx, upsertTenantServiceAccess, arg.TenantID, arg.ServiceType, arg.AllowPlatform)
	var i TenantServiceAccess
	err := row.Scan(
		&i.TenantID,
		&i.ServiceType,
		&i.AllowPlatform,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantServicePreference = `-- name: UpsertTenantServicePreference :one
INSERT INTO tenant_service_preferences (tenant_id, service_type, source)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, service_type) DO UPDATE SET
    source = EXCLUDED.source,
    updated_at = now()
RETURNING tenant_id, service_type, source, updated_at
`

type UpsertTenantServicePreferenceParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ServiceType string      `json:"service_type"`
	Source      string      `json:"source"`
}

func (q *Queries) UpsertTenantServicePreference(ctx context.Context, arg UpsertTenantServicePreferenceParams) (TenantServicePreference, error) {
	row := q.db.QueryRow(ctx, upsertTenantServicePreference, arg.TenantID, arg.ServiceType, arg.Source)
	var i TenantServicePreference
	err := row.Scan(
		&i.TenantID,
		&i.ServiceType,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}
