// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: storefront.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureStorefrontSettings = `-- name: EnsureStorefrontSettings :one
INSERT INTO tenant_storefront_settings (tenant_id, business_name, phone, address, logo_url, favicon_url, tagline)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id) DO UPDATE SET updated_at = now()
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type EnsureStorefrontSettingsParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	BusinessName string      `json:"business_name"`
	Phone        string      `json:"phone"`
	Address      string      `json:"address"`
	LogoUrl      string      `json:"logo_url"`
	FaviconUrl   string      `json:"favicon_url"`
	Tagline      string      `json:"tagline"`
}

func (q *Queries) EnsureStorefrontSettings(ctx context.Context, arg EnsureStorefrontSettingsParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, ensureStorefrontSettings,
		arg.TenantID,
		arg.BusinessName,
		arg.Phone,
		arg.Address,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.Tagline,
	)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const getStorefrontConfig = `-- name: GetStorefrontConfig :one
SELECT
    s.tenant_id,
    t.name              AS tenant_name,
    t.slug,
    t.business_type,
    t.currency,
    t.timezone,
    t.is_published,
    t.store_status,
    t.status_message,
    s.logo_url,
    s.favicon_url,
    s.business_name,
    s.tagline,
    s.description,
    s.phone,
    s.address,
    s.theme_preset,
    s.primary_color,
    s.secondary_color,
    s.accent_color,
    s.theme_mode,
    s.font_family,
    s.radius,
    s.button_style,
    s.card_style,
    s.header_style,
    s.hero_style,
    s.hero_image_url,
    s.product_layout,
    s.filter_style,
    s.ordering_enabled,
    s.closed_message,
    s.customer_login_enabled,
    s.customer_login_mode,
    s.prep_time_minutes,
    s.tax_percent,
    s.packaging_fee,
    s.opening_hours,
    s.homepage,
    s.payments,
    s.workflow,
    s.updated_at
FROM tenant_storefront_settings s
JOIN tenants t ON t.id = s.tenant_id
WHERE s.tenant_id = $1
LIMIT 1
`

type GetStorefrontConfigRow struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	TenantName           string             `json:"tenant_name"`
	Slug                 string             `json:"slug"`
	BusinessType         string             `json:"business_type"`
	Currency             string             `json:"currency"`
	Timezone             string             `json:"timezone"`
	IsPublished          bool               `json:"is_published"`
	StoreStatus          string             `json:"store_status"`
	StatusMessage        string             `json:"status_message"`
	LogoUrl              string             `json:"logo_url"`
	FaviconUrl           string             `json:"favicon_url"`
	BusinessName         string             `json:"business_name"`
	Tagline              string             `json:"tagline"`
	Description          string             `json:"description"`
	Phone                string             `json:"phone"`
	Address              string             `json:"address"`
	ThemePreset          string             `json:"theme_preset"`
	PrimaryColor         string             `json:"primary_color"`
	SecondaryColor       string             `json:"secondary_color"`
	AccentColor          string             `json:"accent_color"`
	ThemeMode            string             `json:"theme_mode"`
	FontFamily           string             `json:"font_family"`
	Radius               string             `json:"radius"`
	ButtonStyle          string             `json:"button_style"`
	CardStyle            string             `json:"card_style"`
	HeaderStyle          string             `json:"header_style"`
	HeroStyle            string             `json:"hero_style"`
	HeroImageUrl         string             `json:"hero_image_url"`
	ProductLayout        string             `json:"product_layout"`
	FilterStyle          string             `json:"filter_style"`
	OrderingEnabled      bool               `json:"ordering_enabled"`
	ClosedMessage        string             `json:"closed_message"`
	CustomerLoginEnabled bool               `json:"customer_login_enabled"`
	CustomerLoginMode    string             `json:"customer_login_mode"`
	PrepTimeMinutes      int32              `json:"prep_time_minutes"`
	TaxPercent           pgtype.Numeric     `json:"tax_percent"`
	PackagingFee         pgtype.Numeric     `json:"packaging_fee"`
	OpeningHours         []byte             `json:"opening_hours"`
	Homepage             []byte             `json:"homepage"`
	Payments             []byte             `json:"payments"`
	Workflow             []byte             `json:"workflow"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// Full storefront row joined with the tenant, so identity fallbacks (name,
// phone, address, logo) can be read without a second round trip.
func (q *Queries) GetStorefrontConfig(ctx context.Context, tenantID pgtype.UUID) (GetStorefrontConfigRow, error) {
	row := q.db.QueryRow(ctx, getStorefrontConfig, tenantID)
	var i GetStorefrontConfigRow
	err := row.Scan(
		&i.TenantID,
		&i.TenantName,
		&i.Slug,
		&i.BusinessType,
		&i.Currency,
		&i.Timezone,
		&i.IsPublished,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.CustomerLoginMode,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorefrontSettings = `-- name: GetStorefrontSettings :one
SELECT tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode FROM tenant_storefront_settings
WHERE tenant_id = $1
LIMIT 1
`

func (q *Queries) GetStorefrontSettings(ctx context.Context, tenantID pgtype.UUID) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, getStorefrontSettings, tenantID)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const setStorefrontPublished = `-- name: SetStorefrontPublished :one
UPDATE tenants
SET is_published = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, shop_type, status_message
`

type SetStorefrontPublishedParams struct {
	IsPublished bool        `json:"is_published"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) SetStorefrontPublished(ctx context.Context, arg SetStorefrontPublishedParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setStorefrontPublished, arg.IsPublished, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.ShopType,
		&i.StatusMessage,
	)
	return i, err
}

const updateStorefrontBehaviour = `-- name: UpdateStorefrontBehaviour :one
UPDATE tenant_storefront_settings
SET
    ordering_enabled       = COALESCE($1, ordering_enabled),
    closed_message         = COALESCE($2, closed_message),
    customer_login_mode    = COALESCE($3, customer_login_mode),
    prep_time_minutes      = COALESCE($4, prep_time_minutes),
    updated_at             = now()
WHERE tenant_id = $5
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type UpdateStorefrontBehaviourParams struct {
	OrderingEnabled   pgtype.Bool `json:"ordering_enabled"`
	ClosedMessage     pgtype.Text `json:"closed_message"`
	CustomerLoginMode pgtype.Text `json:"customer_login_mode"`
	PrepTimeMinutes   pgtype.Int4 `json:"prep_time_minutes"`
	TenantID          pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateStorefrontBehaviour(ctx context.Context, arg UpdateStorefrontBehaviourParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, updateStorefrontBehaviour,
		arg.OrderingEnabled,
		arg.ClosedMessage,
		arg.CustomerLoginMode,
		arg.PrepTimeMinutes,
		arg.TenantID,
	)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const updateStorefrontCosting = `-- name: UpdateStorefrontCosting :one
UPDATE tenant_storefront_settings
SET tax_percent = $1, packaging_fee = $2, updated_at = now()
WHERE tenant_id = $3
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type UpdateStorefrontCostingParams struct {
	TaxPercent   pgtype.Numeric `json:"tax_percent"`
	PackagingFee pgtype.Numeric `json:"packaging_fee"`
	TenantID     pgtype.UUID    `json:"tenant_id"`
}

func (q *Queries) UpdateStorefrontCosting(ctx context.Context, arg UpdateStorefrontCostingParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, updateStorefrontCosting, arg.TaxPercent, arg.PackagingFee, arg.TenantID)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const updateStorefrontHomepage = `-- name: UpdateStorefrontHomepage :one
UPDATE tenant_storefront_settings
SET homepage = $1::jsonb, updated_at = now()
WHERE tenant_id = $2
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type UpdateStorefrontHomepageParams struct {
	Homepage []byte      `json:"homepage"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateStorefrontHomepage(ctx context.Context, arg UpdateStorefrontHomepageParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, updateStorefrontHomepage, arg.Homepage, arg.TenantID)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const updateStorefrontIdentity = `-- name: UpdateStorefrontIdentity :one
UPDATE tenant_storefront_settings
SET
    logo_url      = COALESCE($1, logo_url),
    favicon_url   = COALESCE($2, favicon_url),
    business_name = COALESCE($3, business_name),
    tagline       = COALESCE($4, tagline),
    description   = COALESCE($5, description),
    phone         = COALESCE($6, phone),
    address       = COALESCE($7, address),
    updated_at    = now()
WHERE tenant_id = $8
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type UpdateStorefrontIdentityParams struct {
	LogoUrl      pgtype.Text `json:"logo_url"`
	FaviconUrl   pgtype.Text `json:"favicon_url"`
	BusinessName pgtype.Text `json:"business_name"`
	Tagline      pgtype.Text `json:"tagline"`
	Description  pgtype.Text `json:"description"`
	Phone        pgtype.Text `json:"phone"`
	Address      pgtype.Text `json:"address"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateStorefrontIdentity(ctx context.Context, arg UpdateStorefrontIdentityParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, updateStorefrontIdentity,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.BusinessName,
		arg.Tagline,
		arg.Description,
		arg.Phone,
		arg.Address,
		arg.TenantID,
	)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const updateStorefrontOpeningHours = `-- name: UpdateStorefrontOpeningHours :one
UPDATE tenant_storefront_settings
SET opening_hours = $1::jsonb, updated_at = now()
WHERE tenant_id = $2
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type UpdateStorefrontOpeningHoursParams struct {
	OpeningHours []byte      `json:"opening_hours"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateStorefrontOpeningHours(ctx context.Context, arg UpdateStorefrontOpeningHoursParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, updateStorefrontOpeningHours, arg.OpeningHours, arg.TenantID)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const updateStorefrontPayments = `-- name: UpdateStorefrontPayments :one
UPDATE tenant_storefront_settings
SET payments = $1::jsonb, updated_at = now()
WHERE tenant_id = $2
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type UpdateStorefrontPaymentsParams struct {
	Payments []byte      `json:"payments"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateStorefrontPayments(ctx context.Context, arg UpdateStorefrontPaymentsParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, updateStorefrontPayments, arg.Payments, arg.TenantID)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const updateStorefrontTheme = `-- name: UpdateStorefrontTheme :one
UPDATE tenant_storefront_settings
SET
    theme_preset    = COALESCE($1, theme_preset),
    primary_color   = COALESCE($2, primary_color),
    secondary_color = COALESCE($3, secondary_color),
    accent_color    = COALESCE($4, accent_color),
    theme_mode      = COALESCE($5, theme_mode),
    font_family     = COALESCE($6, font_family),
    radius          = COALESCE($7, radius),
    button_style    = COALESCE($8, button_style),
    card_style      = COALESCE($9, card_style),
    header_style    = COALESCE($10, header_style),
    hero_style      = COALESCE($11, hero_style),
    hero_image_url  = COALESCE($12, hero_image_url),
    product_layout  = COALESCE($13, product_layout),
    filter_style    = COALESCE($14, filter_style),
    updated_at      = now()
WHERE tenant_id = $15
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type UpdateStorefrontThemeParams struct {
	ThemePreset    pgtype.Text `json:"theme_preset"`
	PrimaryColor   pgtype.Text `json:"primary_color"`
	SecondaryColor pgtype.Text `json:"secondary_color"`
	AccentColor    pgtype.Text `json:"accent_color"`
	ThemeMode      pgtype.Text `json:"theme_mode"`
	FontFamily     pgtype.Text `json:"font_family"`
	Radius         pgtype.Text `json:"radius"`
	ButtonStyle    pgtype.Text `json:"button_style"`
	CardStyle      pgtype.Text `json:"card_style"`
	HeaderStyle    pgtype.Text `json:"header_style"`
	HeroStyle      pgtype.Text `json:"hero_style"`
	HeroImageUrl   pgtype.Text `json:"hero_image_url"`
	ProductLayout  pgtype.Text `json:"product_layout"`
	FilterStyle    pgtype.Text `json:"filter_style"`
	TenantID       pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateStorefrontTheme(ctx context.Context, arg UpdateStorefrontThemeParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, updateStorefrontTheme,
		arg.ThemePreset,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.AccentColor,
		arg.ThemeMode,
		arg.FontFamily,
		arg.Radius,
		arg.ButtonStyle,
		arg.CardStyle,
		arg.HeaderStyle,
		arg.HeroStyle,
		arg.HeroImageUrl,
		arg.ProductLayout,
		arg.FilterStyle,
		arg.TenantID,
	)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}

const updateStorefrontWorkflow = `-- name: UpdateStorefrontWorkflow :one
UPDATE tenant_storefront_settings
SET workflow = $1::jsonb, updated_at = now()
WHERE tenant_id = $2
RETURNING tenant_id, logo_url, favicon_url, business_name, tagline, description, phone, address, theme_preset, primary_color, secondary_color, accent_color, theme_mode, font_family, radius, button_style, card_style, header_style, hero_style, hero_image_url, ordering_enabled, closed_message, customer_login_enabled, prep_time_minutes, tax_percent, packaging_fee, opening_hours, homepage, payments, workflow, created_at, updated_at, product_layout, filter_style, customer_login_mode
`

type UpdateStorefrontWorkflowParams struct {
	Workflow []byte      `json:"workflow"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateStorefrontWorkflow(ctx context.Context, arg UpdateStorefrontWorkflowParams) (TenantStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, updateStorefrontWorkflow, arg.Workflow, arg.TenantID)
	var i TenantStorefrontSetting
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BusinessName,
		&i.Tagline,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.ThemePreset,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.ThemeMode,
		&i.FontFamily,
		&i.Radius,
		&i.ButtonStyle,
		&i.CardStyle,
		&i.HeaderStyle,
		&i.HeroStyle,
		&i.HeroImageUrl,
		&i.OrderingEnabled,
		&i.ClosedMessage,
		&i.CustomerLoginEnabled,
		&i.PrepTimeMinutes,
		&i.TaxPercent,
		&i.PackagingFee,
		&i.OpeningHours,
		&i.Homepage,
		&i.Payments,
		&i.Workflow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductLayout,
		&i.FilterStyle,
		&i.CustomerLoginMode,
	)
	return i, err
}
