// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tables.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTable = `-- name: CreateTable :one

INSERT INTO tables (tenant_id, label, seats, status)
VALUES ($1, $2, $3, 'AVAILABLE')
RETURNING id, tenant_id, label, seats, status, created_at
`

type CreateTableParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Label    string      `json:"label"`
	Seats    int32       `json:"seats"`
}

// Cafe/Restaurant dine-in tables.
func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, createTable, arg.TenantID, arg.Label, arg.Seats)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTable = `-- name: DeleteTable :exec
DELETE FROM tables WHERE id = $1 AND tenant_id = $2
`

type DeleteTableParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTable(ctx context.Context, arg DeleteTableParams) error {
	_, err := q.db.Exec(ctx, deleteTable, arg.ID, arg.TenantID)
	return err
}

const getTableByID = `-- name: GetTableByID :one
SELECT id, tenant_id, label, seats, status, created_at FROM tables WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetTableByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetTableByID(ctx context.Context, arg GetTableByIDParams) (Table, error) {
	row := q.db.QueryRow(ctx, getTableByID, arg.ID, arg.TenantID)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTablesByTenant = `-- name: ListTablesByTenant :many
SELECT id, tenant_id, label, seats, status, created_at FROM tables WHERE tenant_id = $1 ORDER BY label ASC
`

func (q *Queries) ListTablesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Table, error) {
	rows, err := q.db.Query(ctx, listTablesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Label,
			&i.Seats,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTable = `-- name: UpdateTable :one
UPDATE tables SET
    label = COALESCE($1, label),
    seats = COALESCE($2, seats)
WHERE id = $3 AND tenant_id = $4
RETURNING id, tenant_id, label, seats, status, created_at
`

type UpdateTableParams struct {
	Label    pgtype.Text `json:"label"`
	Seats    pgtype.Int4 `json:"seats"`
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, updateTable,
		arg.Label,
		arg.Seats,
		arg.ID,
		arg.TenantID,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateTableStatus = `-- name: UpdateTableStatus :one
UPDATE tables SET status = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, label, seats, status, created_at
`

type UpdateTableStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) (Table, error) {
	row := q.db.QueryRow(ctx, updateTableStatus, arg.ID, arg.TenantID, arg.Status)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
