// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminDashboardStats = `-- name: AdminDashboardStats :one
SELECT
    (SELECT COUNT(*)::bigint FROM tenants) AS total_tenants,
    (SELECT COUNT(*)::bigint FROM tenants WHERE status = 'ACTIVE') AS active_tenants,
    (SELECT COUNT(*)::bigint FROM tenants WHERE status = 'SUSPENDED') AS suspended_tenants,
    (SELECT COUNT(*)::bigint FROM subscriptions WHERE status = 'TRIAL') AS trial_tenants,
    (SELECT COUNT(*)::bigint FROM tenants WHERE setup_status <> 'COMPLETED') AS pending_setup,
    (SELECT COUNT(*)::bigint FROM orders) AS total_orders,
    COALESCE((SELECT SUM(total) FROM orders WHERE status = 'COMPLETED'), 0)::text AS total_revenue,
    (SELECT COUNT(*)::bigint FROM orders WHERE created_at >= date_trunc('day', now())) AS orders_today,
    COALESCE((SELECT SUM(total) FROM orders WHERE created_at >= date_trunc('day', now())), 0)::text AS order_value_today,
    (SELECT COUNT(*)::bigint FROM users WHERE tenant_id IS NOT NULL AND status = 'ACTIVE') AS active_users
`

type AdminDashboardStatsRow struct {
	TotalTenants     int64  `json:"total_tenants"`
	ActiveTenants    int64  `json:"active_tenants"`
	SuspendedTenants int64  `json:"suspended_tenants"`
	TrialTenants     int64  `json:"trial_tenants"`
	PendingSetup     int64  `json:"pending_setup"`
	TotalOrders      int64  `json:"total_orders"`
	TotalRevenue     string `json:"total_revenue"`
	OrdersToday      int64  `json:"orders_today"`
	OrderValueToday  string `json:"order_value_today"`
	ActiveUsers      int64  `json:"active_users"`
}

func (q *Queries) AdminDashboardStats(ctx context.Context) (AdminDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, adminDashboardStats)
	var i AdminDashboardStatsRow
	err := row.Scan(
		&i.TotalTenants,
		&i.ActiveTenants,
		&i.SuspendedTenants,
		&i.TrialTenants,
		&i.PendingSetup,
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.OrdersToday,
		&i.OrderValueToday,
		&i.ActiveUsers,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name, slug, business_type, owner_name, phone, email, address, status, is_published, plan_id, setup_status,
    theme_preset_id, theme_color_mode, theme_overrides,
    logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message,
    mfa_allowed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, FALSE, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21, $22
)
RETURNING id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed
`

type CreateTenantParams struct {
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	BusinessType     string      `json:"business_type"`
	OwnerName        string      `json:"owner_name"`
	Phone            string      `json:"phone"`
	Email            string      `json:"email"`
	Address          string      `json:"address"`
	Status           string      `json:"status"`
	PlanID           pgtype.UUID `json:"plan_id"`
	SetupStatus      string      `json:"setup_status"`
	ThemePresetID    string      `json:"theme_preset_id"`
	ThemeColorMode   string      `json:"theme_color_mode"`
	ThemeOverrides   []byte      `json:"theme_overrides"`
	LogoUrl          string      `json:"logo_url"`
	FaviconUrl       string      `json:"favicon_url"`
	ShortDescription string      `json:"short_description"`
	Currency         string      `json:"currency"`
	Timezone         string      `json:"timezone"`
	Language         string      `json:"language"`
	StoreStatus      string      `json:"store_status"`
	StatusMessage    string      `json:"status_message"`
	MfaAllowed       bool        `json:"mfa_allowed"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.BusinessType,
		arg.OwnerName,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.Status,
		arg.PlanID,
		arg.SetupStatus,
		arg.ThemePresetID,
		arg.ThemeColorMode,
		arg.ThemeOverrides,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.ShortDescription,
		arg.Currency,
		arg.Timezone,
		arg.Language,
		arg.StoreStatus,
		arg.StatusMessage,
		arg.MfaAllowed,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed FROM tenants
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed FROM tenants
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}

const getTenantWithPlanByID = `-- name: GetTenantWithPlanByID :one
SELECT
    t.id, t.name, t.slug, t.business_type, t.owner_name, t.phone, t.email, t.address, t.status, t.created_at, t.updated_at, t.is_published, t.plan_id, t.setup_status, t.theme_preset_id, t.theme_color_mode, t.theme_overrides, t.logo_url, t.favicon_url, t.short_description, t.currency, t.timezone, t.language, t.store_status, t.status_message, t.mfa_allowed,
    p.name AS plan_name,
    p.price AS plan_price,
    tp.name AS theme_name,
    tp.tokens AS theme_tokens
FROM tenants t
LEFT JOIN plans p ON p.id = t.plan_id
LEFT JOIN theme_presets tp ON tp.id = t.theme_preset_id
WHERE t.id = $1
LIMIT 1
`

type GetTenantWithPlanByIDRow struct {
	Tenant      Tenant         `json:"tenant"`
	PlanName    pgtype.Text    `json:"plan_name"`
	PlanPrice   pgtype.Numeric `json:"plan_price"`
	ThemeName   pgtype.Text    `json:"theme_name"`
	ThemeTokens []byte         `json:"theme_tokens"`
}

func (q *Queries) GetTenantWithPlanByID(ctx context.Context, id pgtype.UUID) (GetTenantWithPlanByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantWithPlanByID, id)
	var i GetTenantWithPlanByIDRow
	err := row.Scan(
		&i.Tenant.ID,
		&i.Tenant.Name,
		&i.Tenant.Slug,
		&i.Tenant.BusinessType,
		&i.Tenant.OwnerName,
		&i.Tenant.Phone,
		&i.Tenant.Email,
		&i.Tenant.Address,
		&i.Tenant.Status,
		&i.Tenant.CreatedAt,
		&i.Tenant.UpdatedAt,
		&i.Tenant.IsPublished,
		&i.Tenant.PlanID,
		&i.Tenant.SetupStatus,
		&i.Tenant.ThemePresetID,
		&i.Tenant.ThemeColorMode,
		&i.Tenant.ThemeOverrides,
		&i.Tenant.LogoUrl,
		&i.Tenant.FaviconUrl,
		&i.Tenant.ShortDescription,
		&i.Tenant.Currency,
		&i.Tenant.Timezone,
		&i.Tenant.Language,
		&i.Tenant.StoreStatus,
		&i.Tenant.StatusMessage,
		&i.Tenant.MfaAllowed,
		&i.PlanName,
		&i.PlanPrice,
		&i.ThemeName,
		&i.ThemeTokens,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed FROM tenants
ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.BusinessType,
			&i.OwnerName,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPublished,
			&i.PlanID,
			&i.SetupStatus,
			&i.ThemePresetID,
			&i.ThemeColorMode,
			&i.ThemeOverrides,
			&i.LogoUrl,
			&i.FaviconUrl,
			&i.ShortDescription,
			&i.Currency,
			&i.Timezone,
			&i.Language,
			&i.StoreStatus,
			&i.StatusMessage,
			&i.MfaAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsWithPlans = `-- name: ListTenantsWithPlans :many
SELECT
    t.id, t.name, t.slug, t.business_type, t.owner_name, t.phone, t.email, t.address, t.status, t.created_at, t.updated_at, t.is_published, t.plan_id, t.setup_status, t.theme_preset_id, t.theme_color_mode, t.theme_overrides, t.logo_url, t.favicon_url, t.short_description, t.currency, t.timezone, t.language, t.store_status, t.status_message, t.mfa_allowed,
    p.name AS plan_name,
    p.price AS plan_price,
    tp.name AS theme_name,
    tp.tokens AS theme_tokens
FROM tenants t
LEFT JOIN plans p ON p.id = t.plan_id
LEFT JOIN theme_presets tp ON tp.id = t.theme_preset_id
ORDER BY t.created_at DESC
`

type ListTenantsWithPlansRow struct {
	Tenant      Tenant         `json:"tenant"`
	PlanName    pgtype.Text    `json:"plan_name"`
	PlanPrice   pgtype.Numeric `json:"plan_price"`
	ThemeName   pgtype.Text    `json:"theme_name"`
	ThemeTokens []byte         `json:"theme_tokens"`
}

func (q *Queries) ListTenantsWithPlans(ctx context.Context) ([]ListTenantsWithPlansRow, error) {
	rows, err := q.db.Query(ctx, listTenantsWithPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsWithPlansRow{}
	for rows.Next() {
		var i ListTenantsWithPlansRow
		if err := rows.Scan(
			&i.Tenant.ID,
			&i.Tenant.Name,
			&i.Tenant.Slug,
			&i.Tenant.BusinessType,
			&i.Tenant.OwnerName,
			&i.Tenant.Phone,
			&i.Tenant.Email,
			&i.Tenant.Address,
			&i.Tenant.Status,
			&i.Tenant.CreatedAt,
			&i.Tenant.UpdatedAt,
			&i.Tenant.IsPublished,
			&i.Tenant.PlanID,
			&i.Tenant.SetupStatus,
			&i.Tenant.ThemePresetID,
			&i.Tenant.ThemeColorMode,
			&i.Tenant.ThemeOverrides,
			&i.Tenant.LogoUrl,
			&i.Tenant.FaviconUrl,
			&i.Tenant.ShortDescription,
			&i.Tenant.Currency,
			&i.Tenant.Timezone,
			&i.Tenant.Language,
			&i.Tenant.StoreStatus,
			&i.Tenant.StatusMessage,
			&i.Tenant.MfaAllowed,
			&i.PlanName,
			&i.PlanPrice,
			&i.ThemeName,
			&i.ThemeTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantPublished = `-- name: SetTenantPublished :one
UPDATE tenants
SET is_published = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed
`

type SetTenantPublishedParams struct {
	ID          pgtype.UUID `json:"id"`
	IsPublished bool        `json:"is_published"`
}

func (q *Queries) SetTenantPublished(ctx context.Context, arg SetTenantPublishedParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantPublished, arg.ID, arg.IsPublished)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}

const setTenantSetupStatus = `-- name: SetTenantSetupStatus :one
UPDATE tenants
SET setup_status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed
`

type SetTenantSetupStatusParams struct {
	ID          pgtype.UUID `json:"id"`
	SetupStatus string      `json:"setup_status"`
}

func (q *Queries) SetTenantSetupStatus(ctx context.Context, arg SetTenantSetupStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantSetupStatus, arg.ID, arg.SetupStatus)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}

const setTenantStatus = `-- name: SetTenantStatus :one
UPDATE tenants
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed
`

type SetTenantStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantStatus, arg.ID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}

const setTenantTheme = `-- name: SetTenantTheme :one
UPDATE tenants
SET
    theme_preset_id = $2,
    theme_color_mode = $3,
    theme_overrides = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed
`

type SetTenantThemeParams struct {
	ID             pgtype.UUID `json:"id"`
	ThemePresetID  string      `json:"theme_preset_id"`
	ThemeColorMode string      `json:"theme_color_mode"`
	ThemeOverrides []byte      `json:"theme_overrides"`
}

func (q *Queries) SetTenantTheme(ctx context.Context, arg SetTenantThemeParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantTheme,
		arg.ID,
		arg.ThemePresetID,
		arg.ThemeColorMode,
		arg.ThemeOverrides,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    name = COALESCE($1, name),
    business_type = COALESCE($2, business_type),
    owner_name = COALESCE($3, owner_name),
    phone = COALESCE($4, phone),
    email = COALESCE($5, email),
    address = COALESCE($6, address),
    logo_url = COALESCE($7, logo_url),
    favicon_url = COALESCE($8, favicon_url),
    short_description = COALESCE($9, short_description),
    currency = COALESCE($10, currency),
    timezone = COALESCE($11, timezone),
    language = COALESCE($12, language),
    store_status = COALESCE($13, store_status),
    status_message = COALESCE($14, status_message),
    mfa_allowed = COALESCE($15, mfa_allowed),
    updated_at = now()
WHERE id = $16
RETURNING id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed
`

type UpdateTenantParams struct {
	Name             pgtype.Text `json:"name"`
	BusinessType     pgtype.Text `json:"business_type"`
	OwnerName        pgtype.Text `json:"owner_name"`
	Phone            pgtype.Text `json:"phone"`
	Email            pgtype.Text `json:"email"`
	Address          pgtype.Text `json:"address"`
	LogoUrl          pgtype.Text `json:"logo_url"`
	FaviconUrl       pgtype.Text `json:"favicon_url"`
	ShortDescription pgtype.Text `json:"short_description"`
	Currency         pgtype.Text `json:"currency"`
	Timezone         pgtype.Text `json:"timezone"`
	Language         pgtype.Text `json:"language"`
	StoreStatus      pgtype.Text `json:"store_status"`
	StatusMessage    pgtype.Text `json:"status_message"`
	MfaAllowed       pgtype.Bool `json:"mfa_allowed"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.Name,
		arg.BusinessType,
		arg.OwnerName,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.ShortDescription,
		arg.Currency,
		arg.Timezone,
		arg.Language,
		arg.StoreStatus,
		arg.StatusMessage,
		arg.MfaAllowed,
		arg.ID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}

const updateTenantPlanID = `-- name: UpdateTenantPlanID :one
UPDATE tenants
SET plan_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, business_type, owner_name, phone, email, address, status, created_at, updated_at, is_published, plan_id, setup_status, theme_preset_id, theme_color_mode, theme_overrides, logo_url, favicon_url, short_description, currency, timezone, language, store_status, status_message, mfa_allowed
`

type UpdateTenantPlanIDParams struct {
	ID     pgtype.UUID `json:"id"`
	PlanID pgtype.UUID `json:"plan_id"`
}

func (q *Queries) UpdateTenantPlanID(ctx context.Context, arg UpdateTenantPlanIDParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantPlanID, arg.ID, arg.PlanID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.OwnerName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.PlanID,
		&i.SetupStatus,
		&i.ThemePresetID,
		&i.ThemeColorMode,
		&i.ThemeOverrides,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.ShortDescription,
		&i.Currency,
		&i.Timezone,
		&i.Language,
		&i.StoreStatus,
		&i.StatusMessage,
		&i.MfaAllowed,
	)
	return i, err
}
