// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenant_types.sql

package sqlc

import (
	"context"
)

const createTenantType = `-- name: CreateTenantType :one
INSERT INTO tenant_types (code, label, active, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING code, label, active, sort_order, created_at
`

type CreateTenantTypeParams struct {
	Code      string `json:"code"`
	Label     string `json:"label"`
	Active    bool   `json:"active"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateTenantType(ctx context.Context, arg CreateTenantTypeParams) (TenantType, error) {
	row := q.db.QueryRow(ctx, createTenantType,
		arg.Code,
		arg.Label,
		arg.Active,
		arg.SortOrder,
	)
	var i TenantType
	err := row.Scan(
		&i.Code,
		&i.Label,
		&i.Active,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantType = `-- name: GetTenantType :one
SELECT code, label, active, sort_order, created_at
FROM tenant_types
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetTenantType(ctx context.Context, code string) (TenantType, error) {
	row := q.db.QueryRow(ctx, getTenantType, code)
	var i TenantType
	err := row.Scan(
		&i.Code,
		&i.Label,
		&i.Active,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantTypes = `-- name: ListTenantTypes :many
SELECT code, label, active, sort_order, created_at
FROM tenant_types
ORDER BY sort_order ASC, label ASC
`

func (q *Queries) ListTenantTypes(ctx context.Context) ([]TenantType, error) {
	rows, err := q.db.Query(ctx, listTenantTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantType{}
	for rows.Next() {
		var i TenantType
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.Active,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantType = `-- name: UpdateTenantType :one
UPDATE tenant_types
SET label = $2, active = $3, sort_order = $4
WHERE code = $1
RETURNING code, label, active, sort_order, created_at
`

type UpdateTenantTypeParams struct {
	Code      string `json:"code"`
	Label     string `json:"label"`
	Active    bool   `json:"active"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpdateTenantType(ctx context.Context, arg UpdateTenantTypeParams) (TenantType, error) {
	row := q.db.QueryRow(ctx, updateTenantType,
		arg.Code,
		arg.Label,
		arg.Active,
		arg.SortOrder,
	)
	var i TenantType
	err := row.Scan(
		&i.Code,
		&i.Label,
		&i.Active,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
