// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenant_analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const tenantOrdersByDayRange = `-- name: TenantOrdersByDayRange :many

SELECT
    date_trunc('day', created_at)::date AS day,
    COUNT(*)::bigint AS order_count,
    COALESCE(SUM(CASE WHEN status <> 'CANCELLED' THEN total ELSE 0 END), 0)::text AS revenue
FROM orders
WHERE tenant_id = $1
    AND created_at >= now() - $2::interval
GROUP BY 1
ORDER BY 1 ASC
`

type TenantOrdersByDayRangeParams struct {
	TenantID pgtype.UUID     `json:"tenant_id"`
	Days     pgtype.Interval `json:"days"`
}

type TenantOrdersByDayRangeRow struct {
	Day        pgtype.Date `json:"day"`
	OrderCount int64       `json:"order_count"`
	Revenue    string      `json:"revenue"`
}

// Analytics for the tenant-facing dashboard. Every query is scoped to a single
// tenant so the handler can never accidentally return another shop's numbers.
// Orders and revenue per day over a rolling window. Cancelled orders are
// excluded from revenue but still counted as orders, which is what an operator
// wants to see when judging how busy they were.
func (q *Queries) TenantOrdersByDayRange(ctx context.Context, arg TenantOrdersByDayRangeParams) ([]TenantOrdersByDayRangeRow, error) {
	rows, err := q.db.Query(ctx, tenantOrdersByDayRange, arg.TenantID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantOrdersByDayRangeRow{}
	for rows.Next() {
		var i TenantOrdersByDayRangeRow
		if err := rows.Scan(&i.Day, &i.OrderCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantOrdersByHour = `-- name: TenantOrdersByHour :many
SELECT
    EXTRACT(HOUR FROM created_at)::int AS hour_of_day,
    COUNT(*)::bigint AS order_count
FROM orders
WHERE tenant_id = $1
    AND created_at >= now() - $2::interval
GROUP BY 1
ORDER BY 1 ASC
`

type TenantOrdersByHourParams struct {
	TenantID pgtype.UUID     `json:"tenant_id"`
	Days     pgtype.Interval `json:"days"`
}

type TenantOrdersByHourRow struct {
	HourOfDay  int32 `json:"hour_of_day"`
	OrderCount int64 `json:"order_count"`
}

// Orders by hour of day, averaged over the window, so a single quiet Tuesday
// does not read as a permanently quiet hour.
func (q *Queries) TenantOrdersByHour(ctx context.Context, arg TenantOrdersByHourParams) ([]TenantOrdersByHourRow, error) {
	rows, err := q.db.Query(ctx, tenantOrdersByHour, arg.TenantID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantOrdersByHourRow{}
	for rows.Next() {
		var i TenantOrdersByHourRow
		if err := rows.Scan(&i.HourOfDay, &i.OrderCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantPeriodSummary = `-- name: TenantPeriodSummary :one
SELECT
    (SELECT COUNT(*)::bigint FROM orders o
      WHERE o.tenant_id = $1
        AND o.created_at >= date_trunc('day', now())) AS orders_today,
    (SELECT COALESCE(SUM(o.total), 0) FROM orders o
      WHERE o.tenant_id = $1
        AND o.status = 'COMPLETED'
        AND o.created_at >= date_trunc('day', now()))::text AS revenue_today,
    (SELECT COUNT(*)::bigint FROM orders o
      WHERE o.tenant_id = $1
        AND o.status <> 'CANCELLED'
        AND o.created_at >= now() - interval '7 days') AS orders_7d,
    (SELECT COALESCE(SUM(o.total), 0) FROM orders o
      WHERE o.tenant_id = $1
        AND o.status <> 'CANCELLED'
        AND o.created_at >= now() - interval '7 days')::text AS revenue_7d,
    (SELECT COUNT(*)::bigint FROM orders o
      WHERE o.tenant_id = $1
        AND o.status <> 'CANCELLED'
        AND o.created_at >= now() - interval '30 days') AS orders_30d,
    (SELECT COALESCE(SUM(o.total), 0) FROM orders o
      WHERE o.tenant_id = $1
        AND o.status <> 'CANCELLED'
        AND o.created_at >= now() - interval '30 days')::text AS revenue_30d,
    -- The 30 days before that, for the trend arrow.
    (SELECT COUNT(*)::bigint FROM orders o
      WHERE o.tenant_id = $1
        AND o.status <> 'CANCELLED'
        AND o.created_at >= now() - interval '60 days'
        AND o.created_at < now() - interval '30 days') AS orders_prev_30d,
    (SELECT COALESCE(SUM(o.total), 0) FROM orders o
      WHERE o.tenant_id = $1
        AND o.status <> 'CANCELLED'
        AND o.created_at >= now() - interval '60 days'
        AND o.created_at < now() - interval '30 days')::text AS revenue_prev_30d,
    (SELECT COUNT(*)::bigint FROM orders o
      WHERE o.tenant_id = $1
        AND o.status = 'PENDING') AS pending_orders,
    (SELECT COUNT(*)::bigint FROM orders o
      WHERE o.tenant_id = $1
        AND o.status = 'PREPARING') AS preparing_orders,
    (SELECT COUNT(*)::bigint FROM orders o
      WHERE o.tenant_id = $1
        AND o.status = 'READY') AS ready_orders,
    (SELECT COUNT(*)::bigint FROM orders o
      WHERE o.tenant_id = $1
        AND o.status = 'COMPLETED'
        AND o.created_at >= date_trunc('day', now())) AS completed_today,
    (SELECT COALESCE(AVG(o.total), 0) FROM orders o
      WHERE o.tenant_id = $1
        AND o.status <> 'CANCELLED'
        AND o.created_at >= now() - interval '30 days')::text AS avg_order_value_30d,
    (SELECT COUNT(*)::bigint FROM products p
      WHERE p.tenant_id = $1 AND p.is_available) AS products_available,
    (SELECT COUNT(*)::bigint FROM products p
      WHERE p.tenant_id = $1 AND NOT p.is_available) AS products_unavailable
`

type TenantPeriodSummaryRow struct {
	OrdersToday         int64  `json:"orders_today"`
	RevenueToday        string `json:"revenue_today"`
	Orders7d            int64  `json:"orders_7d"`
	Revenue7d           string `json:"revenue_7d"`
	Orders30d           int64  `json:"orders_30d"`
	Revenue30d          string `json:"revenue_30d"`
	OrdersPrev30d       int64  `json:"orders_prev_30d"`
	RevenuePrev30d      string `json:"revenue_prev_30d"`
	PendingOrders       int64  `json:"pending_orders"`
	PreparingOrders     int64  `json:"preparing_orders"`
	ReadyOrders         int64  `json:"ready_orders"`
	CompletedToday      int64  `json:"completed_today"`
	AvgOrderValue30d    string `json:"avg_order_value_30d"`
	ProductsAvailable   int64  `json:"products_available"`
	ProductsUnavailable int64  `json:"products_unavailable"`
}

// Headline figures plus the previous equivalent period, so the UI can show a
// real trend rather than a bare number.
func (q *Queries) TenantPeriodSummary(ctx context.Context, tenantID pgtype.UUID) (TenantPeriodSummaryRow, error) {
	row := q.db.QueryRow(ctx, tenantPeriodSummary, tenantID)
	var i TenantPeriodSummaryRow
	err := row.Scan(
		&i.OrdersToday,
		&i.RevenueToday,
		&i.Orders7d,
		&i.Revenue7d,
		&i.Orders30d,
		&i.Revenue30d,
		&i.OrdersPrev30d,
		&i.RevenuePrev30d,
		&i.PendingOrders,
		&i.PreparingOrders,
		&i.ReadyOrders,
		&i.CompletedToday,
		&i.AvgOrderValue30d,
		&i.ProductsAvailable,
		&i.ProductsUnavailable,
	)
	return i, err
}

const tenantTopProducts = `-- name: TenantTopProducts :many
SELECT
    p.name AS name,
    COALESCE(SUM(oi.quantity), 0)::bigint AS units,
    COALESCE(SUM(oi.quantity * oi.unit_price), 0)::text AS revenue
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
JOIN products p ON p.id = oi.product_id
WHERE o.tenant_id = $1
    AND o.status <> 'CANCELLED'
    AND o.created_at >= now() - $2::interval
GROUP BY p.id, p.name
ORDER BY units DESC, revenue DESC
LIMIT $3
`

type TenantTopProductsParams struct {
	TenantID pgtype.UUID     `json:"tenant_id"`
	Days     pgtype.Interval `json:"days"`
	RowLimit int32           `json:"row_limit"`
}

type TenantTopProductsRow struct {
	Name    string `json:"name"`
	Units   int64  `json:"units"`
	Revenue string `json:"revenue"`
}

// Best sellers by units, with the revenue they produced.
func (q *Queries) TenantTopProducts(ctx context.Context, arg TenantTopProductsParams) ([]TenantTopProductsRow, error) {
	rows, err := q.db.Query(ctx, tenantTopProducts, arg.TenantID, arg.Days, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantTopProductsRow{}
	for rows.Next() {
		var i TenantTopProductsRow
		if err := rows.Scan(&i.Name, &i.Units, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
