// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: themes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenantsOnThemePreset = `-- name: CountTenantsOnThemePreset :one
SELECT COUNT(*)::bigint
FROM tenants
WHERE theme_preset_id = $1
`

func (q *Queries) CountTenantsOnThemePreset(ctx context.Context, themePresetID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantsOnThemePreset, themePresetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createThemePreset = `-- name: CreateThemePreset :one
INSERT INTO theme_presets (id, name, tokens)
VALUES ($1, $2, $3)
RETURNING id, name, tokens, created_at
`

type CreateThemePresetParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Tokens []byte `json:"tokens"`
}

func (q *Queries) CreateThemePreset(ctx context.Context, arg CreateThemePresetParams) (ThemePreset, error) {
	row := q.db.QueryRow(ctx, createThemePreset, arg.ID, arg.Name, arg.Tokens)
	var i ThemePreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const deleteThemePreset = `-- name: DeleteThemePreset :exec
DELETE FROM theme_presets
WHERE id = $1
`

func (q *Queries) DeleteThemePreset(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteThemePreset, id)
	return err
}

const getThemePreset = `-- name: GetThemePreset :one
SELECT id, name, tokens, created_at
FROM theme_presets
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetThemePreset(ctx context.Context, id string) (ThemePreset, error) {
	row := q.db.QueryRow(ctx, getThemePreset, id)
	var i ThemePreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const listThemePresets = `-- name: ListThemePresets :many
SELECT id, name, tokens, created_at
FROM theme_presets
ORDER BY name ASC
`

func (q *Queries) ListThemePresets(ctx context.Context) ([]ThemePreset, error) {
	rows, err := q.db.Query(ctx, listThemePresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemePreset{}
	for rows.Next() {
		var i ThemePreset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThemePreset = `-- name: UpdateThemePreset :one
UPDATE theme_presets
SET
    name = COALESCE($1, name),
    tokens = COALESCE($2, tokens)
WHERE id = $3
RETURNING id, name, tokens, created_at
`

type UpdateThemePresetParams struct {
	Name   pgtype.Text `json:"name"`
	Tokens []byte      `json:"tokens"`
	ID     string      `json:"id"`
}

func (q *Queries) UpdateThemePreset(ctx context.Context, arg UpdateThemePresetParams) (ThemePreset, error) {
	row := q.db.QueryRow(ctx, updateThemePreset, arg.Name, arg.Tokens, arg.ID)
	var i ThemePreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}
