// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessionsByTenant = `-- name: CountActiveSessionsByTenant :many
SELECT
    u.id AS user_id,
    COUNT(rt.id)::bigint AS active_sessions
FROM users u
LEFT JOIN refresh_tokens rt
       ON rt.user_id = u.id
      AND rt.expires_at > now()
WHERE u.tenant_id = $1
GROUP BY u.id
`

type CountActiveSessionsByTenantRow struct {
	UserID         pgtype.UUID `json:"user_id"`
	ActiveSessions int64       `json:"active_sessions"`
}

// Session counts per user, for the IAM screen. Signing out deletes the refresh
// token rather than flagging it, so an unexpired row is an active session —
// the closest thing to "signed in somewhere" this schema records.
func (q *Queries) CountActiveSessionsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]CountActiveSessionsByTenantRow, error) {
	rows, err := q.db.Query(ctx, countActiveSessionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveSessionsByTenantRow{}
	for rows.Next() {
		var i CountActiveSessionsByTenantRow
		if err := rows.Scan(&i.UserID, &i.ActiveSessions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTenantUsers = `-- name: CountTenantUsers :one
SELECT COUNT(*)::bigint
FROM users
WHERE tenant_id = $1
`

func (q *Queries) CountTenantUsers(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantUsers, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTenantUsersByRole = `-- name: CountTenantUsersByRole :one
SELECT COUNT(*)::bigint
FROM users
WHERE tenant_id = $1
  AND role = $2
  AND status = 'ACTIVE'
`

type CountTenantUsersByRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Role     string      `json:"role"`
}

func (q *Queries) CountTenantUsersByRole(ctx context.Context, arg CountTenantUsersByRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantUsersByRole, arg.TenantID, arg.Role)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSuperAdmin = `-- name: CreateSuperAdmin :one
INSERT INTO users (
    tenant_id, name, email, phone, password_hash, role, status, must_set_password, invite_token_hash
) VALUES (
    NULL, $1, $2, '', $3, 'SUPER_ADMIN', 'ACTIVE', FALSE, NULL
)
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type CreateSuperAdminParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateSuperAdmin(ctx context.Context, arg CreateSuperAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, createSuperAdmin, arg.Name, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    tenant_id, name, email, phone, password_hash, role, status, must_set_password, invite_token_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type CreateUserParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	Name            string      `json:"name"`
	Email           string      `json:"email"`
	Phone           string      `json:"phone"`
	PasswordHash    string      `json:"password_hash"`
	Role            string      `json:"role"`
	Status          string      `json:"status"`
	MustSetPassword bool        `json:"must_set_password"`
	InviteTokenHash pgtype.Text `json:"invite_token_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.MustSetPassword,
		arg.InviteTokenHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const deleteRefreshTokensByUser = `-- name: DeleteRefreshTokensByUser :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUser, userID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantAdminForTenant = `-- name: GetTenantAdminForTenant :one
SELECT id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme FROM users
WHERE tenant_id = $1 AND role = 'TENANT_ADMIN'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetTenantAdminForTenant(ctx context.Context, tenantID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getTenantAdminForTenant, tenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const getUserByInviteTokenHash = `-- name: GetUserByInviteTokenHash :one
SELECT id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme FROM users
WHERE invite_token_hash = $1
LIMIT 1
`

func (q *Queries) GetUserByInviteTokenHash(ctx context.Context, inviteTokenHash pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByInviteTokenHash, inviteTokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const hasSuperAdmin = `-- name: HasSuperAdmin :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE role = 'SUPER_ADMIN' AND tenant_id IS NULL
) AS has_super_admin
`

func (q *Queries) HasSuperAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasSuperAdmin)
	var has_super_admin bool
	err := row.Scan(&has_super_admin)
	return has_super_admin, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type InsertRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantAdmins = `-- name: ListTenantAdmins :many
SELECT id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme FROM users
WHERE tenant_id = $1 AND role = 'TENANT_ADMIN'
ORDER BY created_at ASC
`

func (q *Queries) ListTenantAdmins(ctx context.Context, tenantID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listTenantAdmins, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MustSetPassword,
			&i.InviteTokenHash,
			&i.ConsoleTheme,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT
    u.id, u.tenant_id, u.name, u.email, u.phone, u.password_hash, u.role, u.status, u.created_at, u.updated_at, u.must_set_password, u.invite_token_hash, u.console_theme,
    (SELECT MAX(rt.created_at) FROM refresh_tokens rt WHERE rt.user_id = u.id) AS last_activity
FROM users u
WHERE u.tenant_id = $1
ORDER BY u.created_at ASC
`

type ListTenantUsersRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MustSetPassword bool               `json:"must_set_password"`
	InviteTokenHash pgtype.Text        `json:"invite_token_hash"`
	ConsoleTheme    []byte             `json:"console_theme"`
	LastActivity    interface{}        `json:"last_activity"`
}

func (q *Queries) ListTenantUsers(ctx context.Context, tenantID pgtype.UUID) ([]ListTenantUsersRow, error) {
	rows, err := q.db.Query(ctx, listTenantUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantUsersRow{}
	for rows.Next() {
		var i ListTenantUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MustSetPassword,
			&i.InviteTokenHash,
			&i.ConsoleTheme,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserAccess = `-- name: ResetUserAccess :one
UPDATE users
SET
    must_set_password = TRUE,
    invite_token_hash = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type ResetUserAccessParams struct {
	InviteTokenHash pgtype.Text `json:"invite_token_hash"`
	ID              pgtype.UUID `json:"id"`
}

// Clears the usable-password state and installs a fresh invite token so the
// user must complete setup again. Callers revoke refresh tokens separately.
func (q *Queries) ResetUserAccess(ctx context.Context, arg ResetUserAccessParams) (User, error) {
	row := q.db.QueryRow(ctx, resetUserAccess, arg.InviteTokenHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const setUserConsoleTheme = `-- name: SetUserConsoleTheme :one
UPDATE users
SET console_theme = $1, updated_at = now()
WHERE id = $2
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type SetUserConsoleThemeParams struct {
	ConsoleTheme []byte      `json:"console_theme"`
	ID           pgtype.UUID `json:"id"`
}

// The personal console appearance. Writing NULL is how a user goes back to the
// business default, so one statement covers both save and reset.
func (q *Queries) SetUserConsoleTheme(ctx context.Context, arg SetUserConsoleThemeParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserConsoleTheme, arg.ConsoleTheme, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :one
UPDATE users
SET
    password_hash = $2,
    must_set_password = FALSE,
    invite_token_hash = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type SetUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const setUserPasswordWithCurrent = `-- name: SetUserPasswordWithCurrent :one
UPDATE users
SET
    password_hash = $2,
    must_set_password = FALSE,
    invite_token_hash = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type SetUserPasswordWithCurrentParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) SetUserPasswordWithCurrent(ctx context.Context, arg SetUserPasswordWithCurrentParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPasswordWithCurrent, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users
SET role = $1, updated_at = now()
WHERE id = $2
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type SetUserRoleParams struct {
	Role string      `json:"role"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.Role, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type SetUserStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const updateUserInviteToken = `-- name: UpdateUserInviteToken :one
UPDATE users
SET
    invite_token_hash = $2,
    must_set_password = TRUE,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type UpdateUserInviteTokenParams struct {
	ID              pgtype.UUID `json:"id"`
	InviteTokenHash pgtype.Text `json:"invite_token_hash"`
}

func (q *Queries) UpdateUserInviteToken(ctx context.Context, arg UpdateUserInviteTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInviteToken, arg.ID, arg.InviteTokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    updated_at = now()
WHERE id = $3
RETURNING id, tenant_id, name, email, phone, password_hash, role, status, created_at, updated_at, must_set_password, invite_token_hash, console_theme
`

type UpdateUserProfileParams struct {
	Name  pgtype.Text `json:"name"`
	Phone pgtype.Text `json:"phone"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Name, arg.Phone, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustSetPassword,
		&i.InviteTokenHash,
		&i.ConsoleTheme,
	)
	return i, err
}
